// Code generated by "cmd/pgngen"; DO NOT EDIT.
package n2k

// SubscriptionId identifies a specific subscriber.
type SubscriptionId uint

func (n *N2kService) SubscribeToStruct(t any, callback any) (SubscriptionId, error) {
	return n.impl.SubscribeToStruct(t, callback)
}

func (n *N2kService) SubscribeToAllStructs(callback any) (SubscriptionId, error) {
	return n.impl.SubscribeToAllStructs(callback)
}

func (n *N2kService) Unsubscribe(subId SubscriptionId) error {
	return n.impl.Unsubscribe(subId)
}
