// Code generated by "cmd/pgngen"; DO NOT EDIT.
package pgn

import (
	"fmt"
)



// PgnDiscriminator contains the information needed to discriminate between PGN variants
type PgnDiscriminator struct {
	Decoder    func(MessageInfo, *DataStream) (any, error)
	MatchSpecs []MatchFieldSpec
}

// MatchFieldSpec contains a FieldSpec and the expected match value for discrimination
type MatchFieldSpec struct {
	FieldSpec  *FieldSpec
	MatchValue int
}

// PgnDiscriminatorMap maps PGN IDs to their discriminators
var PgnDiscriminatorMap = map[uint32][]PgnDiscriminator{
	59392: {
		{
			Decoder: DecodeIsoAcknowledgement,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	59904: {
		{
			Decoder: DecodeIsoRequest,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	60160: {
		{
			Decoder: DecodeIsoTransportProtocolDataTransfer,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	60416: {
		{
			Decoder: DecodeIsoTransportProtocolConnectionManagementRequestToSend,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 16,
				},
			},
		},
		{
			Decoder: DecodeIsoTransportProtocolConnectionManagementClearToSend,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 17,
				},
			},
		},
		{
			Decoder: DecodeIsoTransportProtocolConnectionManagementEndOfMessage,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 19,
				},
			},
		},
		{
			Decoder: DecodeIsoTransportProtocolConnectionManagementBroadcastAnnounce,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32,
				},
			},
		},
		{
			Decoder: DecodeIsoTransportProtocolConnectionManagementAbort,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 255,
				},
			},
		},
	},
	60928: {
		{
			Decoder: DecodeIsoAddressClaim,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65001: {
		{
			Decoder: DecodeBus1PhaseCBasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65002: {
		{
			Decoder: DecodeBus1PhaseBBasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65003: {
		{
			Decoder: DecodeBus1PhaseABasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65006: {
		{
			Decoder: DecodeUtilityPhaseCAcReactivePower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65007: {
		{
			Decoder: DecodeUtilityPhaseCAcPower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65008: {
		{
			Decoder: DecodeUtilityPhaseCBasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65009: {
		{
			Decoder: DecodeUtilityPhaseBAcReactivePower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65010: {
		{
			Decoder: DecodeUtilityPhaseBAcPower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65011: {
		{
			Decoder: DecodeUtilityPhaseBBasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65012: {
		{
			Decoder: DecodeUtilityPhaseAAcReactivePower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65013: {
		{
			Decoder: DecodeUtilityPhaseAAcPower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65014: {
		{
			Decoder: DecodeUtilityPhaseABasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65015: {
		{
			Decoder: DecodeUtilityTotalAcReactivePower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65016: {
		{
			Decoder: DecodeUtilityTotalAcPower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65017: {
		{
			Decoder: DecodeUtilityAverageBasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65019: {
		{
			Decoder: DecodeGeneratorPhaseCAcReactivePower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65020: {
		{
			Decoder: DecodeGeneratorPhaseCAcPower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65021: {
		{
			Decoder: DecodeGeneratorPhaseCBasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65022: {
		{
			Decoder: DecodeGeneratorPhaseBAcReactivePower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65023: {
		{
			Decoder: DecodeGeneratorPhaseBAcPower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65024: {
		{
			Decoder: DecodeGeneratorPhaseBBasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65025: {
		{
			Decoder: DecodeGeneratorPhaseAAcReactivePower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65026: {
		{
			Decoder: DecodeGeneratorPhaseAAcPower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65027: {
		{
			Decoder: DecodeGeneratorPhaseABasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65028: {
		{
			Decoder: DecodeGeneratorTotalAcReactivePower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65029: {
		{
			Decoder: DecodeGeneratorTotalAcPower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65030: {
		{
			Decoder: DecodeGeneratorAverageBasicAcQuantities,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65240: {
		{
			Decoder: DecodeIsoCommandedAddress,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	65284: {
		{
			Decoder: DecodeMaretronProprietaryDcBreakerCurrent,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 137,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	65285: {
		{
			Decoder: DecodeAirmarBootStateAcknowledgment,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
		{
			Decoder: DecodeLowranceTemperature,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 140,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	65286: {
		{
			Decoder: DecodeAirmarBootStateRequest,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	65287: {
		{
			Decoder: DecodeAirmarAccessLevel,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	65305: {
		{
			Decoder: DecodeSimnetDeviceStatus,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 1857,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 24,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 2,
				},
			},
		},
		{
			Decoder: DecodeSimnetDeviceStatusRequest,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 1857,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 24,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 3,
				},
			},
		},
		{
			Decoder: DecodeSimnetPilotMode,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 1857,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 24,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 10,
				},
			},
		},
		{
			Decoder: DecodeSimnetDeviceModeRequest,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 1857,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 24,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 11,
				},
			},
		},
	},
	65360: {
		{
			Decoder: DecodeSeatalkPilotLockedHeading,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 1851,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	65361: {
		{
			Decoder: DecodeSeatalkSilenceAlarm,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 1851,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	65409: {
		{
			Decoder: DecodeAirmarSpeedPulseCount,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	126208: {
		{
			Decoder: DecodeNmeaRequestGroupFunction,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 0,
				},
			},
		},
		{
			Decoder: DecodeNmeaCommandGroupFunction,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 1,
				},
			},
		},
		{
			Decoder: DecodeNmeaAcknowledgeGroupFunction,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 2,
				},
			},
		},
		{
			Decoder: DecodeNmeaReadFieldsReplyGroupFunction,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
		{
			Decoder: DecodeNmeaWriteFieldsGroupFunction,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 5,
				},
			},
		},
		{
			Decoder: DecodeNmeaWriteFieldsReplyGroupFunction,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 6,
				},
			},
		},
	},
	126464: {
		{
			Decoder: DecodePgnListTransmitAndReceive,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	126720: {
		{
			Decoder: DecodeFusionMediaControl,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 3,
				},
			},
		},
		{
			Decoder: DecodeFusionSiriusControl,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 30,
				},
			},
		},
		{
			Decoder: DecodeFusionRequestStatus,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 1,
				},
			},
		},
		{
			Decoder: DecodeFusionSetSource,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 2,
				},
			},
		},
		{
			Decoder: DecodeFusionSetMute,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 17,
				},
			},
		},
		{
			Decoder: DecodeFusionSetZoneVolume,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 24,
				},
			},
		},
		{
			Decoder: DecodeFusionSetAllVolumes,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 25,
				},
			},
		},
		{
			Decoder: DecodeAirmarAttitudeOffset,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32,
				},
			},
		},
		{
			Decoder: DecodeAirmarSimulateMode,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 35,
				},
			},
		},
		{
			Decoder: DecodeAirmarCalibrateDepth,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 40,
				},
			},
		},
		{
			Decoder: DecodeAirmarCalibrateSpeed,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 41,
				},
			},
		},
		{
			Decoder: DecodeAirmarCalibrateTemperature,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 42,
				},
			},
		},
		{
			Decoder: DecodeAirmarSpeedFilterNone,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 43,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 4,
						BitOffset: 24,
						MaxRawValue: 13,
						MissingValue: 15,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 2,
						BitLengthVariable: false,
						CanboatType: "NUMBER",
					},
					MatchValue: 0,
				},
			},
		},
		{
			Decoder: DecodeAirmarSpeedFilterIir,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 43,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 4,
						BitOffset: 24,
						MaxRawValue: 13,
						MissingValue: 15,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 2,
						BitLengthVariable: false,
						CanboatType: "NUMBER",
					},
					MatchValue: 1,
				},
			},
		},
		{
			Decoder: DecodeAirmarTemperatureFilterNone,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 44,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 4,
						BitOffset: 24,
						MaxRawValue: 13,
						MissingValue: 15,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 2,
						BitLengthVariable: false,
						CanboatType: "NUMBER",
					},
					MatchValue: 0,
				},
			},
		},
		{
			Decoder: DecodeAirmarTemperatureFilterIir,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 44,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 4,
						BitOffset: 24,
						MaxRawValue: 13,
						MissingValue: 15,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 2,
						BitLengthVariable: false,
						CanboatType: "NUMBER",
					},
					MatchValue: 1,
				},
			},
		},
		{
			Decoder: DecodeAirmarNmea2000Options,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 135,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 46,
				},
			},
		},
		{
			Decoder: DecodeMaretronDeviationCalibrationResponse,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 137,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 32,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 1,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 48,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 80,
				},
			},
		},
		{
			Decoder: DecodeMaretronSlaveResponse,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 137,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	126983: {
		{
			Decoder: DecodeAlert,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	126984: {
		{
			Decoder: DecodeAlertResponse,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	126985: {
		{
			Decoder: DecodeAlertText,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	126992: {
		{
			Decoder: DecodeSystemTime,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	126993: {
		{
			Decoder: DecodeHeartbeat,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	126996: {
		{
			Decoder: DecodeProductInformation,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	126998: {
		{
			Decoder: DecodeConfigurationInformation,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127233: {
		{
			Decoder: DecodeManOverboardNotification,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127237: {
		{
			Decoder: DecodeHeadingTrackControl,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127245: {
		{
			Decoder: DecodeRudder,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127250: {
		{
			Decoder: DecodeVesselHeading,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127251: {
		{
			Decoder: DecodeRateOfTurn,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127257: {
		{
			Decoder: DecodeAttitude,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127258: {
		{
			Decoder: DecodeMagneticVariation,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127488: {
		{
			Decoder: DecodeEngineParametersRapidUpdate,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127489: {
		{
			Decoder: DecodeEngineParametersDynamic,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127493: {
		{
			Decoder: DecodeTransmissionParametersDynamic,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127496: {
		{
			Decoder: DecodeTripParametersVessel,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127497: {
		{
			Decoder: DecodeTripParametersEngine,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127498: {
		{
			Decoder: DecodeEngineParametersStatic,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127500: {
		{
			Decoder: DecodeLoadControllerConnectionStateControl,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127501: {
		{
			Decoder: DecodeBinarySwitchBankStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127502: {
		{
			Decoder: DecodeSwitchBankControl,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127503: {
		{
			Decoder: DecodeAcInputStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127504: {
		{
			Decoder: DecodeAcOutputStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127505: {
		{
			Decoder: DecodeFluidLevel,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127506: {
		{
			Decoder: DecodeDcDetailedStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127507: {
		{
			Decoder: DecodeChargerStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127508: {
		{
			Decoder: DecodeBatteryStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127509: {
		{
			Decoder: DecodeInverterStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127744: {
		{
			Decoder: DecodeAcPowerCurrentPhaseA,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127745: {
		{
			Decoder: DecodeAcPowerCurrentPhaseB,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127746: {
		{
			Decoder: DecodeAcPowerCurrentPhaseC,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127747: {
		{
			Decoder: DecodeAcVoltageFrequencyPhaseA,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127748: {
		{
			Decoder: DecodeAcVoltageFrequencyPhaseB,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127749: {
		{
			Decoder: DecodeAcVoltageFrequencyPhaseC,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127750: {
		{
			Decoder: DecodeConverterStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	127751: {
		{
			Decoder: DecodeDcVoltageCurrent,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	128000: {
		{
			Decoder: DecodeLeewayAngle,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	128006: {
		{
			Decoder: DecodeThrusterControlStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	128007: {
		{
			Decoder: DecodeThrusterInformation,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	128008: {
		{
			Decoder: DecodeThrusterMotorStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	128259: {
		{
			Decoder: DecodeSpeed,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	128267: {
		{
			Decoder: DecodeWaterDepth,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	128275: {
		{
			Decoder: DecodeDistanceLog,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	128776: {
		{
			Decoder: DecodeWindlassControlStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	128777: {
		{
			Decoder: DecodeAnchorWindlassOperatingStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	128778: {
		{
			Decoder: DecodeAnchorWindlassMonitoringStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129025: {
		{
			Decoder: DecodePositionRapidUpdate,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129026: {
		{
			Decoder: DecodeCogSogRapidUpdate,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129029: {
		{
			Decoder: DecodeGnssPositionData,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129033: {
		{
			Decoder: DecodeTimeDate,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129038: {
		{
			Decoder: DecodeAisClassAPositionReport,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129039: {
		{
			Decoder: DecodeAisClassBPositionReport,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129041: {
		{
			Decoder: DecodeAisAidsToNavigationAtonReport,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129044: {
		{
			Decoder: DecodeDatum,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129045: {
		{
			Decoder: DecodeUserDatum,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129283: {
		{
			Decoder: DecodeCrossTrackError,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129284: {
		{
			Decoder: DecodeNavigationData,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129285: {
		{
			Decoder: DecodeNavigationRouteWpInformation,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129539: {
		{
			Decoder: DecodeGnssDops,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129540: {
		{
			Decoder: DecodeGnssSatsInView,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129546: {
		{
			Decoder: DecodeGnssRaimSettings,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129547: {
		{
			Decoder: DecodeGnssPseudorangeErrorStatistics,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129549: {
		{
			Decoder: DecodeDgnssCorrections,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129550: {
		{
			Decoder: DecodeGnssDifferentialCorrectionReceiverInterface,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129551: {
		{
			Decoder: DecodeGnssDifferentialCorrectionReceiverSignal,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129556: {
		{
			Decoder: DecodeGlonassAlmanacData,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129794: {
		{
			Decoder: DecodeAisClassAStaticAndVoyageRelatedData,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129795: {
		{
			Decoder: DecodeAisAddressedBinaryMessage,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129796: {
		{
			Decoder: DecodeAisAcknowledge,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129797: {
		{
			Decoder: DecodeAisBinaryBroadcastMessage,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129799: {
		{
			Decoder: DecodeRadioFrequencyModePower,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129809: {
		{
			Decoder: DecodeAisClassBStaticDataMsg24PartA,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	129810: {
		{
			Decoder: DecodeAisClassBStaticDataMsg24PartB,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130064: {
		{
			Decoder: DecodeRouteAndWpServiceDatabaseList,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130065: {
		{
			Decoder: DecodeRouteAndWpServiceRouteList,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130066: {
		{
			Decoder: DecodeRouteAndWpServiceRouteWpListAttributes,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130067: {
		{
			Decoder: DecodeRouteAndWpServiceRouteWpNamePosition,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130068: {
		{
			Decoder: DecodeRouteAndWpServiceRouteWpName,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130069: {
		{
			Decoder: DecodeRouteAndWpServiceXteLimitNavigationMethod,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130070: {
		{
			Decoder: DecodeRouteAndWpServiceWpComment,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130071: {
		{
			Decoder: DecodeRouteAndWpServiceRouteComment,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130072: {
		{
			Decoder: DecodeRouteAndWpServiceDatabaseComment,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130073: {
		{
			Decoder: DecodeRouteAndWpServiceRadiusOfTurn,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130074: {
		{
			Decoder: DecodeRouteAndWpServiceWpListWpNamePosition,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130306: {
		{
			Decoder: DecodeWindData,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130310: {
		{
			Decoder: DecodeEnvironmentalParametersObsolete,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130311: {
		{
			Decoder: DecodeEnvironmentalParameters,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130312: {
		{
			Decoder: DecodeTemperature,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130313: {
		{
			Decoder: DecodeHumidity,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130314: {
		{
			Decoder: DecodeActualPressure,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130315: {
		{
			Decoder: DecodeSetPressure,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130316: {
		{
			Decoder: DecodeTemperatureExtendedRange,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130320: {
		{
			Decoder: DecodeTideStationData,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130567: {
		{
			Decoder: DecodeWatermakerInputSettingAndStatus,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130578: {
		{
			Decoder: DecodeVesselSpeedComponents,
			MatchSpecs: []MatchFieldSpec{
			},
		},
	},
	130816: {
		{
			Decoder: DecodeSonichubVolume,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 275,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 8,
						BitOffset: 24,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 24,
				},
			},
		},
	},
	130820: {
		{
			Decoder: DecodeFusionVersions,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32769,
				},
			},
		},
		{
			Decoder: DecodeFusionSource,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32770,
				},
			},
		},
		{
			Decoder: DecodeFusionSourceCount,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32771,
				},
			},
		},
		{
			Decoder: DecodeFusionMedia,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32772,
				},
			},
		},
		{
			Decoder: DecodeFusionTrackName,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32773,
				},
			},
		},
		{
			Decoder: DecodeFusionArtistName,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32774,
				},
			},
		},
		{
			Decoder: DecodeFusionAlbumName,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32775,
				},
			},
		},
		{
			Decoder: DecodeFusionDeviceName,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32801,
				},
			},
		},
		{
			Decoder: DecodeFusionZoneName,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32813,
				},
			},
		},
		{
			Decoder: DecodeFusionTrackPosition,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32777,
				},
			},
		},
		{
			Decoder: DecodeFusionTuner,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32779,
				},
			},
		},
		{
			Decoder: DecodeFusionMarineTuner,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32780,
				},
			},
		},
		{
			Decoder: DecodeFusionMarineSquelch,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32781,
				},
			},
		},
		{
			Decoder: DecodeFusionMarineScanMode,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32782,
				},
			},
		},
		{
			Decoder: DecodeFusionMenuItem,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32785,
				},
			},
		},
		{
			Decoder: DecodeFusionAuxGain,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32787,
				},
			},
		},
		{
			Decoder: DecodeFusionUsbRepeatStatus,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32788,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 32,
						BitOffset: 32,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 9,
				},
			},
		},
		{
			Decoder: DecodeFusionSetting,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32788,
				},
			},
		},
		{
			Decoder: DecodeFusionSettings,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32789,
				},
			},
		},
		{
			Decoder: DecodeFusionMute,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32791,
				},
			},
		},
		{
			Decoder: DecodeFusionBalance,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32792,
				},
			},
		},
		{
			Decoder: DecodeFusionLowPassFilter,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32793,
				},
			},
		},
		{
			Decoder: DecodeFusionSublevels,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32794,
				},
			},
		},
		{
			Decoder: DecodeFusionEq,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32795,
				},
			},
		},
		{
			Decoder: DecodeFusionVolumeLimits,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32796,
				},
			},
		},
		{
			Decoder: DecodeFusionVolumes,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32797,
				},
			},
		},
		{
			Decoder: DecodeFusionCapabilities,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32798,
				},
			},
		},
		{
			Decoder: DecodeFusionLineLevelControl,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32799,
				},
			},
		},
		{
			Decoder: DecodeFusionPowerState,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32800,
				},
			},
		},
		{
			Decoder: DecodeFusionSiriusxm,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32802,
				},
			},
		},
		{
			Decoder: DecodeFusionSiriusxmChannel,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32804,
				},
			},
		},
		{
			Decoder: DecodeFusionSiriusxmTitle,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32805,
				},
			},
		},
		{
			Decoder: DecodeFusionSiriusxmArtist,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32806,
				},
			},
		},
		{
			Decoder: DecodeFusionSiriusxmContentInfo,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32807,
				},
			},
		},
		{
			Decoder: DecodeFusionSiriusxmCategory,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32808,
				},
			},
		},
		{
			Decoder: DecodeFusionSiriusxmSignal,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32809,
				},
			},
		},
		{
			Decoder: DecodeFusionSiriusxmPresets,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 419,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 16,
						BitOffset: 16,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 32812,
				},
			},
		},
	},
	130823: {
		{
			Decoder: DecodeMaretronProprietaryTemperatureHighRange,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 137,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	130824: {
		{
			Decoder: DecodeBGKeyValueData,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 381,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	130836: {
		{
			Decoder: DecodeMaretronSwitchStatusCounter,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 137,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
	130837: {
		{
			Decoder: DecodeMaretronSwitchStatusTimer,
			MatchSpecs: []MatchFieldSpec{
				{
					FieldSpec: &FieldSpec{
						BitLength: 11,
						BitOffset: 0,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 137,
				},
				{
					FieldSpec: &FieldSpec{
						BitLength: 3,
						BitOffset: 13,
						MaxRawValue: 0,
						MissingValue: 0,
						Resolution: 1,
						Offset: 0,
						IsSigned: false,
						ReservedCount: 0,
						BitLengthVariable: false,
						CanboatType: "LOOKUP",
					},
					MatchValue: 4,
				},
			},
		},
	},
}

// FindDecoder finds the appropriate decoder for a PGN based on match field values
func FindDecoder(stream *DataStream, pgn uint32) (func(MessageInfo, *DataStream) (any, error), error) {
	discriminators, exists := PgnDiscriminatorMap[pgn]
	if !exists {
		return nil, fmt.Errorf("no decoder found for PGN %d", pgn)
	}
	
	for _, discriminator := range discriminators {
		if matchesVariant(stream, discriminator.MatchSpecs) {
			return discriminator.Decoder, nil
		}
	}
	
	return nil, fmt.Errorf("no matching variant found for PGN %d", pgn)
}

// matchesVariant checks if the data stream matches the specified variant's match fields
func matchesVariant(stream *DataStream, matchSpecs []MatchFieldSpec) bool {
	// Save current position
	originalPos := stream.Position()
	defer stream.SetPosition(originalPos)
	
	for _, matchSpec := range matchSpecs {
		// Set position to the field's bit offset
		stream.SetPosition(matchSpec.FieldSpec.BitOffset)
		
		// Use ReadRaw since match values are raw (unscaled)
		if value, err := ReadRaw[uint64](stream, matchSpec.FieldSpec); err != nil {
			return false
		} else if value == nil || *value != uint64(matchSpec.MatchValue) {
			return false
		}
	}
	return true
}
