// Code generated by "cmd/pgngen"; DO NOT EDIT.
package pgn

import (
	"fmt"

	publicpgn "github.com/boatkit-io/n2k/pkg/pgn"
)

// EncodeStruct encodes a public PGN struct to NMEA 2000 wire format.
func EncodeStruct(s any, stream *DataStream) (*publicpgn.MessageInfo, error) {
	switch p := s.(type) {
	case *publicpgn.ISOAcknowledgement:
		return EncodeISOAcknowledgement(p, stream)
	case publicpgn.ISOAcknowledgement:
		return EncodeISOAcknowledgement(&p, stream)
	case *publicpgn.ISORequest:
		return EncodeISORequest(p, stream)
	case publicpgn.ISORequest:
		return EncodeISORequest(&p, stream)
	case *publicpgn.ISOTransportProtocolDataTransfer:
		return EncodeISOTransportProtocolDataTransfer(p, stream)
	case publicpgn.ISOTransportProtocolDataTransfer:
		return EncodeISOTransportProtocolDataTransfer(&p, stream)
	case *publicpgn.ISOTransportProtocolConnectionManagementRequestToSend:
		return EncodeISOTransportProtocolConnectionManagementRequestToSend(p, stream)
	case publicpgn.ISOTransportProtocolConnectionManagementRequestToSend:
		return EncodeISOTransportProtocolConnectionManagementRequestToSend(&p, stream)
	case *publicpgn.ISOTransportProtocolConnectionManagementClearToSend:
		return EncodeISOTransportProtocolConnectionManagementClearToSend(p, stream)
	case publicpgn.ISOTransportProtocolConnectionManagementClearToSend:
		return EncodeISOTransportProtocolConnectionManagementClearToSend(&p, stream)
	case *publicpgn.ISOTransportProtocolConnectionManagementEndOfMessage:
		return EncodeISOTransportProtocolConnectionManagementEndOfMessage(p, stream)
	case publicpgn.ISOTransportProtocolConnectionManagementEndOfMessage:
		return EncodeISOTransportProtocolConnectionManagementEndOfMessage(&p, stream)
	case *publicpgn.ISOTransportProtocolConnectionManagementBroadcastAnnounce:
		return EncodeISOTransportProtocolConnectionManagementBroadcastAnnounce(p, stream)
	case publicpgn.ISOTransportProtocolConnectionManagementBroadcastAnnounce:
		return EncodeISOTransportProtocolConnectionManagementBroadcastAnnounce(&p, stream)
	case *publicpgn.ISOTransportProtocolConnectionManagementAbort:
		return EncodeISOTransportProtocolConnectionManagementAbort(p, stream)
	case publicpgn.ISOTransportProtocolConnectionManagementAbort:
		return EncodeISOTransportProtocolConnectionManagementAbort(&p, stream)
	case *publicpgn.ISOAddressClaim:
		return EncodeISOAddressClaim(p, stream)
	case publicpgn.ISOAddressClaim:
		return EncodeISOAddressClaim(&p, stream)
	case *publicpgn.CarlingBreakerCommand:
		return EncodeCarlingBreakerCommand(p, stream)
	case publicpgn.CarlingBreakerCommand:
		return EncodeCarlingBreakerCommand(&p, stream)
	case *publicpgn.Bus1PhaseCBasicACQuantities:
		return EncodeBus1PhaseCBasicACQuantities(p, stream)
	case publicpgn.Bus1PhaseCBasicACQuantities:
		return EncodeBus1PhaseCBasicACQuantities(&p, stream)
	case *publicpgn.Bus1PhaseBBasicACQuantities:
		return EncodeBus1PhaseBBasicACQuantities(p, stream)
	case publicpgn.Bus1PhaseBBasicACQuantities:
		return EncodeBus1PhaseBBasicACQuantities(&p, stream)
	case *publicpgn.Bus1PhaseABasicACQuantities:
		return EncodeBus1PhaseABasicACQuantities(p, stream)
	case publicpgn.Bus1PhaseABasicACQuantities:
		return EncodeBus1PhaseABasicACQuantities(&p, stream)
	case *publicpgn.UtilityPhaseCACReactivePower:
		return EncodeUtilityPhaseCACReactivePower(p, stream)
	case publicpgn.UtilityPhaseCACReactivePower:
		return EncodeUtilityPhaseCACReactivePower(&p, stream)
	case *publicpgn.UtilityPhaseCACPower:
		return EncodeUtilityPhaseCACPower(p, stream)
	case publicpgn.UtilityPhaseCACPower:
		return EncodeUtilityPhaseCACPower(&p, stream)
	case *publicpgn.UtilityPhaseCBasicACQuantities:
		return EncodeUtilityPhaseCBasicACQuantities(p, stream)
	case publicpgn.UtilityPhaseCBasicACQuantities:
		return EncodeUtilityPhaseCBasicACQuantities(&p, stream)
	case *publicpgn.UtilityPhaseBACReactivePower:
		return EncodeUtilityPhaseBACReactivePower(p, stream)
	case publicpgn.UtilityPhaseBACReactivePower:
		return EncodeUtilityPhaseBACReactivePower(&p, stream)
	case *publicpgn.UtilityPhaseBACPower:
		return EncodeUtilityPhaseBACPower(p, stream)
	case publicpgn.UtilityPhaseBACPower:
		return EncodeUtilityPhaseBACPower(&p, stream)
	case *publicpgn.UtilityPhaseBBasicACQuantities:
		return EncodeUtilityPhaseBBasicACQuantities(p, stream)
	case publicpgn.UtilityPhaseBBasicACQuantities:
		return EncodeUtilityPhaseBBasicACQuantities(&p, stream)
	case *publicpgn.UtilityPhaseAACReactivePower:
		return EncodeUtilityPhaseAACReactivePower(p, stream)
	case publicpgn.UtilityPhaseAACReactivePower:
		return EncodeUtilityPhaseAACReactivePower(&p, stream)
	case *publicpgn.UtilityPhaseAACPower:
		return EncodeUtilityPhaseAACPower(p, stream)
	case publicpgn.UtilityPhaseAACPower:
		return EncodeUtilityPhaseAACPower(&p, stream)
	case *publicpgn.UtilityPhaseABasicACQuantities:
		return EncodeUtilityPhaseABasicACQuantities(p, stream)
	case publicpgn.UtilityPhaseABasicACQuantities:
		return EncodeUtilityPhaseABasicACQuantities(&p, stream)
	case *publicpgn.UtilityTotalACReactivePower:
		return EncodeUtilityTotalACReactivePower(p, stream)
	case publicpgn.UtilityTotalACReactivePower:
		return EncodeUtilityTotalACReactivePower(&p, stream)
	case *publicpgn.UtilityTotalACPower:
		return EncodeUtilityTotalACPower(p, stream)
	case publicpgn.UtilityTotalACPower:
		return EncodeUtilityTotalACPower(&p, stream)
	case *publicpgn.UtilityAverageBasicACQuantities:
		return EncodeUtilityAverageBasicACQuantities(p, stream)
	case publicpgn.UtilityAverageBasicACQuantities:
		return EncodeUtilityAverageBasicACQuantities(&p, stream)
	case *publicpgn.GeneratorPhaseCACReactivePower:
		return EncodeGeneratorPhaseCACReactivePower(p, stream)
	case publicpgn.GeneratorPhaseCACReactivePower:
		return EncodeGeneratorPhaseCACReactivePower(&p, stream)
	case *publicpgn.GeneratorPhaseCACPower:
		return EncodeGeneratorPhaseCACPower(p, stream)
	case publicpgn.GeneratorPhaseCACPower:
		return EncodeGeneratorPhaseCACPower(&p, stream)
	case *publicpgn.GeneratorPhaseCBasicACQuantities:
		return EncodeGeneratorPhaseCBasicACQuantities(p, stream)
	case publicpgn.GeneratorPhaseCBasicACQuantities:
		return EncodeGeneratorPhaseCBasicACQuantities(&p, stream)
	case *publicpgn.GeneratorPhaseBACReactivePower:
		return EncodeGeneratorPhaseBACReactivePower(p, stream)
	case publicpgn.GeneratorPhaseBACReactivePower:
		return EncodeGeneratorPhaseBACReactivePower(&p, stream)
	case *publicpgn.GeneratorPhaseBACPower:
		return EncodeGeneratorPhaseBACPower(p, stream)
	case publicpgn.GeneratorPhaseBACPower:
		return EncodeGeneratorPhaseBACPower(&p, stream)
	case *publicpgn.GeneratorPhaseBBasicACQuantities:
		return EncodeGeneratorPhaseBBasicACQuantities(p, stream)
	case publicpgn.GeneratorPhaseBBasicACQuantities:
		return EncodeGeneratorPhaseBBasicACQuantities(&p, stream)
	case *publicpgn.GeneratorPhaseAACReactivePower:
		return EncodeGeneratorPhaseAACReactivePower(p, stream)
	case publicpgn.GeneratorPhaseAACReactivePower:
		return EncodeGeneratorPhaseAACReactivePower(&p, stream)
	case *publicpgn.GeneratorPhaseAACPower:
		return EncodeGeneratorPhaseAACPower(p, stream)
	case publicpgn.GeneratorPhaseAACPower:
		return EncodeGeneratorPhaseAACPower(&p, stream)
	case *publicpgn.GeneratorPhaseABasicACQuantities:
		return EncodeGeneratorPhaseABasicACQuantities(p, stream)
	case publicpgn.GeneratorPhaseABasicACQuantities:
		return EncodeGeneratorPhaseABasicACQuantities(&p, stream)
	case *publicpgn.GeneratorTotalACReactivePower:
		return EncodeGeneratorTotalACReactivePower(p, stream)
	case publicpgn.GeneratorTotalACReactivePower:
		return EncodeGeneratorTotalACReactivePower(&p, stream)
	case *publicpgn.GeneratorTotalACPower:
		return EncodeGeneratorTotalACPower(p, stream)
	case publicpgn.GeneratorTotalACPower:
		return EncodeGeneratorTotalACPower(&p, stream)
	case *publicpgn.GeneratorAverageBasicACQuantities:
		return EncodeGeneratorAverageBasicACQuantities(p, stream)
	case publicpgn.GeneratorAverageBasicACQuantities:
		return EncodeGeneratorAverageBasicACQuantities(&p, stream)
	case *publicpgn.ISOCommandedAddress:
		return EncodeISOCommandedAddress(p, stream)
	case publicpgn.ISOCommandedAddress:
		return EncodeISOCommandedAddress(&p, stream)
	case *publicpgn.MaretronNumberOfChannels:
		return EncodeMaretronNumberOfChannels(p, stream)
	case publicpgn.MaretronNumberOfChannels:
		return EncodeMaretronNumberOfChannels(&p, stream)
	case *publicpgn.MaretronProprietaryDCBreakerCurrent:
		return EncodeMaretronProprietaryDCBreakerCurrent(p, stream)
	case publicpgn.MaretronProprietaryDCBreakerCurrent:
		return EncodeMaretronProprietaryDCBreakerCurrent(&p, stream)
	case *publicpgn.AirmarBootStateAcknowledgment:
		return EncodeAirmarBootStateAcknowledgment(p, stream)
	case publicpgn.AirmarBootStateAcknowledgment:
		return EncodeAirmarBootStateAcknowledgment(&p, stream)
	case *publicpgn.LowranceTemperature:
		return EncodeLowranceTemperature(p, stream)
	case publicpgn.LowranceTemperature:
		return EncodeLowranceTemperature(&p, stream)
	case *publicpgn.AirmarBootStateRequest:
		return EncodeAirmarBootStateRequest(p, stream)
	case publicpgn.AirmarBootStateRequest:
		return EncodeAirmarBootStateRequest(&p, stream)
	case *publicpgn.AirmarAccessLevel:
		return EncodeAirmarAccessLevel(p, stream)
	case publicpgn.AirmarAccessLevel:
		return EncodeAirmarAccessLevel(&p, stream)
	case *publicpgn.LowranceVesselSetupEngineAndTankConfiguration:
		return EncodeLowranceVesselSetupEngineAndTankConfiguration(p, stream)
	case publicpgn.LowranceVesselSetupEngineAndTankConfiguration:
		return EncodeLowranceVesselSetupEngineAndTankConfiguration(&p, stream)
	case *publicpgn.LowranceVesselSetupEngineAndTankConfigurationBroadcast:
		return EncodeLowranceVesselSetupEngineAndTankConfigurationBroadcast(p, stream)
	case publicpgn.LowranceVesselSetupEngineAndTankConfigurationBroadcast:
		return EncodeLowranceVesselSetupEngineAndTankConfigurationBroadcast(&p, stream)
	case *publicpgn.SimnetDeviceStatus:
		return EncodeSimnetDeviceStatus(p, stream)
	case publicpgn.SimnetDeviceStatus:
		return EncodeSimnetDeviceStatus(&p, stream)
	case *publicpgn.SimnetDeviceStatusRequest:
		return EncodeSimnetDeviceStatusRequest(p, stream)
	case publicpgn.SimnetDeviceStatusRequest:
		return EncodeSimnetDeviceStatusRequest(&p, stream)
	case *publicpgn.SimnetPilotMode:
		return EncodeSimnetPilotMode(p, stream)
	case publicpgn.SimnetPilotMode:
		return EncodeSimnetPilotMode(&p, stream)
	case *publicpgn.SimnetDeviceModeRequest:
		return EncodeSimnetDeviceModeRequest(p, stream)
	case publicpgn.SimnetDeviceModeRequest:
		return EncodeSimnetDeviceModeRequest(&p, stream)
	case *publicpgn.NavicoDepthQuality:
		return EncodeNavicoDepthQuality(p, stream)
	case publicpgn.NavicoDepthQuality:
		return EncodeNavicoDepthQuality(&p, stream)
	case *publicpgn.SeatalkPilotLockedHeading:
		return EncodeSeatalkPilotLockedHeading(p, stream)
	case publicpgn.SeatalkPilotLockedHeading:
		return EncodeSeatalkPilotLockedHeading(&p, stream)
	case *publicpgn.SeatalkSilenceAlarm:
		return EncodeSeatalkSilenceAlarm(p, stream)
	case publicpgn.SeatalkSilenceAlarm:
		return EncodeSeatalkSilenceAlarm(&p, stream)
	case *publicpgn.AirmarSpeedPulseCount:
		return EncodeAirmarSpeedPulseCount(p, stream)
	case publicpgn.AirmarSpeedPulseCount:
		return EncodeAirmarSpeedPulseCount(&p, stream)
	case *publicpgn.NMEARequestGroupFunction:
		return EncodeNMEARequestGroupFunction(p, stream)
	case publicpgn.NMEARequestGroupFunction:
		return EncodeNMEARequestGroupFunction(&p, stream)
	case *publicpgn.NMEARequestGroupFunctionPartial:
		return EncodeNMEARequestGroupFunctionPartial(p, stream)
	case publicpgn.NMEARequestGroupFunctionPartial:
		return EncodeNMEARequestGroupFunctionPartial(&p, stream)
	case *publicpgn.NMEACommandGroupFunction:
		return EncodeNMEACommandGroupFunction(p, stream)
	case publicpgn.NMEACommandGroupFunction:
		return EncodeNMEACommandGroupFunction(&p, stream)
	case *publicpgn.NMEACommandGroupFunctionPartial:
		return EncodeNMEACommandGroupFunctionPartial(p, stream)
	case publicpgn.NMEACommandGroupFunctionPartial:
		return EncodeNMEACommandGroupFunctionPartial(&p, stream)
	case *publicpgn.NMEAAcknowledgeGroupFunction:
		return EncodeNMEAAcknowledgeGroupFunction(p, stream)
	case publicpgn.NMEAAcknowledgeGroupFunction:
		return EncodeNMEAAcknowledgeGroupFunction(&p, stream)
	case *publicpgn.NMEAAcknowledgeGroupFunctionPartial:
		return EncodeNMEAAcknowledgeGroupFunctionPartial(p, stream)
	case publicpgn.NMEAAcknowledgeGroupFunctionPartial:
		return EncodeNMEAAcknowledgeGroupFunctionPartial(&p, stream)
	case *publicpgn.NMEAReadFieldsReplyGroupFunction:
		return EncodeNMEAReadFieldsReplyGroupFunction(p, stream)
	case publicpgn.NMEAReadFieldsReplyGroupFunction:
		return EncodeNMEAReadFieldsReplyGroupFunction(&p, stream)
	case *publicpgn.NMEAReadFieldsReplyGroupFunctionPartial:
		return EncodeNMEAReadFieldsReplyGroupFunctionPartial(p, stream)
	case publicpgn.NMEAReadFieldsReplyGroupFunctionPartial:
		return EncodeNMEAReadFieldsReplyGroupFunctionPartial(&p, stream)
	case *publicpgn.NMEAWriteFieldsGroupFunction:
		return EncodeNMEAWriteFieldsGroupFunction(p, stream)
	case publicpgn.NMEAWriteFieldsGroupFunction:
		return EncodeNMEAWriteFieldsGroupFunction(&p, stream)
	case *publicpgn.NMEAWriteFieldsGroupFunctionPartial:
		return EncodeNMEAWriteFieldsGroupFunctionPartial(p, stream)
	case publicpgn.NMEAWriteFieldsGroupFunctionPartial:
		return EncodeNMEAWriteFieldsGroupFunctionPartial(&p, stream)
	case *publicpgn.NMEAWriteFieldsReplyGroupFunction:
		return EncodeNMEAWriteFieldsReplyGroupFunction(p, stream)
	case publicpgn.NMEAWriteFieldsReplyGroupFunction:
		return EncodeNMEAWriteFieldsReplyGroupFunction(&p, stream)
	case *publicpgn.NMEAWriteFieldsReplyGroupFunctionPartial:
		return EncodeNMEAWriteFieldsReplyGroupFunctionPartial(p, stream)
	case publicpgn.NMEAWriteFieldsReplyGroupFunctionPartial:
		return EncodeNMEAWriteFieldsReplyGroupFunctionPartial(&p, stream)
	case *publicpgn.PGNListTransmitAndReceive:
		return EncodePGNListTransmitAndReceive(p, stream)
	case publicpgn.PGNListTransmitAndReceive:
		return EncodePGNListTransmitAndReceive(&p, stream)
	case *publicpgn.FusionMediaControl:
		return EncodeFusionMediaControl(p, stream)
	case publicpgn.FusionMediaControl:
		return EncodeFusionMediaControl(&p, stream)
	case *publicpgn.FusionSiriusControl:
		return EncodeFusionSiriusControl(p, stream)
	case publicpgn.FusionSiriusControl:
		return EncodeFusionSiriusControl(&p, stream)
	case *publicpgn.FusionRequestStatus:
		return EncodeFusionRequestStatus(p, stream)
	case publicpgn.FusionRequestStatus:
		return EncodeFusionRequestStatus(&p, stream)
	case *publicpgn.FusionSetSource:
		return EncodeFusionSetSource(p, stream)
	case publicpgn.FusionSetSource:
		return EncodeFusionSetSource(&p, stream)
	case *publicpgn.FusionSetMute:
		return EncodeFusionSetMute(p, stream)
	case publicpgn.FusionSetMute:
		return EncodeFusionSetMute(&p, stream)
	case *publicpgn.FusionSetZoneVolume:
		return EncodeFusionSetZoneVolume(p, stream)
	case publicpgn.FusionSetZoneVolume:
		return EncodeFusionSetZoneVolume(&p, stream)
	case *publicpgn.FusionSetAllVolumes:
		return EncodeFusionSetAllVolumes(p, stream)
	case publicpgn.FusionSetAllVolumes:
		return EncodeFusionSetAllVolumes(&p, stream)
	case *publicpgn.AirmarAttitudeOffset:
		return EncodeAirmarAttitudeOffset(p, stream)
	case publicpgn.AirmarAttitudeOffset:
		return EncodeAirmarAttitudeOffset(&p, stream)
	case *publicpgn.AirmarSimulateMode:
		return EncodeAirmarSimulateMode(p, stream)
	case publicpgn.AirmarSimulateMode:
		return EncodeAirmarSimulateMode(&p, stream)
	case *publicpgn.AirmarCalibrateDepth:
		return EncodeAirmarCalibrateDepth(p, stream)
	case publicpgn.AirmarCalibrateDepth:
		return EncodeAirmarCalibrateDepth(&p, stream)
	case *publicpgn.AirmarCalibrateSpeed:
		return EncodeAirmarCalibrateSpeed(p, stream)
	case publicpgn.AirmarCalibrateSpeed:
		return EncodeAirmarCalibrateSpeed(&p, stream)
	case *publicpgn.AirmarCalibrateTemperature:
		return EncodeAirmarCalibrateTemperature(p, stream)
	case publicpgn.AirmarCalibrateTemperature:
		return EncodeAirmarCalibrateTemperature(&p, stream)
	case *publicpgn.AirmarSpeedFilterNone:
		return EncodeAirmarSpeedFilterNone(p, stream)
	case publicpgn.AirmarSpeedFilterNone:
		return EncodeAirmarSpeedFilterNone(&p, stream)
	case *publicpgn.AirmarSpeedFilterIIR:
		return EncodeAirmarSpeedFilterIIR(p, stream)
	case publicpgn.AirmarSpeedFilterIIR:
		return EncodeAirmarSpeedFilterIIR(&p, stream)
	case *publicpgn.AirmarTemperatureFilterNone:
		return EncodeAirmarTemperatureFilterNone(p, stream)
	case publicpgn.AirmarTemperatureFilterNone:
		return EncodeAirmarTemperatureFilterNone(&p, stream)
	case *publicpgn.AirmarTemperatureFilterIIR:
		return EncodeAirmarTemperatureFilterIIR(p, stream)
	case publicpgn.AirmarTemperatureFilterIIR:
		return EncodeAirmarTemperatureFilterIIR(&p, stream)
	case *publicpgn.AirmarNMEA2000Options:
		return EncodeAirmarNMEA2000Options(p, stream)
	case publicpgn.AirmarNMEA2000Options:
		return EncodeAirmarNMEA2000Options(&p, stream)
	case *publicpgn.MaretronDeviationCalibrationResponse:
		return EncodeMaretronDeviationCalibrationResponse(p, stream)
	case publicpgn.MaretronDeviationCalibrationResponse:
		return EncodeMaretronDeviationCalibrationResponse(&p, stream)
	case *publicpgn.MaretronSlaveResponse:
		return EncodeMaretronSlaveResponse(p, stream)
	case publicpgn.MaretronSlaveResponse:
		return EncodeMaretronSlaveResponse(&p, stream)
	case *publicpgn.Alert:
		return EncodeAlert(p, stream)
	case publicpgn.Alert:
		return EncodeAlert(&p, stream)
	case *publicpgn.AlertResponse:
		return EncodeAlertResponse(p, stream)
	case publicpgn.AlertResponse:
		return EncodeAlertResponse(&p, stream)
	case *publicpgn.AlertText:
		return EncodeAlertText(p, stream)
	case publicpgn.AlertText:
		return EncodeAlertText(&p, stream)
	case *publicpgn.SystemTime:
		return EncodeSystemTime(p, stream)
	case publicpgn.SystemTime:
		return EncodeSystemTime(&p, stream)
	case *publicpgn.Heartbeat:
		return EncodeHeartbeat(p, stream)
	case publicpgn.Heartbeat:
		return EncodeHeartbeat(&p, stream)
	case *publicpgn.ProductInformation:
		return EncodeProductInformation(p, stream)
	case publicpgn.ProductInformation:
		return EncodeProductInformation(&p, stream)
	case *publicpgn.ConfigurationInformation:
		return EncodeConfigurationInformation(p, stream)
	case publicpgn.ConfigurationInformation:
		return EncodeConfigurationInformation(&p, stream)
	case *publicpgn.ManOverboardNotification:
		return EncodeManOverboardNotification(p, stream)
	case publicpgn.ManOverboardNotification:
		return EncodeManOverboardNotification(&p, stream)
	case *publicpgn.HeadingTrackControl:
		return EncodeHeadingTrackControl(p, stream)
	case publicpgn.HeadingTrackControl:
		return EncodeHeadingTrackControl(&p, stream)
	case *publicpgn.Rudder:
		return EncodeRudder(p, stream)
	case publicpgn.Rudder:
		return EncodeRudder(&p, stream)
	case *publicpgn.VesselHeading:
		return EncodeVesselHeading(p, stream)
	case publicpgn.VesselHeading:
		return EncodeVesselHeading(&p, stream)
	case *publicpgn.RateOfTurn:
		return EncodeRateOfTurn(p, stream)
	case publicpgn.RateOfTurn:
		return EncodeRateOfTurn(&p, stream)
	case *publicpgn.Attitude:
		return EncodeAttitude(p, stream)
	case publicpgn.Attitude:
		return EncodeAttitude(&p, stream)
	case *publicpgn.MagneticVariation:
		return EncodeMagneticVariation(p, stream)
	case publicpgn.MagneticVariation:
		return EncodeMagneticVariation(&p, stream)
	case *publicpgn.EngineParametersRapidUpdate:
		return EncodeEngineParametersRapidUpdate(p, stream)
	case publicpgn.EngineParametersRapidUpdate:
		return EncodeEngineParametersRapidUpdate(&p, stream)
	case *publicpgn.EngineParametersDynamic:
		return EncodeEngineParametersDynamic(p, stream)
	case publicpgn.EngineParametersDynamic:
		return EncodeEngineParametersDynamic(&p, stream)
	case *publicpgn.TransmissionParametersDynamic:
		return EncodeTransmissionParametersDynamic(p, stream)
	case publicpgn.TransmissionParametersDynamic:
		return EncodeTransmissionParametersDynamic(&p, stream)
	case *publicpgn.TripParametersVessel:
		return EncodeTripParametersVessel(p, stream)
	case publicpgn.TripParametersVessel:
		return EncodeTripParametersVessel(&p, stream)
	case *publicpgn.TripParametersEngine:
		return EncodeTripParametersEngine(p, stream)
	case publicpgn.TripParametersEngine:
		return EncodeTripParametersEngine(&p, stream)
	case *publicpgn.EngineParametersStatic:
		return EncodeEngineParametersStatic(p, stream)
	case publicpgn.EngineParametersStatic:
		return EncodeEngineParametersStatic(&p, stream)
	case *publicpgn.LoadControllerConnectionStateControl:
		return EncodeLoadControllerConnectionStateControl(p, stream)
	case publicpgn.LoadControllerConnectionStateControl:
		return EncodeLoadControllerConnectionStateControl(&p, stream)
	case *publicpgn.BinarySwitchBankStatus:
		return EncodeBinarySwitchBankStatus(p, stream)
	case publicpgn.BinarySwitchBankStatus:
		return EncodeBinarySwitchBankStatus(&p, stream)
	case *publicpgn.SwitchBankControl:
		return EncodeSwitchBankControl(p, stream)
	case publicpgn.SwitchBankControl:
		return EncodeSwitchBankControl(&p, stream)
	case *publicpgn.ACInputStatus:
		return EncodeACInputStatus(p, stream)
	case publicpgn.ACInputStatus:
		return EncodeACInputStatus(&p, stream)
	case *publicpgn.ACOutputStatus:
		return EncodeACOutputStatus(p, stream)
	case publicpgn.ACOutputStatus:
		return EncodeACOutputStatus(&p, stream)
	case *publicpgn.FluidLevel:
		return EncodeFluidLevel(p, stream)
	case publicpgn.FluidLevel:
		return EncodeFluidLevel(&p, stream)
	case *publicpgn.DCDetailedStatus:
		return EncodeDCDetailedStatus(p, stream)
	case publicpgn.DCDetailedStatus:
		return EncodeDCDetailedStatus(&p, stream)
	case *publicpgn.ChargerStatus:
		return EncodeChargerStatus(p, stream)
	case publicpgn.ChargerStatus:
		return EncodeChargerStatus(&p, stream)
	case *publicpgn.BatteryStatus:
		return EncodeBatteryStatus(p, stream)
	case publicpgn.BatteryStatus:
		return EncodeBatteryStatus(&p, stream)
	case *publicpgn.InverterStatus:
		return EncodeInverterStatus(p, stream)
	case publicpgn.InverterStatus:
		return EncodeInverterStatus(&p, stream)
	case *publicpgn.ChargerConfigurationStatus:
		return EncodeChargerConfigurationStatus(p, stream)
	case publicpgn.ChargerConfigurationStatus:
		return EncodeChargerConfigurationStatus(&p, stream)
	case *publicpgn.InverterConfigurationStatus:
		return EncodeInverterConfigurationStatus(p, stream)
	case publicpgn.InverterConfigurationStatus:
		return EncodeInverterConfigurationStatus(&p, stream)
	case *publicpgn.BatteryConfigurationStatus:
		return EncodeBatteryConfigurationStatus(p, stream)
	case publicpgn.BatteryConfigurationStatus:
		return EncodeBatteryConfigurationStatus(&p, stream)
	case *publicpgn.ACPowerCurrentPhaseA:
		return EncodeACPowerCurrentPhaseA(p, stream)
	case publicpgn.ACPowerCurrentPhaseA:
		return EncodeACPowerCurrentPhaseA(&p, stream)
	case *publicpgn.ACPowerCurrentPhaseB:
		return EncodeACPowerCurrentPhaseB(p, stream)
	case publicpgn.ACPowerCurrentPhaseB:
		return EncodeACPowerCurrentPhaseB(&p, stream)
	case *publicpgn.ACPowerCurrentPhaseC:
		return EncodeACPowerCurrentPhaseC(p, stream)
	case publicpgn.ACPowerCurrentPhaseC:
		return EncodeACPowerCurrentPhaseC(&p, stream)
	case *publicpgn.ACVoltageFrequencyPhaseA:
		return EncodeACVoltageFrequencyPhaseA(p, stream)
	case publicpgn.ACVoltageFrequencyPhaseA:
		return EncodeACVoltageFrequencyPhaseA(&p, stream)
	case *publicpgn.ACVoltageFrequencyPhaseB:
		return EncodeACVoltageFrequencyPhaseB(p, stream)
	case publicpgn.ACVoltageFrequencyPhaseB:
		return EncodeACVoltageFrequencyPhaseB(&p, stream)
	case *publicpgn.ACVoltageFrequencyPhaseC:
		return EncodeACVoltageFrequencyPhaseC(p, stream)
	case publicpgn.ACVoltageFrequencyPhaseC:
		return EncodeACVoltageFrequencyPhaseC(&p, stream)
	case *publicpgn.ConverterStatus:
		return EncodeConverterStatus(p, stream)
	case publicpgn.ConverterStatus:
		return EncodeConverterStatus(&p, stream)
	case *publicpgn.LeewayAngle:
		return EncodeLeewayAngle(p, stream)
	case publicpgn.LeewayAngle:
		return EncodeLeewayAngle(&p, stream)
	case *publicpgn.ThrusterControlStatus:
		return EncodeThrusterControlStatus(p, stream)
	case publicpgn.ThrusterControlStatus:
		return EncodeThrusterControlStatus(&p, stream)
	case *publicpgn.ThrusterInformation:
		return EncodeThrusterInformation(p, stream)
	case publicpgn.ThrusterInformation:
		return EncodeThrusterInformation(&p, stream)
	case *publicpgn.ThrusterMotorStatus:
		return EncodeThrusterMotorStatus(p, stream)
	case publicpgn.ThrusterMotorStatus:
		return EncodeThrusterMotorStatus(&p, stream)
	case *publicpgn.Speed:
		return EncodeSpeed(p, stream)
	case publicpgn.Speed:
		return EncodeSpeed(&p, stream)
	case *publicpgn.WaterDepth:
		return EncodeWaterDepth(p, stream)
	case publicpgn.WaterDepth:
		return EncodeWaterDepth(&p, stream)
	case *publicpgn.DistanceLog:
		return EncodeDistanceLog(p, stream)
	case publicpgn.DistanceLog:
		return EncodeDistanceLog(&p, stream)
	case *publicpgn.WindlassControlStatus:
		return EncodeWindlassControlStatus(p, stream)
	case publicpgn.WindlassControlStatus:
		return EncodeWindlassControlStatus(&p, stream)
	case *publicpgn.AnchorWindlassOperatingStatus:
		return EncodeAnchorWindlassOperatingStatus(p, stream)
	case publicpgn.AnchorWindlassOperatingStatus:
		return EncodeAnchorWindlassOperatingStatus(&p, stream)
	case *publicpgn.AnchorWindlassMonitoringStatus:
		return EncodeAnchorWindlassMonitoringStatus(p, stream)
	case publicpgn.AnchorWindlassMonitoringStatus:
		return EncodeAnchorWindlassMonitoringStatus(&p, stream)
	case *publicpgn.PositionRapidUpdate:
		return EncodePositionRapidUpdate(p, stream)
	case publicpgn.PositionRapidUpdate:
		return EncodePositionRapidUpdate(&p, stream)
	case *publicpgn.COGSOGRapidUpdate:
		return EncodeCOGSOGRapidUpdate(p, stream)
	case publicpgn.COGSOGRapidUpdate:
		return EncodeCOGSOGRapidUpdate(&p, stream)
	case *publicpgn.GNSSPositionData:
		return EncodeGNSSPositionData(p, stream)
	case publicpgn.GNSSPositionData:
		return EncodeGNSSPositionData(&p, stream)
	case *publicpgn.TimeDate:
		return EncodeTimeDate(p, stream)
	case publicpgn.TimeDate:
		return EncodeTimeDate(&p, stream)
	case *publicpgn.AISClassAPositionReport:
		return EncodeAISClassAPositionReport(p, stream)
	case publicpgn.AISClassAPositionReport:
		return EncodeAISClassAPositionReport(&p, stream)
	case *publicpgn.AISClassBPositionReport:
		return EncodeAISClassBPositionReport(p, stream)
	case publicpgn.AISClassBPositionReport:
		return EncodeAISClassBPositionReport(&p, stream)
	case *publicpgn.AISAidsToNavigationAtonReport:
		return EncodeAISAidsToNavigationAtonReport(p, stream)
	case publicpgn.AISAidsToNavigationAtonReport:
		return EncodeAISAidsToNavigationAtonReport(&p, stream)
	case *publicpgn.Datum:
		return EncodeDatum(p, stream)
	case publicpgn.Datum:
		return EncodeDatum(&p, stream)
	case *publicpgn.UserDatum:
		return EncodeUserDatum(p, stream)
	case publicpgn.UserDatum:
		return EncodeUserDatum(&p, stream)
	case *publicpgn.CrossTrackError:
		return EncodeCrossTrackError(p, stream)
	case publicpgn.CrossTrackError:
		return EncodeCrossTrackError(&p, stream)
	case *publicpgn.NavigationData:
		return EncodeNavigationData(p, stream)
	case publicpgn.NavigationData:
		return EncodeNavigationData(&p, stream)
	case *publicpgn.NavigationRouteWPInformation:
		return EncodeNavigationRouteWPInformation(p, stream)
	case publicpgn.NavigationRouteWPInformation:
		return EncodeNavigationRouteWPInformation(&p, stream)
	case *publicpgn.SetDriftRapidUpdate:
		return EncodeSetDriftRapidUpdate(p, stream)
	case publicpgn.SetDriftRapidUpdate:
		return EncodeSetDriftRapidUpdate(&p, stream)
	case *publicpgn.NavigationRouteTimeToFromMark:
		return EncodeNavigationRouteTimeToFromMark(p, stream)
	case publicpgn.NavigationRouteTimeToFromMark:
		return EncodeNavigationRouteTimeToFromMark(&p, stream)
	case *publicpgn.GNSSControlStatus:
		return EncodeGNSSControlStatus(p, stream)
	case publicpgn.GNSSControlStatus:
		return EncodeGNSSControlStatus(&p, stream)
	case *publicpgn.GNSSDOPs:
		return EncodeGNSSDOPs(p, stream)
	case publicpgn.GNSSDOPs:
		return EncodeGNSSDOPs(&p, stream)
	case *publicpgn.GNSSSatsInView:
		return EncodeGNSSSatsInView(p, stream)
	case publicpgn.GNSSSatsInView:
		return EncodeGNSSSatsInView(&p, stream)
	case *publicpgn.GNSSRAIMSettings:
		return EncodeGNSSRAIMSettings(p, stream)
	case publicpgn.GNSSRAIMSettings:
		return EncodeGNSSRAIMSettings(&p, stream)
	case *publicpgn.GNSSPseudorangeErrorStatistics:
		return EncodeGNSSPseudorangeErrorStatistics(p, stream)
	case publicpgn.GNSSPseudorangeErrorStatistics:
		return EncodeGNSSPseudorangeErrorStatistics(&p, stream)
	case *publicpgn.DGNSSCorrections:
		return EncodeDGNSSCorrections(p, stream)
	case publicpgn.DGNSSCorrections:
		return EncodeDGNSSCorrections(&p, stream)
	case *publicpgn.GNSSDifferentialCorrectionReceiverInterface:
		return EncodeGNSSDifferentialCorrectionReceiverInterface(p, stream)
	case publicpgn.GNSSDifferentialCorrectionReceiverInterface:
		return EncodeGNSSDifferentialCorrectionReceiverInterface(&p, stream)
	case *publicpgn.GNSSDifferentialCorrectionReceiverSignal:
		return EncodeGNSSDifferentialCorrectionReceiverSignal(p, stream)
	case publicpgn.GNSSDifferentialCorrectionReceiverSignal:
		return EncodeGNSSDifferentialCorrectionReceiverSignal(&p, stream)
	case *publicpgn.GLONASSAlmanacData:
		return EncodeGLONASSAlmanacData(p, stream)
	case publicpgn.GLONASSAlmanacData:
		return EncodeGLONASSAlmanacData(&p, stream)
	case *publicpgn.AISUTCAndDateReport:
		return EncodeAISUTCAndDateReport(p, stream)
	case publicpgn.AISUTCAndDateReport:
		return EncodeAISUTCAndDateReport(&p, stream)
	case *publicpgn.AISClassAStaticAndVoyageRelatedData:
		return EncodeAISClassAStaticAndVoyageRelatedData(p, stream)
	case publicpgn.AISClassAStaticAndVoyageRelatedData:
		return EncodeAISClassAStaticAndVoyageRelatedData(&p, stream)
	case *publicpgn.AISAddressedBinaryMessage:
		return EncodeAISAddressedBinaryMessage(p, stream)
	case publicpgn.AISAddressedBinaryMessage:
		return EncodeAISAddressedBinaryMessage(&p, stream)
	case *publicpgn.AISAcknowledge:
		return EncodeAISAcknowledge(p, stream)
	case publicpgn.AISAcknowledge:
		return EncodeAISAcknowledge(&p, stream)
	case *publicpgn.AISBinaryBroadcastMessage:
		return EncodeAISBinaryBroadcastMessage(p, stream)
	case publicpgn.AISBinaryBroadcastMessage:
		return EncodeAISBinaryBroadcastMessage(&p, stream)
	case *publicpgn.RadioFrequencyModePower:
		return EncodeRadioFrequencyModePower(p, stream)
	case publicpgn.RadioFrequencyModePower:
		return EncodeRadioFrequencyModePower(&p, stream)
	case *publicpgn.AISClassBStaticDataMsg24PartA:
		return EncodeAISClassBStaticDataMsg24PartA(p, stream)
	case publicpgn.AISClassBStaticDataMsg24PartA:
		return EncodeAISClassBStaticDataMsg24PartA(&p, stream)
	case *publicpgn.AISClassBStaticDataMsg24PartB:
		return EncodeAISClassBStaticDataMsg24PartB(p, stream)
	case publicpgn.AISClassBStaticDataMsg24PartB:
		return EncodeAISClassBStaticDataMsg24PartB(&p, stream)
	case *publicpgn.RouteAndWPServiceDatabaseList:
		return EncodeRouteAndWPServiceDatabaseList(p, stream)
	case publicpgn.RouteAndWPServiceDatabaseList:
		return EncodeRouteAndWPServiceDatabaseList(&p, stream)
	case *publicpgn.RouteAndWPServiceRouteList:
		return EncodeRouteAndWPServiceRouteList(p, stream)
	case publicpgn.RouteAndWPServiceRouteList:
		return EncodeRouteAndWPServiceRouteList(&p, stream)
	case *publicpgn.RouteAndWPServiceRouteWPListAttributes:
		return EncodeRouteAndWPServiceRouteWPListAttributes(p, stream)
	case publicpgn.RouteAndWPServiceRouteWPListAttributes:
		return EncodeRouteAndWPServiceRouteWPListAttributes(&p, stream)
	case *publicpgn.RouteAndWPServiceRouteWPNamePosition:
		return EncodeRouteAndWPServiceRouteWPNamePosition(p, stream)
	case publicpgn.RouteAndWPServiceRouteWPNamePosition:
		return EncodeRouteAndWPServiceRouteWPNamePosition(&p, stream)
	case *publicpgn.RouteAndWPServiceRouteWPName:
		return EncodeRouteAndWPServiceRouteWPName(p, stream)
	case publicpgn.RouteAndWPServiceRouteWPName:
		return EncodeRouteAndWPServiceRouteWPName(&p, stream)
	case *publicpgn.RouteAndWPServiceXTELimitNavigationMethod:
		return EncodeRouteAndWPServiceXTELimitNavigationMethod(p, stream)
	case publicpgn.RouteAndWPServiceXTELimitNavigationMethod:
		return EncodeRouteAndWPServiceXTELimitNavigationMethod(&p, stream)
	case *publicpgn.RouteAndWPServiceWPComment:
		return EncodeRouteAndWPServiceWPComment(p, stream)
	case publicpgn.RouteAndWPServiceWPComment:
		return EncodeRouteAndWPServiceWPComment(&p, stream)
	case *publicpgn.RouteAndWPServiceRouteComment:
		return EncodeRouteAndWPServiceRouteComment(p, stream)
	case publicpgn.RouteAndWPServiceRouteComment:
		return EncodeRouteAndWPServiceRouteComment(&p, stream)
	case *publicpgn.RouteAndWPServiceDatabaseComment:
		return EncodeRouteAndWPServiceDatabaseComment(p, stream)
	case publicpgn.RouteAndWPServiceDatabaseComment:
		return EncodeRouteAndWPServiceDatabaseComment(&p, stream)
	case *publicpgn.RouteAndWPServiceRadiusOfTurn:
		return EncodeRouteAndWPServiceRadiusOfTurn(p, stream)
	case publicpgn.RouteAndWPServiceRadiusOfTurn:
		return EncodeRouteAndWPServiceRadiusOfTurn(&p, stream)
	case *publicpgn.RouteAndWPServiceWPListWPNamePosition:
		return EncodeRouteAndWPServiceWPListWPNamePosition(p, stream)
	case publicpgn.RouteAndWPServiceWPListWPNamePosition:
		return EncodeRouteAndWPServiceWPListWPNamePosition(&p, stream)
	case *publicpgn.WindData:
		return EncodeWindData(p, stream)
	case publicpgn.WindData:
		return EncodeWindData(&p, stream)
	case *publicpgn.EnvironmentalParametersObsolete:
		return EncodeEnvironmentalParametersObsolete(p, stream)
	case publicpgn.EnvironmentalParametersObsolete:
		return EncodeEnvironmentalParametersObsolete(&p, stream)
	case *publicpgn.EnvironmentalParameters:
		return EncodeEnvironmentalParameters(p, stream)
	case publicpgn.EnvironmentalParameters:
		return EncodeEnvironmentalParameters(&p, stream)
	case *publicpgn.Temperature:
		return EncodeTemperature(p, stream)
	case publicpgn.Temperature:
		return EncodeTemperature(&p, stream)
	case *publicpgn.Humidity:
		return EncodeHumidity(p, stream)
	case publicpgn.Humidity:
		return EncodeHumidity(&p, stream)
	case *publicpgn.ActualPressure:
		return EncodeActualPressure(p, stream)
	case publicpgn.ActualPressure:
		return EncodeActualPressure(&p, stream)
	case *publicpgn.SetPressure:
		return EncodeSetPressure(p, stream)
	case publicpgn.SetPressure:
		return EncodeSetPressure(&p, stream)
	case *publicpgn.TemperatureExtendedRange:
		return EncodeTemperatureExtendedRange(p, stream)
	case publicpgn.TemperatureExtendedRange:
		return EncodeTemperatureExtendedRange(&p, stream)
	case *publicpgn.TideStationData:
		return EncodeTideStationData(p, stream)
	case publicpgn.TideStationData:
		return EncodeTideStationData(&p, stream)
	case *publicpgn.WatermakerInputSettingAndStatus:
		return EncodeWatermakerInputSettingAndStatus(p, stream)
	case publicpgn.WatermakerInputSettingAndStatus:
		return EncodeWatermakerInputSettingAndStatus(&p, stream)
	case *publicpgn.SmallCraftStatus:
		return EncodeSmallCraftStatus(p, stream)
	case publicpgn.SmallCraftStatus:
		return EncodeSmallCraftStatus(&p, stream)
	case *publicpgn.DirectionData:
		return EncodeDirectionData(p, stream)
	case publicpgn.DirectionData:
		return EncodeDirectionData(&p, stream)
	case *publicpgn.VesselSpeedComponents:
		return EncodeVesselSpeedComponents(p, stream)
	case publicpgn.VesselSpeedComponents:
		return EncodeVesselSpeedComponents(&p, stream)
	case *publicpgn.SonichubVolume:
		return EncodeSonichubVolume(p, stream)
	case publicpgn.SonichubVolume:
		return EncodeSonichubVolume(&p, stream)
	case *publicpgn.BEPMarineCzoneZcfBusDistribution:
		return EncodeBEPMarineCzoneZcfBusDistribution(p, stream)
	case publicpgn.BEPMarineCzoneZcfBusDistribution:
		return EncodeBEPMarineCzoneZcfBusDistribution(&p, stream)
	case *publicpgn.MaretronLabel:
		return EncodeMaretronLabel(p, stream)
	case publicpgn.MaretronLabel:
		return EncodeMaretronLabel(&p, stream)
	case *publicpgn.FusionVersions:
		return EncodeFusionVersions(p, stream)
	case publicpgn.FusionVersions:
		return EncodeFusionVersions(&p, stream)
	case *publicpgn.FusionSource:
		return EncodeFusionSource(p, stream)
	case publicpgn.FusionSource:
		return EncodeFusionSource(&p, stream)
	case *publicpgn.FusionSourceCount:
		return EncodeFusionSourceCount(p, stream)
	case publicpgn.FusionSourceCount:
		return EncodeFusionSourceCount(&p, stream)
	case *publicpgn.FusionMedia:
		return EncodeFusionMedia(p, stream)
	case publicpgn.FusionMedia:
		return EncodeFusionMedia(&p, stream)
	case *publicpgn.FusionTrackName:
		return EncodeFusionTrackName(p, stream)
	case publicpgn.FusionTrackName:
		return EncodeFusionTrackName(&p, stream)
	case *publicpgn.FusionArtistName:
		return EncodeFusionArtistName(p, stream)
	case publicpgn.FusionArtistName:
		return EncodeFusionArtistName(&p, stream)
	case *publicpgn.FusionAlbumName:
		return EncodeFusionAlbumName(p, stream)
	case publicpgn.FusionAlbumName:
		return EncodeFusionAlbumName(&p, stream)
	case *publicpgn.FusionDeviceName:
		return EncodeFusionDeviceName(p, stream)
	case publicpgn.FusionDeviceName:
		return EncodeFusionDeviceName(&p, stream)
	case *publicpgn.FusionZoneName:
		return EncodeFusionZoneName(p, stream)
	case publicpgn.FusionZoneName:
		return EncodeFusionZoneName(&p, stream)
	case *publicpgn.FusionSpeedVolumeCurrentSpeed:
		return EncodeFusionSpeedVolumeCurrentSpeed(p, stream)
	case publicpgn.FusionSpeedVolumeCurrentSpeed:
		return EncodeFusionSpeedVolumeCurrentSpeed(&p, stream)
	case *publicpgn.FusionIgnitionSwitchState:
		return EncodeFusionIgnitionSwitchState(p, stream)
	case publicpgn.FusionIgnitionSwitchState:
		return EncodeFusionIgnitionSwitchState(&p, stream)
	case *publicpgn.FusionMenuLockId:
		return EncodeFusionMenuLockId(p, stream)
	case publicpgn.FusionMenuLockId:
		return EncodeFusionMenuLockId(&p, stream)
	case *publicpgn.FusionRDSData:
		return EncodeFusionRDSData(p, stream)
	case publicpgn.FusionRDSData:
		return EncodeFusionRDSData(&p, stream)
	case *publicpgn.FusionMultiroom:
		return EncodeFusionMultiroom(p, stream)
	case publicpgn.FusionMultiroom:
		return EncodeFusionMultiroom(&p, stream)
	case *publicpgn.FusionMultiroomStatus:
		return EncodeFusionMultiroomStatus(p, stream)
	case publicpgn.FusionMultiroomStatus:
		return EncodeFusionMultiroomStatus(&p, stream)
	case *publicpgn.FusionProcessingBypass:
		return EncodeFusionProcessingBypass(p, stream)
	case publicpgn.FusionProcessingBypass:
		return EncodeFusionProcessingBypass(&p, stream)
	case *publicpgn.FusionMono:
		return EncodeFusionMono(p, stream)
	case publicpgn.FusionMono:
		return EncodeFusionMono(&p, stream)
	case *publicpgn.FusionTrackPosition:
		return EncodeFusionTrackPosition(p, stream)
	case publicpgn.FusionTrackPosition:
		return EncodeFusionTrackPosition(&p, stream)
	case *publicpgn.FusionTuner:
		return EncodeFusionTuner(p, stream)
	case publicpgn.FusionTuner:
		return EncodeFusionTuner(&p, stream)
	case *publicpgn.FusionMARINETUNER:
		return EncodeFusionMARINETUNER(p, stream)
	case publicpgn.FusionMARINETUNER:
		return EncodeFusionMARINETUNER(&p, stream)
	case *publicpgn.FusionMarineSquelch:
		return EncodeFusionMarineSquelch(p, stream)
	case publicpgn.FusionMarineSquelch:
		return EncodeFusionMarineSquelch(&p, stream)
	case *publicpgn.FusionMarineScanMode:
		return EncodeFusionMarineScanMode(p, stream)
	case publicpgn.FusionMarineScanMode:
		return EncodeFusionMarineScanMode(&p, stream)
	case *publicpgn.FusionMenuItem:
		return EncodeFusionMenuItem(p, stream)
	case publicpgn.FusionMenuItem:
		return EncodeFusionMenuItem(&p, stream)
	case *publicpgn.FusionAuxGain:
		return EncodeFusionAuxGain(p, stream)
	case publicpgn.FusionAuxGain:
		return EncodeFusionAuxGain(&p, stream)
	case *publicpgn.FusionUSBRepeatStatus:
		return EncodeFusionUSBRepeatStatus(p, stream)
	case publicpgn.FusionUSBRepeatStatus:
		return EncodeFusionUSBRepeatStatus(&p, stream)
	case *publicpgn.FusionSetting:
		return EncodeFusionSetting(p, stream)
	case publicpgn.FusionSetting:
		return EncodeFusionSetting(&p, stream)
	case *publicpgn.FusionSettings:
		return EncodeFusionSettings(p, stream)
	case publicpgn.FusionSettings:
		return EncodeFusionSettings(&p, stream)
	case *publicpgn.FusionMute:
		return EncodeFusionMute(p, stream)
	case publicpgn.FusionMute:
		return EncodeFusionMute(&p, stream)
	case *publicpgn.FusionBalance:
		return EncodeFusionBalance(p, stream)
	case publicpgn.FusionBalance:
		return EncodeFusionBalance(&p, stream)
	case *publicpgn.FusionLowPassFilter:
		return EncodeFusionLowPassFilter(p, stream)
	case publicpgn.FusionLowPassFilter:
		return EncodeFusionLowPassFilter(&p, stream)
	case *publicpgn.FusionSublevels:
		return EncodeFusionSublevels(p, stream)
	case publicpgn.FusionSublevels:
		return EncodeFusionSublevels(&p, stream)
	case *publicpgn.FusionEQ:
		return EncodeFusionEQ(p, stream)
	case publicpgn.FusionEQ:
		return EncodeFusionEQ(&p, stream)
	case *publicpgn.FusionVolumeLimits:
		return EncodeFusionVolumeLimits(p, stream)
	case publicpgn.FusionVolumeLimits:
		return EncodeFusionVolumeLimits(&p, stream)
	case *publicpgn.FusionVolumes:
		return EncodeFusionVolumes(p, stream)
	case publicpgn.FusionVolumes:
		return EncodeFusionVolumes(&p, stream)
	case *publicpgn.FusionCapabilities:
		return EncodeFusionCapabilities(p, stream)
	case publicpgn.FusionCapabilities:
		return EncodeFusionCapabilities(&p, stream)
	case *publicpgn.FusionLineLevelControl:
		return EncodeFusionLineLevelControl(p, stream)
	case publicpgn.FusionLineLevelControl:
		return EncodeFusionLineLevelControl(&p, stream)
	case *publicpgn.FusionPowerState:
		return EncodeFusionPowerState(p, stream)
	case publicpgn.FusionPowerState:
		return EncodeFusionPowerState(&p, stream)
	case *publicpgn.FusionSiriusxm:
		return EncodeFusionSiriusxm(p, stream)
	case publicpgn.FusionSiriusxm:
		return EncodeFusionSiriusxm(&p, stream)
	case *publicpgn.FusionSiriusxmChannel:
		return EncodeFusionSiriusxmChannel(p, stream)
	case publicpgn.FusionSiriusxmChannel:
		return EncodeFusionSiriusxmChannel(&p, stream)
	case *publicpgn.FusionSiriusxmTitle:
		return EncodeFusionSiriusxmTitle(p, stream)
	case publicpgn.FusionSiriusxmTitle:
		return EncodeFusionSiriusxmTitle(&p, stream)
	case *publicpgn.FusionSiriusxmArtist:
		return EncodeFusionSiriusxmArtist(p, stream)
	case publicpgn.FusionSiriusxmArtist:
		return EncodeFusionSiriusxmArtist(&p, stream)
	case *publicpgn.FusionSiriusxmContentInfo:
		return EncodeFusionSiriusxmContentInfo(p, stream)
	case publicpgn.FusionSiriusxmContentInfo:
		return EncodeFusionSiriusxmContentInfo(&p, stream)
	case *publicpgn.FusionSiriusxmCategory:
		return EncodeFusionSiriusxmCategory(p, stream)
	case publicpgn.FusionSiriusxmCategory:
		return EncodeFusionSiriusxmCategory(&p, stream)
	case *publicpgn.FusionSiriusxmSignal:
		return EncodeFusionSiriusxmSignal(p, stream)
	case publicpgn.FusionSiriusxmSignal:
		return EncodeFusionSiriusxmSignal(&p, stream)
	case *publicpgn.FusionSiriusxmPresets:
		return EncodeFusionSiriusxmPresets(p, stream)
	case publicpgn.FusionSiriusxmPresets:
		return EncodeFusionSiriusxmPresets(&p, stream)
	case *publicpgn.MaretronProprietaryTemperatureHighRange:
		return EncodeMaretronProprietaryTemperatureHighRange(p, stream)
	case publicpgn.MaretronProprietaryTemperatureHighRange:
		return EncodeMaretronProprietaryTemperatureHighRange(&p, stream)
	case *publicpgn.BGKeyValueData:
		return EncodeBGKeyValueData(p, stream)
	case publicpgn.BGKeyValueData:
		return EncodeBGKeyValueData(&p, stream)
	case *publicpgn.MercuryEngineKeyValueData:
		return EncodeMercuryEngineKeyValueData(p, stream)
	case publicpgn.MercuryEngineKeyValueData:
		return EncodeMercuryEngineKeyValueData(&p, stream)
	case *publicpgn.MaretronDataInstanceChannelCorrelation:
		return EncodeMaretronDataInstanceChannelCorrelation(p, stream)
	case publicpgn.MaretronDataInstanceChannelCorrelation:
		return EncodeMaretronDataInstanceChannelCorrelation(&p, stream)
	case *publicpgn.MaretronSwitchIndicatorStatus:
		return EncodeMaretronSwitchIndicatorStatus(p, stream)
	case publicpgn.MaretronSwitchIndicatorStatus:
		return EncodeMaretronSwitchIndicatorStatus(&p, stream)
	case *publicpgn.MaretronSwitchStatusCounter:
		return EncodeMaretronSwitchStatusCounter(p, stream)
	case publicpgn.MaretronSwitchStatusCounter:
		return EncodeMaretronSwitchStatusCounter(&p, stream)
	case *publicpgn.MaretronSwitchStatusTimer:
		return EncodeMaretronSwitchStatusTimer(p, stream)
	case publicpgn.MaretronSwitchStatusTimer:
		return EncodeMaretronSwitchStatusTimer(&p, stream)
	case *publicpgn.FurunoMultiSatsInViewExtended:
		return EncodeFurunoMultiSatsInViewExtended(p, stream)
	case publicpgn.FurunoMultiSatsInViewExtended:
		return EncodeFurunoMultiSatsInViewExtended(&p, stream)
	default:
		return nil, fmt.Errorf("trying to encode a struct that isn't a PGN: %T", s)
	}
}
