// Code generated by "cmd/pgngen"; DO NOT EDIT.
package pgn

import (
	"fmt"

	publicpgn "github.com/boatkit-io/n2k/pkg/pgn"
)

// EncodeStruct encodes a public PGN struct to NMEA 2000 wire format.
func EncodeStruct(s any, stream *DataStream) (*publicpgn.MessageInfo, error) {
	switch p := s.(type) {
	case *publicpgn.IsoAcknowledgement:
		return EncodeIsoAcknowledgement(p, stream)
	case publicpgn.IsoAcknowledgement:
		return EncodeIsoAcknowledgement(&p, stream)
	case *publicpgn.IsoRequest:
		return EncodeIsoRequest(p, stream)
	case publicpgn.IsoRequest:
		return EncodeIsoRequest(&p, stream)
	case *publicpgn.IsoTransportProtocolDataTransfer:
		return EncodeIsoTransportProtocolDataTransfer(p, stream)
	case publicpgn.IsoTransportProtocolDataTransfer:
		return EncodeIsoTransportProtocolDataTransfer(&p, stream)
	case *publicpgn.IsoTransportProtocolConnectionManagementRequestToSend:
		return EncodeIsoTransportProtocolConnectionManagementRequestToSend(p, stream)
	case publicpgn.IsoTransportProtocolConnectionManagementRequestToSend:
		return EncodeIsoTransportProtocolConnectionManagementRequestToSend(&p, stream)
	case *publicpgn.IsoTransportProtocolConnectionManagementClearToSend:
		return EncodeIsoTransportProtocolConnectionManagementClearToSend(p, stream)
	case publicpgn.IsoTransportProtocolConnectionManagementClearToSend:
		return EncodeIsoTransportProtocolConnectionManagementClearToSend(&p, stream)
	case *publicpgn.IsoTransportProtocolConnectionManagementEndOfMessage:
		return EncodeIsoTransportProtocolConnectionManagementEndOfMessage(p, stream)
	case publicpgn.IsoTransportProtocolConnectionManagementEndOfMessage:
		return EncodeIsoTransportProtocolConnectionManagementEndOfMessage(&p, stream)
	case *publicpgn.IsoTransportProtocolConnectionManagementBroadcastAnnounce:
		return EncodeIsoTransportProtocolConnectionManagementBroadcastAnnounce(p, stream)
	case publicpgn.IsoTransportProtocolConnectionManagementBroadcastAnnounce:
		return EncodeIsoTransportProtocolConnectionManagementBroadcastAnnounce(&p, stream)
	case *publicpgn.IsoTransportProtocolConnectionManagementAbort:
		return EncodeIsoTransportProtocolConnectionManagementAbort(p, stream)
	case publicpgn.IsoTransportProtocolConnectionManagementAbort:
		return EncodeIsoTransportProtocolConnectionManagementAbort(&p, stream)
	case *publicpgn.IsoAddressClaim:
		return EncodeIsoAddressClaim(p, stream)
	case publicpgn.IsoAddressClaim:
		return EncodeIsoAddressClaim(&p, stream)
	case *publicpgn.CarlingBreakerCommand:
		return EncodeCarlingBreakerCommand(p, stream)
	case publicpgn.CarlingBreakerCommand:
		return EncodeCarlingBreakerCommand(&p, stream)
	case *publicpgn.Bus1PhaseCBasicAcQuantities:
		return EncodeBus1PhaseCBasicAcQuantities(p, stream)
	case publicpgn.Bus1PhaseCBasicAcQuantities:
		return EncodeBus1PhaseCBasicAcQuantities(&p, stream)
	case *publicpgn.Bus1PhaseBBasicAcQuantities:
		return EncodeBus1PhaseBBasicAcQuantities(p, stream)
	case publicpgn.Bus1PhaseBBasicAcQuantities:
		return EncodeBus1PhaseBBasicAcQuantities(&p, stream)
	case *publicpgn.Bus1PhaseABasicAcQuantities:
		return EncodeBus1PhaseABasicAcQuantities(p, stream)
	case publicpgn.Bus1PhaseABasicAcQuantities:
		return EncodeBus1PhaseABasicAcQuantities(&p, stream)
	case *publicpgn.UtilityPhaseCAcReactivePower:
		return EncodeUtilityPhaseCAcReactivePower(p, stream)
	case publicpgn.UtilityPhaseCAcReactivePower:
		return EncodeUtilityPhaseCAcReactivePower(&p, stream)
	case *publicpgn.UtilityPhaseCAcPower:
		return EncodeUtilityPhaseCAcPower(p, stream)
	case publicpgn.UtilityPhaseCAcPower:
		return EncodeUtilityPhaseCAcPower(&p, stream)
	case *publicpgn.UtilityPhaseCBasicAcQuantities:
		return EncodeUtilityPhaseCBasicAcQuantities(p, stream)
	case publicpgn.UtilityPhaseCBasicAcQuantities:
		return EncodeUtilityPhaseCBasicAcQuantities(&p, stream)
	case *publicpgn.UtilityPhaseBAcReactivePower:
		return EncodeUtilityPhaseBAcReactivePower(p, stream)
	case publicpgn.UtilityPhaseBAcReactivePower:
		return EncodeUtilityPhaseBAcReactivePower(&p, stream)
	case *publicpgn.UtilityPhaseBAcPower:
		return EncodeUtilityPhaseBAcPower(p, stream)
	case publicpgn.UtilityPhaseBAcPower:
		return EncodeUtilityPhaseBAcPower(&p, stream)
	case *publicpgn.UtilityPhaseBBasicAcQuantities:
		return EncodeUtilityPhaseBBasicAcQuantities(p, stream)
	case publicpgn.UtilityPhaseBBasicAcQuantities:
		return EncodeUtilityPhaseBBasicAcQuantities(&p, stream)
	case *publicpgn.UtilityPhaseAAcReactivePower:
		return EncodeUtilityPhaseAAcReactivePower(p, stream)
	case publicpgn.UtilityPhaseAAcReactivePower:
		return EncodeUtilityPhaseAAcReactivePower(&p, stream)
	case *publicpgn.UtilityPhaseAAcPower:
		return EncodeUtilityPhaseAAcPower(p, stream)
	case publicpgn.UtilityPhaseAAcPower:
		return EncodeUtilityPhaseAAcPower(&p, stream)
	case *publicpgn.UtilityPhaseABasicAcQuantities:
		return EncodeUtilityPhaseABasicAcQuantities(p, stream)
	case publicpgn.UtilityPhaseABasicAcQuantities:
		return EncodeUtilityPhaseABasicAcQuantities(&p, stream)
	case *publicpgn.UtilityTotalAcReactivePower:
		return EncodeUtilityTotalAcReactivePower(p, stream)
	case publicpgn.UtilityTotalAcReactivePower:
		return EncodeUtilityTotalAcReactivePower(&p, stream)
	case *publicpgn.UtilityTotalAcPower:
		return EncodeUtilityTotalAcPower(p, stream)
	case publicpgn.UtilityTotalAcPower:
		return EncodeUtilityTotalAcPower(&p, stream)
	case *publicpgn.UtilityAverageBasicAcQuantities:
		return EncodeUtilityAverageBasicAcQuantities(p, stream)
	case publicpgn.UtilityAverageBasicAcQuantities:
		return EncodeUtilityAverageBasicAcQuantities(&p, stream)
	case *publicpgn.GeneratorPhaseCAcReactivePower:
		return EncodeGeneratorPhaseCAcReactivePower(p, stream)
	case publicpgn.GeneratorPhaseCAcReactivePower:
		return EncodeGeneratorPhaseCAcReactivePower(&p, stream)
	case *publicpgn.GeneratorPhaseCAcPower:
		return EncodeGeneratorPhaseCAcPower(p, stream)
	case publicpgn.GeneratorPhaseCAcPower:
		return EncodeGeneratorPhaseCAcPower(&p, stream)
	case *publicpgn.GeneratorPhaseCBasicAcQuantities:
		return EncodeGeneratorPhaseCBasicAcQuantities(p, stream)
	case publicpgn.GeneratorPhaseCBasicAcQuantities:
		return EncodeGeneratorPhaseCBasicAcQuantities(&p, stream)
	case *publicpgn.GeneratorPhaseBAcReactivePower:
		return EncodeGeneratorPhaseBAcReactivePower(p, stream)
	case publicpgn.GeneratorPhaseBAcReactivePower:
		return EncodeGeneratorPhaseBAcReactivePower(&p, stream)
	case *publicpgn.GeneratorPhaseBAcPower:
		return EncodeGeneratorPhaseBAcPower(p, stream)
	case publicpgn.GeneratorPhaseBAcPower:
		return EncodeGeneratorPhaseBAcPower(&p, stream)
	case *publicpgn.GeneratorPhaseBBasicAcQuantities:
		return EncodeGeneratorPhaseBBasicAcQuantities(p, stream)
	case publicpgn.GeneratorPhaseBBasicAcQuantities:
		return EncodeGeneratorPhaseBBasicAcQuantities(&p, stream)
	case *publicpgn.GeneratorPhaseAAcReactivePower:
		return EncodeGeneratorPhaseAAcReactivePower(p, stream)
	case publicpgn.GeneratorPhaseAAcReactivePower:
		return EncodeGeneratorPhaseAAcReactivePower(&p, stream)
	case *publicpgn.GeneratorPhaseAAcPower:
		return EncodeGeneratorPhaseAAcPower(p, stream)
	case publicpgn.GeneratorPhaseAAcPower:
		return EncodeGeneratorPhaseAAcPower(&p, stream)
	case *publicpgn.GeneratorPhaseABasicAcQuantities:
		return EncodeGeneratorPhaseABasicAcQuantities(p, stream)
	case publicpgn.GeneratorPhaseABasicAcQuantities:
		return EncodeGeneratorPhaseABasicAcQuantities(&p, stream)
	case *publicpgn.GeneratorTotalAcReactivePower:
		return EncodeGeneratorTotalAcReactivePower(p, stream)
	case publicpgn.GeneratorTotalAcReactivePower:
		return EncodeGeneratorTotalAcReactivePower(&p, stream)
	case *publicpgn.GeneratorTotalAcPower:
		return EncodeGeneratorTotalAcPower(p, stream)
	case publicpgn.GeneratorTotalAcPower:
		return EncodeGeneratorTotalAcPower(&p, stream)
	case *publicpgn.GeneratorAverageBasicAcQuantities:
		return EncodeGeneratorAverageBasicAcQuantities(p, stream)
	case publicpgn.GeneratorAverageBasicAcQuantities:
		return EncodeGeneratorAverageBasicAcQuantities(&p, stream)
	case *publicpgn.IsoCommandedAddress:
		return EncodeIsoCommandedAddress(p, stream)
	case publicpgn.IsoCommandedAddress:
		return EncodeIsoCommandedAddress(&p, stream)
	case *publicpgn.MaretronNumberOfChannels:
		return EncodeMaretronNumberOfChannels(p, stream)
	case publicpgn.MaretronNumberOfChannels:
		return EncodeMaretronNumberOfChannels(&p, stream)
	case *publicpgn.MaretronProprietaryDcBreakerCurrent:
		return EncodeMaretronProprietaryDcBreakerCurrent(p, stream)
	case publicpgn.MaretronProprietaryDcBreakerCurrent:
		return EncodeMaretronProprietaryDcBreakerCurrent(&p, stream)
	case *publicpgn.AirmarBootStateAcknowledgment:
		return EncodeAirmarBootStateAcknowledgment(p, stream)
	case publicpgn.AirmarBootStateAcknowledgment:
		return EncodeAirmarBootStateAcknowledgment(&p, stream)
	case *publicpgn.LowranceTemperature:
		return EncodeLowranceTemperature(p, stream)
	case publicpgn.LowranceTemperature:
		return EncodeLowranceTemperature(&p, stream)
	case *publicpgn.AirmarBootStateRequest:
		return EncodeAirmarBootStateRequest(p, stream)
	case publicpgn.AirmarBootStateRequest:
		return EncodeAirmarBootStateRequest(&p, stream)
	case *publicpgn.AirmarAccessLevel:
		return EncodeAirmarAccessLevel(p, stream)
	case publicpgn.AirmarAccessLevel:
		return EncodeAirmarAccessLevel(&p, stream)
	case *publicpgn.SimnetDeviceStatus:
		return EncodeSimnetDeviceStatus(p, stream)
	case publicpgn.SimnetDeviceStatus:
		return EncodeSimnetDeviceStatus(&p, stream)
	case *publicpgn.SimnetDeviceStatusRequest:
		return EncodeSimnetDeviceStatusRequest(p, stream)
	case publicpgn.SimnetDeviceStatusRequest:
		return EncodeSimnetDeviceStatusRequest(&p, stream)
	case *publicpgn.SimnetPilotMode:
		return EncodeSimnetPilotMode(p, stream)
	case publicpgn.SimnetPilotMode:
		return EncodeSimnetPilotMode(&p, stream)
	case *publicpgn.SimnetDeviceModeRequest:
		return EncodeSimnetDeviceModeRequest(p, stream)
	case publicpgn.SimnetDeviceModeRequest:
		return EncodeSimnetDeviceModeRequest(&p, stream)
	case *publicpgn.SeatalkPilotLockedHeading:
		return EncodeSeatalkPilotLockedHeading(p, stream)
	case publicpgn.SeatalkPilotLockedHeading:
		return EncodeSeatalkPilotLockedHeading(&p, stream)
	case *publicpgn.SeatalkSilenceAlarm:
		return EncodeSeatalkSilenceAlarm(p, stream)
	case publicpgn.SeatalkSilenceAlarm:
		return EncodeSeatalkSilenceAlarm(&p, stream)
	case *publicpgn.AirmarSpeedPulseCount:
		return EncodeAirmarSpeedPulseCount(p, stream)
	case publicpgn.AirmarSpeedPulseCount:
		return EncodeAirmarSpeedPulseCount(&p, stream)
	case *publicpgn.NmeaRequestGroupFunction:
		return EncodeNmeaRequestGroupFunction(p, stream)
	case publicpgn.NmeaRequestGroupFunction:
		return EncodeNmeaRequestGroupFunction(&p, stream)
	case *publicpgn.NmeaRequestGroupFunctionPartial:
		return EncodeNmeaRequestGroupFunctionPartial(p, stream)
	case publicpgn.NmeaRequestGroupFunctionPartial:
		return EncodeNmeaRequestGroupFunctionPartial(&p, stream)
	case *publicpgn.NmeaCommandGroupFunction:
		return EncodeNmeaCommandGroupFunction(p, stream)
	case publicpgn.NmeaCommandGroupFunction:
		return EncodeNmeaCommandGroupFunction(&p, stream)
	case *publicpgn.NmeaCommandGroupFunctionPartial:
		return EncodeNmeaCommandGroupFunctionPartial(p, stream)
	case publicpgn.NmeaCommandGroupFunctionPartial:
		return EncodeNmeaCommandGroupFunctionPartial(&p, stream)
	case *publicpgn.NmeaAcknowledgeGroupFunction:
		return EncodeNmeaAcknowledgeGroupFunction(p, stream)
	case publicpgn.NmeaAcknowledgeGroupFunction:
		return EncodeNmeaAcknowledgeGroupFunction(&p, stream)
	case *publicpgn.NmeaAcknowledgeGroupFunctionPartial:
		return EncodeNmeaAcknowledgeGroupFunctionPartial(p, stream)
	case publicpgn.NmeaAcknowledgeGroupFunctionPartial:
		return EncodeNmeaAcknowledgeGroupFunctionPartial(&p, stream)
	case *publicpgn.NmeaReadFieldsReplyGroupFunction:
		return EncodeNmeaReadFieldsReplyGroupFunction(p, stream)
	case publicpgn.NmeaReadFieldsReplyGroupFunction:
		return EncodeNmeaReadFieldsReplyGroupFunction(&p, stream)
	case *publicpgn.NmeaReadFieldsReplyGroupFunctionPartial:
		return EncodeNmeaReadFieldsReplyGroupFunctionPartial(p, stream)
	case publicpgn.NmeaReadFieldsReplyGroupFunctionPartial:
		return EncodeNmeaReadFieldsReplyGroupFunctionPartial(&p, stream)
	case *publicpgn.NmeaWriteFieldsGroupFunction:
		return EncodeNmeaWriteFieldsGroupFunction(p, stream)
	case publicpgn.NmeaWriteFieldsGroupFunction:
		return EncodeNmeaWriteFieldsGroupFunction(&p, stream)
	case *publicpgn.NmeaWriteFieldsGroupFunctionPartial:
		return EncodeNmeaWriteFieldsGroupFunctionPartial(p, stream)
	case publicpgn.NmeaWriteFieldsGroupFunctionPartial:
		return EncodeNmeaWriteFieldsGroupFunctionPartial(&p, stream)
	case *publicpgn.NmeaWriteFieldsReplyGroupFunction:
		return EncodeNmeaWriteFieldsReplyGroupFunction(p, stream)
	case publicpgn.NmeaWriteFieldsReplyGroupFunction:
		return EncodeNmeaWriteFieldsReplyGroupFunction(&p, stream)
	case *publicpgn.NmeaWriteFieldsReplyGroupFunctionPartial:
		return EncodeNmeaWriteFieldsReplyGroupFunctionPartial(p, stream)
	case publicpgn.NmeaWriteFieldsReplyGroupFunctionPartial:
		return EncodeNmeaWriteFieldsReplyGroupFunctionPartial(&p, stream)
	case *publicpgn.PgnListTransmitAndReceive:
		return EncodePgnListTransmitAndReceive(p, stream)
	case publicpgn.PgnListTransmitAndReceive:
		return EncodePgnListTransmitAndReceive(&p, stream)
	case *publicpgn.FusionMediaControl:
		return EncodeFusionMediaControl(p, stream)
	case publicpgn.FusionMediaControl:
		return EncodeFusionMediaControl(&p, stream)
	case *publicpgn.FusionSiriusControl:
		return EncodeFusionSiriusControl(p, stream)
	case publicpgn.FusionSiriusControl:
		return EncodeFusionSiriusControl(&p, stream)
	case *publicpgn.FusionRequestStatus:
		return EncodeFusionRequestStatus(p, stream)
	case publicpgn.FusionRequestStatus:
		return EncodeFusionRequestStatus(&p, stream)
	case *publicpgn.FusionSetSource:
		return EncodeFusionSetSource(p, stream)
	case publicpgn.FusionSetSource:
		return EncodeFusionSetSource(&p, stream)
	case *publicpgn.FusionSetMute:
		return EncodeFusionSetMute(p, stream)
	case publicpgn.FusionSetMute:
		return EncodeFusionSetMute(&p, stream)
	case *publicpgn.FusionSetZoneVolume:
		return EncodeFusionSetZoneVolume(p, stream)
	case publicpgn.FusionSetZoneVolume:
		return EncodeFusionSetZoneVolume(&p, stream)
	case *publicpgn.FusionSetAllVolumes:
		return EncodeFusionSetAllVolumes(p, stream)
	case publicpgn.FusionSetAllVolumes:
		return EncodeFusionSetAllVolumes(&p, stream)
	case *publicpgn.AirmarAttitudeOffset:
		return EncodeAirmarAttitudeOffset(p, stream)
	case publicpgn.AirmarAttitudeOffset:
		return EncodeAirmarAttitudeOffset(&p, stream)
	case *publicpgn.AirmarSimulateMode:
		return EncodeAirmarSimulateMode(p, stream)
	case publicpgn.AirmarSimulateMode:
		return EncodeAirmarSimulateMode(&p, stream)
	case *publicpgn.AirmarCalibrateDepth:
		return EncodeAirmarCalibrateDepth(p, stream)
	case publicpgn.AirmarCalibrateDepth:
		return EncodeAirmarCalibrateDepth(&p, stream)
	case *publicpgn.AirmarCalibrateSpeed:
		return EncodeAirmarCalibrateSpeed(p, stream)
	case publicpgn.AirmarCalibrateSpeed:
		return EncodeAirmarCalibrateSpeed(&p, stream)
	case *publicpgn.AirmarCalibrateTemperature:
		return EncodeAirmarCalibrateTemperature(p, stream)
	case publicpgn.AirmarCalibrateTemperature:
		return EncodeAirmarCalibrateTemperature(&p, stream)
	case *publicpgn.AirmarSpeedFilterNone:
		return EncodeAirmarSpeedFilterNone(p, stream)
	case publicpgn.AirmarSpeedFilterNone:
		return EncodeAirmarSpeedFilterNone(&p, stream)
	case *publicpgn.AirmarSpeedFilterIir:
		return EncodeAirmarSpeedFilterIir(p, stream)
	case publicpgn.AirmarSpeedFilterIir:
		return EncodeAirmarSpeedFilterIir(&p, stream)
	case *publicpgn.AirmarTemperatureFilterNone:
		return EncodeAirmarTemperatureFilterNone(p, stream)
	case publicpgn.AirmarTemperatureFilterNone:
		return EncodeAirmarTemperatureFilterNone(&p, stream)
	case *publicpgn.AirmarTemperatureFilterIir:
		return EncodeAirmarTemperatureFilterIir(p, stream)
	case publicpgn.AirmarTemperatureFilterIir:
		return EncodeAirmarTemperatureFilterIir(&p, stream)
	case *publicpgn.AirmarNmea2000Options:
		return EncodeAirmarNmea2000Options(p, stream)
	case publicpgn.AirmarNmea2000Options:
		return EncodeAirmarNmea2000Options(&p, stream)
	case *publicpgn.MaretronDeviationCalibrationResponse:
		return EncodeMaretronDeviationCalibrationResponse(p, stream)
	case publicpgn.MaretronDeviationCalibrationResponse:
		return EncodeMaretronDeviationCalibrationResponse(&p, stream)
	case *publicpgn.MaretronSlaveResponse:
		return EncodeMaretronSlaveResponse(p, stream)
	case publicpgn.MaretronSlaveResponse:
		return EncodeMaretronSlaveResponse(&p, stream)
	case *publicpgn.Alert:
		return EncodeAlert(p, stream)
	case publicpgn.Alert:
		return EncodeAlert(&p, stream)
	case *publicpgn.AlertResponse:
		return EncodeAlertResponse(p, stream)
	case publicpgn.AlertResponse:
		return EncodeAlertResponse(&p, stream)
	case *publicpgn.AlertText:
		return EncodeAlertText(p, stream)
	case publicpgn.AlertText:
		return EncodeAlertText(&p, stream)
	case *publicpgn.SystemTime:
		return EncodeSystemTime(p, stream)
	case publicpgn.SystemTime:
		return EncodeSystemTime(&p, stream)
	case *publicpgn.Heartbeat:
		return EncodeHeartbeat(p, stream)
	case publicpgn.Heartbeat:
		return EncodeHeartbeat(&p, stream)
	case *publicpgn.ProductInformation:
		return EncodeProductInformation(p, stream)
	case publicpgn.ProductInformation:
		return EncodeProductInformation(&p, stream)
	case *publicpgn.ConfigurationInformation:
		return EncodeConfigurationInformation(p, stream)
	case publicpgn.ConfigurationInformation:
		return EncodeConfigurationInformation(&p, stream)
	case *publicpgn.ManOverboardNotification:
		return EncodeManOverboardNotification(p, stream)
	case publicpgn.ManOverboardNotification:
		return EncodeManOverboardNotification(&p, stream)
	case *publicpgn.HeadingTrackControl:
		return EncodeHeadingTrackControl(p, stream)
	case publicpgn.HeadingTrackControl:
		return EncodeHeadingTrackControl(&p, stream)
	case *publicpgn.Rudder:
		return EncodeRudder(p, stream)
	case publicpgn.Rudder:
		return EncodeRudder(&p, stream)
	case *publicpgn.VesselHeading:
		return EncodeVesselHeading(p, stream)
	case publicpgn.VesselHeading:
		return EncodeVesselHeading(&p, stream)
	case *publicpgn.RateOfTurn:
		return EncodeRateOfTurn(p, stream)
	case publicpgn.RateOfTurn:
		return EncodeRateOfTurn(&p, stream)
	case *publicpgn.Attitude:
		return EncodeAttitude(p, stream)
	case publicpgn.Attitude:
		return EncodeAttitude(&p, stream)
	case *publicpgn.MagneticVariation:
		return EncodeMagneticVariation(p, stream)
	case publicpgn.MagneticVariation:
		return EncodeMagneticVariation(&p, stream)
	case *publicpgn.EngineParametersRapidUpdate:
		return EncodeEngineParametersRapidUpdate(p, stream)
	case publicpgn.EngineParametersRapidUpdate:
		return EncodeEngineParametersRapidUpdate(&p, stream)
	case *publicpgn.EngineParametersDynamic:
		return EncodeEngineParametersDynamic(p, stream)
	case publicpgn.EngineParametersDynamic:
		return EncodeEngineParametersDynamic(&p, stream)
	case *publicpgn.TransmissionParametersDynamic:
		return EncodeTransmissionParametersDynamic(p, stream)
	case publicpgn.TransmissionParametersDynamic:
		return EncodeTransmissionParametersDynamic(&p, stream)
	case *publicpgn.TripParametersVessel:
		return EncodeTripParametersVessel(p, stream)
	case publicpgn.TripParametersVessel:
		return EncodeTripParametersVessel(&p, stream)
	case *publicpgn.TripParametersEngine:
		return EncodeTripParametersEngine(p, stream)
	case publicpgn.TripParametersEngine:
		return EncodeTripParametersEngine(&p, stream)
	case *publicpgn.EngineParametersStatic:
		return EncodeEngineParametersStatic(p, stream)
	case publicpgn.EngineParametersStatic:
		return EncodeEngineParametersStatic(&p, stream)
	case *publicpgn.LoadControllerConnectionStateControl:
		return EncodeLoadControllerConnectionStateControl(p, stream)
	case publicpgn.LoadControllerConnectionStateControl:
		return EncodeLoadControllerConnectionStateControl(&p, stream)
	case *publicpgn.BinarySwitchBankStatus:
		return EncodeBinarySwitchBankStatus(p, stream)
	case publicpgn.BinarySwitchBankStatus:
		return EncodeBinarySwitchBankStatus(&p, stream)
	case *publicpgn.SwitchBankControl:
		return EncodeSwitchBankControl(p, stream)
	case publicpgn.SwitchBankControl:
		return EncodeSwitchBankControl(&p, stream)
	case *publicpgn.AcInputStatus:
		return EncodeAcInputStatus(p, stream)
	case publicpgn.AcInputStatus:
		return EncodeAcInputStatus(&p, stream)
	case *publicpgn.AcOutputStatus:
		return EncodeAcOutputStatus(p, stream)
	case publicpgn.AcOutputStatus:
		return EncodeAcOutputStatus(&p, stream)
	case *publicpgn.FluidLevel:
		return EncodeFluidLevel(p, stream)
	case publicpgn.FluidLevel:
		return EncodeFluidLevel(&p, stream)
	case *publicpgn.DcDetailedStatus:
		return EncodeDcDetailedStatus(p, stream)
	case publicpgn.DcDetailedStatus:
		return EncodeDcDetailedStatus(&p, stream)
	case *publicpgn.ChargerStatus:
		return EncodeChargerStatus(p, stream)
	case publicpgn.ChargerStatus:
		return EncodeChargerStatus(&p, stream)
	case *publicpgn.BatteryStatus:
		return EncodeBatteryStatus(p, stream)
	case publicpgn.BatteryStatus:
		return EncodeBatteryStatus(&p, stream)
	case *publicpgn.InverterStatus:
		return EncodeInverterStatus(p, stream)
	case publicpgn.InverterStatus:
		return EncodeInverterStatus(&p, stream)
	case *publicpgn.ChargerConfigurationStatus:
		return EncodeChargerConfigurationStatus(p, stream)
	case publicpgn.ChargerConfigurationStatus:
		return EncodeChargerConfigurationStatus(&p, stream)
	case *publicpgn.InverterConfigurationStatus:
		return EncodeInverterConfigurationStatus(p, stream)
	case publicpgn.InverterConfigurationStatus:
		return EncodeInverterConfigurationStatus(&p, stream)
	case *publicpgn.BatteryConfigurationStatus:
		return EncodeBatteryConfigurationStatus(p, stream)
	case publicpgn.BatteryConfigurationStatus:
		return EncodeBatteryConfigurationStatus(&p, stream)
	case *publicpgn.AcPowerCurrentPhaseA:
		return EncodeAcPowerCurrentPhaseA(p, stream)
	case publicpgn.AcPowerCurrentPhaseA:
		return EncodeAcPowerCurrentPhaseA(&p, stream)
	case *publicpgn.AcPowerCurrentPhaseB:
		return EncodeAcPowerCurrentPhaseB(p, stream)
	case publicpgn.AcPowerCurrentPhaseB:
		return EncodeAcPowerCurrentPhaseB(&p, stream)
	case *publicpgn.AcPowerCurrentPhaseC:
		return EncodeAcPowerCurrentPhaseC(p, stream)
	case publicpgn.AcPowerCurrentPhaseC:
		return EncodeAcPowerCurrentPhaseC(&p, stream)
	case *publicpgn.AcVoltageFrequencyPhaseA:
		return EncodeAcVoltageFrequencyPhaseA(p, stream)
	case publicpgn.AcVoltageFrequencyPhaseA:
		return EncodeAcVoltageFrequencyPhaseA(&p, stream)
	case *publicpgn.AcVoltageFrequencyPhaseB:
		return EncodeAcVoltageFrequencyPhaseB(p, stream)
	case publicpgn.AcVoltageFrequencyPhaseB:
		return EncodeAcVoltageFrequencyPhaseB(&p, stream)
	case *publicpgn.AcVoltageFrequencyPhaseC:
		return EncodeAcVoltageFrequencyPhaseC(p, stream)
	case publicpgn.AcVoltageFrequencyPhaseC:
		return EncodeAcVoltageFrequencyPhaseC(&p, stream)
	case *publicpgn.ConverterStatus:
		return EncodeConverterStatus(p, stream)
	case publicpgn.ConverterStatus:
		return EncodeConverterStatus(&p, stream)
	case *publicpgn.DcVoltageCurrent:
		return EncodeDcVoltageCurrent(p, stream)
	case publicpgn.DcVoltageCurrent:
		return EncodeDcVoltageCurrent(&p, stream)
	case *publicpgn.LeewayAngle:
		return EncodeLeewayAngle(p, stream)
	case publicpgn.LeewayAngle:
		return EncodeLeewayAngle(&p, stream)
	case *publicpgn.ThrusterControlStatus:
		return EncodeThrusterControlStatus(p, stream)
	case publicpgn.ThrusterControlStatus:
		return EncodeThrusterControlStatus(&p, stream)
	case *publicpgn.ThrusterInformation:
		return EncodeThrusterInformation(p, stream)
	case publicpgn.ThrusterInformation:
		return EncodeThrusterInformation(&p, stream)
	case *publicpgn.ThrusterMotorStatus:
		return EncodeThrusterMotorStatus(p, stream)
	case publicpgn.ThrusterMotorStatus:
		return EncodeThrusterMotorStatus(&p, stream)
	case *publicpgn.Speed:
		return EncodeSpeed(p, stream)
	case publicpgn.Speed:
		return EncodeSpeed(&p, stream)
	case *publicpgn.WaterDepth:
		return EncodeWaterDepth(p, stream)
	case publicpgn.WaterDepth:
		return EncodeWaterDepth(&p, stream)
	case *publicpgn.DistanceLog:
		return EncodeDistanceLog(p, stream)
	case publicpgn.DistanceLog:
		return EncodeDistanceLog(&p, stream)
	case *publicpgn.WindlassControlStatus:
		return EncodeWindlassControlStatus(p, stream)
	case publicpgn.WindlassControlStatus:
		return EncodeWindlassControlStatus(&p, stream)
	case *publicpgn.AnchorWindlassOperatingStatus:
		return EncodeAnchorWindlassOperatingStatus(p, stream)
	case publicpgn.AnchorWindlassOperatingStatus:
		return EncodeAnchorWindlassOperatingStatus(&p, stream)
	case *publicpgn.AnchorWindlassMonitoringStatus:
		return EncodeAnchorWindlassMonitoringStatus(p, stream)
	case publicpgn.AnchorWindlassMonitoringStatus:
		return EncodeAnchorWindlassMonitoringStatus(&p, stream)
	case *publicpgn.PositionRapidUpdate:
		return EncodePositionRapidUpdate(p, stream)
	case publicpgn.PositionRapidUpdate:
		return EncodePositionRapidUpdate(&p, stream)
	case *publicpgn.CogSogRapidUpdate:
		return EncodeCogSogRapidUpdate(p, stream)
	case publicpgn.CogSogRapidUpdate:
		return EncodeCogSogRapidUpdate(&p, stream)
	case *publicpgn.GnssPositionData:
		return EncodeGnssPositionData(p, stream)
	case publicpgn.GnssPositionData:
		return EncodeGnssPositionData(&p, stream)
	case *publicpgn.TimeDate:
		return EncodeTimeDate(p, stream)
	case publicpgn.TimeDate:
		return EncodeTimeDate(&p, stream)
	case *publicpgn.AisClassAPositionReport:
		return EncodeAisClassAPositionReport(p, stream)
	case publicpgn.AisClassAPositionReport:
		return EncodeAisClassAPositionReport(&p, stream)
	case *publicpgn.AisClassBPositionReport:
		return EncodeAisClassBPositionReport(p, stream)
	case publicpgn.AisClassBPositionReport:
		return EncodeAisClassBPositionReport(&p, stream)
	case *publicpgn.AisAidsToNavigationAtonReport:
		return EncodeAisAidsToNavigationAtonReport(p, stream)
	case publicpgn.AisAidsToNavigationAtonReport:
		return EncodeAisAidsToNavigationAtonReport(&p, stream)
	case *publicpgn.Datum:
		return EncodeDatum(p, stream)
	case publicpgn.Datum:
		return EncodeDatum(&p, stream)
	case *publicpgn.UserDatum:
		return EncodeUserDatum(p, stream)
	case publicpgn.UserDatum:
		return EncodeUserDatum(&p, stream)
	case *publicpgn.CrossTrackError:
		return EncodeCrossTrackError(p, stream)
	case publicpgn.CrossTrackError:
		return EncodeCrossTrackError(&p, stream)
	case *publicpgn.NavigationData:
		return EncodeNavigationData(p, stream)
	case publicpgn.NavigationData:
		return EncodeNavigationData(&p, stream)
	case *publicpgn.NavigationRouteWpInformation:
		return EncodeNavigationRouteWpInformation(p, stream)
	case publicpgn.NavigationRouteWpInformation:
		return EncodeNavigationRouteWpInformation(&p, stream)
	case *publicpgn.SetDriftRapidUpdate:
		return EncodeSetDriftRapidUpdate(p, stream)
	case publicpgn.SetDriftRapidUpdate:
		return EncodeSetDriftRapidUpdate(&p, stream)
	case *publicpgn.NavigationRouteTimeToFromMark:
		return EncodeNavigationRouteTimeToFromMark(p, stream)
	case publicpgn.NavigationRouteTimeToFromMark:
		return EncodeNavigationRouteTimeToFromMark(&p, stream)
	case *publicpgn.GnssControlStatus:
		return EncodeGnssControlStatus(p, stream)
	case publicpgn.GnssControlStatus:
		return EncodeGnssControlStatus(&p, stream)
	case *publicpgn.GnssDops:
		return EncodeGnssDops(p, stream)
	case publicpgn.GnssDops:
		return EncodeGnssDops(&p, stream)
	case *publicpgn.GnssSatsInView:
		return EncodeGnssSatsInView(p, stream)
	case publicpgn.GnssSatsInView:
		return EncodeGnssSatsInView(&p, stream)
	case *publicpgn.GnssRaimSettings:
		return EncodeGnssRaimSettings(p, stream)
	case publicpgn.GnssRaimSettings:
		return EncodeGnssRaimSettings(&p, stream)
	case *publicpgn.GnssPseudorangeErrorStatistics:
		return EncodeGnssPseudorangeErrorStatistics(p, stream)
	case publicpgn.GnssPseudorangeErrorStatistics:
		return EncodeGnssPseudorangeErrorStatistics(&p, stream)
	case *publicpgn.DgnssCorrections:
		return EncodeDgnssCorrections(p, stream)
	case publicpgn.DgnssCorrections:
		return EncodeDgnssCorrections(&p, stream)
	case *publicpgn.GnssDifferentialCorrectionReceiverInterface:
		return EncodeGnssDifferentialCorrectionReceiverInterface(p, stream)
	case publicpgn.GnssDifferentialCorrectionReceiverInterface:
		return EncodeGnssDifferentialCorrectionReceiverInterface(&p, stream)
	case *publicpgn.GnssDifferentialCorrectionReceiverSignal:
		return EncodeGnssDifferentialCorrectionReceiverSignal(p, stream)
	case publicpgn.GnssDifferentialCorrectionReceiverSignal:
		return EncodeGnssDifferentialCorrectionReceiverSignal(&p, stream)
	case *publicpgn.GlonassAlmanacData:
		return EncodeGlonassAlmanacData(p, stream)
	case publicpgn.GlonassAlmanacData:
		return EncodeGlonassAlmanacData(&p, stream)
	case *publicpgn.AisUtcAndDateReport:
		return EncodeAisUtcAndDateReport(p, stream)
	case publicpgn.AisUtcAndDateReport:
		return EncodeAisUtcAndDateReport(&p, stream)
	case *publicpgn.AisClassAStaticAndVoyageRelatedData:
		return EncodeAisClassAStaticAndVoyageRelatedData(p, stream)
	case publicpgn.AisClassAStaticAndVoyageRelatedData:
		return EncodeAisClassAStaticAndVoyageRelatedData(&p, stream)
	case *publicpgn.AisAddressedBinaryMessage:
		return EncodeAisAddressedBinaryMessage(p, stream)
	case publicpgn.AisAddressedBinaryMessage:
		return EncodeAisAddressedBinaryMessage(&p, stream)
	case *publicpgn.AisAcknowledge:
		return EncodeAisAcknowledge(p, stream)
	case publicpgn.AisAcknowledge:
		return EncodeAisAcknowledge(&p, stream)
	case *publicpgn.AisBinaryBroadcastMessage:
		return EncodeAisBinaryBroadcastMessage(p, stream)
	case publicpgn.AisBinaryBroadcastMessage:
		return EncodeAisBinaryBroadcastMessage(&p, stream)
	case *publicpgn.RadioFrequencyModePower:
		return EncodeRadioFrequencyModePower(p, stream)
	case publicpgn.RadioFrequencyModePower:
		return EncodeRadioFrequencyModePower(&p, stream)
	case *publicpgn.AisClassBStaticDataMsg24PartA:
		return EncodeAisClassBStaticDataMsg24PartA(p, stream)
	case publicpgn.AisClassBStaticDataMsg24PartA:
		return EncodeAisClassBStaticDataMsg24PartA(&p, stream)
	case *publicpgn.AisClassBStaticDataMsg24PartB:
		return EncodeAisClassBStaticDataMsg24PartB(p, stream)
	case publicpgn.AisClassBStaticDataMsg24PartB:
		return EncodeAisClassBStaticDataMsg24PartB(&p, stream)
	case *publicpgn.RouteAndWpServiceDatabaseList:
		return EncodeRouteAndWpServiceDatabaseList(p, stream)
	case publicpgn.RouteAndWpServiceDatabaseList:
		return EncodeRouteAndWpServiceDatabaseList(&p, stream)
	case *publicpgn.RouteAndWpServiceRouteList:
		return EncodeRouteAndWpServiceRouteList(p, stream)
	case publicpgn.RouteAndWpServiceRouteList:
		return EncodeRouteAndWpServiceRouteList(&p, stream)
	case *publicpgn.RouteAndWpServiceRouteWpListAttributes:
		return EncodeRouteAndWpServiceRouteWpListAttributes(p, stream)
	case publicpgn.RouteAndWpServiceRouteWpListAttributes:
		return EncodeRouteAndWpServiceRouteWpListAttributes(&p, stream)
	case *publicpgn.RouteAndWpServiceRouteWpNamePosition:
		return EncodeRouteAndWpServiceRouteWpNamePosition(p, stream)
	case publicpgn.RouteAndWpServiceRouteWpNamePosition:
		return EncodeRouteAndWpServiceRouteWpNamePosition(&p, stream)
	case *publicpgn.RouteAndWpServiceRouteWpName:
		return EncodeRouteAndWpServiceRouteWpName(p, stream)
	case publicpgn.RouteAndWpServiceRouteWpName:
		return EncodeRouteAndWpServiceRouteWpName(&p, stream)
	case *publicpgn.RouteAndWpServiceXteLimitNavigationMethod:
		return EncodeRouteAndWpServiceXteLimitNavigationMethod(p, stream)
	case publicpgn.RouteAndWpServiceXteLimitNavigationMethod:
		return EncodeRouteAndWpServiceXteLimitNavigationMethod(&p, stream)
	case *publicpgn.RouteAndWpServiceWpComment:
		return EncodeRouteAndWpServiceWpComment(p, stream)
	case publicpgn.RouteAndWpServiceWpComment:
		return EncodeRouteAndWpServiceWpComment(&p, stream)
	case *publicpgn.RouteAndWpServiceRouteComment:
		return EncodeRouteAndWpServiceRouteComment(p, stream)
	case publicpgn.RouteAndWpServiceRouteComment:
		return EncodeRouteAndWpServiceRouteComment(&p, stream)
	case *publicpgn.RouteAndWpServiceDatabaseComment:
		return EncodeRouteAndWpServiceDatabaseComment(p, stream)
	case publicpgn.RouteAndWpServiceDatabaseComment:
		return EncodeRouteAndWpServiceDatabaseComment(&p, stream)
	case *publicpgn.RouteAndWpServiceRadiusOfTurn:
		return EncodeRouteAndWpServiceRadiusOfTurn(p, stream)
	case publicpgn.RouteAndWpServiceRadiusOfTurn:
		return EncodeRouteAndWpServiceRadiusOfTurn(&p, stream)
	case *publicpgn.RouteAndWpServiceWpListWpNamePosition:
		return EncodeRouteAndWpServiceWpListWpNamePosition(p, stream)
	case publicpgn.RouteAndWpServiceWpListWpNamePosition:
		return EncodeRouteAndWpServiceWpListWpNamePosition(&p, stream)
	case *publicpgn.WindData:
		return EncodeWindData(p, stream)
	case publicpgn.WindData:
		return EncodeWindData(&p, stream)
	case *publicpgn.EnvironmentalParametersObsolete:
		return EncodeEnvironmentalParametersObsolete(p, stream)
	case publicpgn.EnvironmentalParametersObsolete:
		return EncodeEnvironmentalParametersObsolete(&p, stream)
	case *publicpgn.EnvironmentalParameters:
		return EncodeEnvironmentalParameters(p, stream)
	case publicpgn.EnvironmentalParameters:
		return EncodeEnvironmentalParameters(&p, stream)
	case *publicpgn.Temperature:
		return EncodeTemperature(p, stream)
	case publicpgn.Temperature:
		return EncodeTemperature(&p, stream)
	case *publicpgn.Humidity:
		return EncodeHumidity(p, stream)
	case publicpgn.Humidity:
		return EncodeHumidity(&p, stream)
	case *publicpgn.ActualPressure:
		return EncodeActualPressure(p, stream)
	case publicpgn.ActualPressure:
		return EncodeActualPressure(&p, stream)
	case *publicpgn.SetPressure:
		return EncodeSetPressure(p, stream)
	case publicpgn.SetPressure:
		return EncodeSetPressure(&p, stream)
	case *publicpgn.TemperatureExtendedRange:
		return EncodeTemperatureExtendedRange(p, stream)
	case publicpgn.TemperatureExtendedRange:
		return EncodeTemperatureExtendedRange(&p, stream)
	case *publicpgn.TideStationData:
		return EncodeTideStationData(p, stream)
	case publicpgn.TideStationData:
		return EncodeTideStationData(&p, stream)
	case *publicpgn.WatermakerInputSettingAndStatus:
		return EncodeWatermakerInputSettingAndStatus(p, stream)
	case publicpgn.WatermakerInputSettingAndStatus:
		return EncodeWatermakerInputSettingAndStatus(&p, stream)
	case *publicpgn.SmallCraftStatus:
		return EncodeSmallCraftStatus(p, stream)
	case publicpgn.SmallCraftStatus:
		return EncodeSmallCraftStatus(&p, stream)
	case *publicpgn.DirectionData:
		return EncodeDirectionData(p, stream)
	case publicpgn.DirectionData:
		return EncodeDirectionData(&p, stream)
	case *publicpgn.VesselSpeedComponents:
		return EncodeVesselSpeedComponents(p, stream)
	case publicpgn.VesselSpeedComponents:
		return EncodeVesselSpeedComponents(&p, stream)
	case *publicpgn.SonichubVolume:
		return EncodeSonichubVolume(p, stream)
	case publicpgn.SonichubVolume:
		return EncodeSonichubVolume(&p, stream)
	case *publicpgn.BepMarineCzoneZcfBusDistribution:
		return EncodeBepMarineCzoneZcfBusDistribution(p, stream)
	case publicpgn.BepMarineCzoneZcfBusDistribution:
		return EncodeBepMarineCzoneZcfBusDistribution(&p, stream)
	case *publicpgn.MaretronLabel:
		return EncodeMaretronLabel(p, stream)
	case publicpgn.MaretronLabel:
		return EncodeMaretronLabel(&p, stream)
	case *publicpgn.FusionVersions:
		return EncodeFusionVersions(p, stream)
	case publicpgn.FusionVersions:
		return EncodeFusionVersions(&p, stream)
	case *publicpgn.FusionSource:
		return EncodeFusionSource(p, stream)
	case publicpgn.FusionSource:
		return EncodeFusionSource(&p, stream)
	case *publicpgn.FusionSourceCount:
		return EncodeFusionSourceCount(p, stream)
	case publicpgn.FusionSourceCount:
		return EncodeFusionSourceCount(&p, stream)
	case *publicpgn.FusionMedia:
		return EncodeFusionMedia(p, stream)
	case publicpgn.FusionMedia:
		return EncodeFusionMedia(&p, stream)
	case *publicpgn.FusionTrackName:
		return EncodeFusionTrackName(p, stream)
	case publicpgn.FusionTrackName:
		return EncodeFusionTrackName(&p, stream)
	case *publicpgn.FusionArtistName:
		return EncodeFusionArtistName(p, stream)
	case publicpgn.FusionArtistName:
		return EncodeFusionArtistName(&p, stream)
	case *publicpgn.FusionAlbumName:
		return EncodeFusionAlbumName(p, stream)
	case publicpgn.FusionAlbumName:
		return EncodeFusionAlbumName(&p, stream)
	case *publicpgn.FusionDeviceName:
		return EncodeFusionDeviceName(p, stream)
	case publicpgn.FusionDeviceName:
		return EncodeFusionDeviceName(&p, stream)
	case *publicpgn.FusionZoneName:
		return EncodeFusionZoneName(p, stream)
	case publicpgn.FusionZoneName:
		return EncodeFusionZoneName(&p, stream)
	case *publicpgn.FusionTrackPosition:
		return EncodeFusionTrackPosition(p, stream)
	case publicpgn.FusionTrackPosition:
		return EncodeFusionTrackPosition(&p, stream)
	case *publicpgn.FusionTuner:
		return EncodeFusionTuner(p, stream)
	case publicpgn.FusionTuner:
		return EncodeFusionTuner(&p, stream)
	case *publicpgn.FusionMarineTuner:
		return EncodeFusionMarineTuner(p, stream)
	case publicpgn.FusionMarineTuner:
		return EncodeFusionMarineTuner(&p, stream)
	case *publicpgn.FusionMarineSquelch:
		return EncodeFusionMarineSquelch(p, stream)
	case publicpgn.FusionMarineSquelch:
		return EncodeFusionMarineSquelch(&p, stream)
	case *publicpgn.FusionMarineScanMode:
		return EncodeFusionMarineScanMode(p, stream)
	case publicpgn.FusionMarineScanMode:
		return EncodeFusionMarineScanMode(&p, stream)
	case *publicpgn.FusionMenuItem:
		return EncodeFusionMenuItem(p, stream)
	case publicpgn.FusionMenuItem:
		return EncodeFusionMenuItem(&p, stream)
	case *publicpgn.FusionAuxGain:
		return EncodeFusionAuxGain(p, stream)
	case publicpgn.FusionAuxGain:
		return EncodeFusionAuxGain(&p, stream)
	case *publicpgn.FusionUsbRepeatStatus:
		return EncodeFusionUsbRepeatStatus(p, stream)
	case publicpgn.FusionUsbRepeatStatus:
		return EncodeFusionUsbRepeatStatus(&p, stream)
	case *publicpgn.FusionSetting:
		return EncodeFusionSetting(p, stream)
	case publicpgn.FusionSetting:
		return EncodeFusionSetting(&p, stream)
	case *publicpgn.FusionSettings:
		return EncodeFusionSettings(p, stream)
	case publicpgn.FusionSettings:
		return EncodeFusionSettings(&p, stream)
	case *publicpgn.FusionMute:
		return EncodeFusionMute(p, stream)
	case publicpgn.FusionMute:
		return EncodeFusionMute(&p, stream)
	case *publicpgn.FusionBalance:
		return EncodeFusionBalance(p, stream)
	case publicpgn.FusionBalance:
		return EncodeFusionBalance(&p, stream)
	case *publicpgn.FusionLowPassFilter:
		return EncodeFusionLowPassFilter(p, stream)
	case publicpgn.FusionLowPassFilter:
		return EncodeFusionLowPassFilter(&p, stream)
	case *publicpgn.FusionSublevels:
		return EncodeFusionSublevels(p, stream)
	case publicpgn.FusionSublevels:
		return EncodeFusionSublevels(&p, stream)
	case *publicpgn.FusionEq:
		return EncodeFusionEq(p, stream)
	case publicpgn.FusionEq:
		return EncodeFusionEq(&p, stream)
	case *publicpgn.FusionVolumeLimits:
		return EncodeFusionVolumeLimits(p, stream)
	case publicpgn.FusionVolumeLimits:
		return EncodeFusionVolumeLimits(&p, stream)
	case *publicpgn.FusionVolumes:
		return EncodeFusionVolumes(p, stream)
	case publicpgn.FusionVolumes:
		return EncodeFusionVolumes(&p, stream)
	case *publicpgn.FusionCapabilities:
		return EncodeFusionCapabilities(p, stream)
	case publicpgn.FusionCapabilities:
		return EncodeFusionCapabilities(&p, stream)
	case *publicpgn.FusionLineLevelControl:
		return EncodeFusionLineLevelControl(p, stream)
	case publicpgn.FusionLineLevelControl:
		return EncodeFusionLineLevelControl(&p, stream)
	case *publicpgn.FusionPowerState:
		return EncodeFusionPowerState(p, stream)
	case publicpgn.FusionPowerState:
		return EncodeFusionPowerState(&p, stream)
	case *publicpgn.FusionSiriusxm:
		return EncodeFusionSiriusxm(p, stream)
	case publicpgn.FusionSiriusxm:
		return EncodeFusionSiriusxm(&p, stream)
	case *publicpgn.FusionSiriusxmChannel:
		return EncodeFusionSiriusxmChannel(p, stream)
	case publicpgn.FusionSiriusxmChannel:
		return EncodeFusionSiriusxmChannel(&p, stream)
	case *publicpgn.FusionSiriusxmTitle:
		return EncodeFusionSiriusxmTitle(p, stream)
	case publicpgn.FusionSiriusxmTitle:
		return EncodeFusionSiriusxmTitle(&p, stream)
	case *publicpgn.FusionSiriusxmArtist:
		return EncodeFusionSiriusxmArtist(p, stream)
	case publicpgn.FusionSiriusxmArtist:
		return EncodeFusionSiriusxmArtist(&p, stream)
	case *publicpgn.FusionSiriusxmContentInfo:
		return EncodeFusionSiriusxmContentInfo(p, stream)
	case publicpgn.FusionSiriusxmContentInfo:
		return EncodeFusionSiriusxmContentInfo(&p, stream)
	case *publicpgn.FusionSiriusxmCategory:
		return EncodeFusionSiriusxmCategory(p, stream)
	case publicpgn.FusionSiriusxmCategory:
		return EncodeFusionSiriusxmCategory(&p, stream)
	case *publicpgn.FusionSiriusxmSignal:
		return EncodeFusionSiriusxmSignal(p, stream)
	case publicpgn.FusionSiriusxmSignal:
		return EncodeFusionSiriusxmSignal(&p, stream)
	case *publicpgn.FusionSiriusxmPresets:
		return EncodeFusionSiriusxmPresets(p, stream)
	case publicpgn.FusionSiriusxmPresets:
		return EncodeFusionSiriusxmPresets(&p, stream)
	case *publicpgn.MaretronProprietaryTemperatureHighRange:
		return EncodeMaretronProprietaryTemperatureHighRange(p, stream)
	case publicpgn.MaretronProprietaryTemperatureHighRange:
		return EncodeMaretronProprietaryTemperatureHighRange(&p, stream)
	case *publicpgn.BGKeyValueData:
		return EncodeBGKeyValueData(p, stream)
	case publicpgn.BGKeyValueData:
		return EncodeBGKeyValueData(&p, stream)
	case *publicpgn.MaretronDataInstanceChannelCorrelation:
		return EncodeMaretronDataInstanceChannelCorrelation(p, stream)
	case publicpgn.MaretronDataInstanceChannelCorrelation:
		return EncodeMaretronDataInstanceChannelCorrelation(&p, stream)
	case *publicpgn.MaretronSwitchIndicatorStatus:
		return EncodeMaretronSwitchIndicatorStatus(p, stream)
	case publicpgn.MaretronSwitchIndicatorStatus:
		return EncodeMaretronSwitchIndicatorStatus(&p, stream)
	case *publicpgn.MaretronSwitchStatusCounter:
		return EncodeMaretronSwitchStatusCounter(p, stream)
	case publicpgn.MaretronSwitchStatusCounter:
		return EncodeMaretronSwitchStatusCounter(&p, stream)
	case *publicpgn.MaretronSwitchStatusTimer:
		return EncodeMaretronSwitchStatusTimer(p, stream)
	case publicpgn.MaretronSwitchStatusTimer:
		return EncodeMaretronSwitchStatusTimer(&p, stream)
	default:
		return nil, fmt.Errorf("trying to encode a struct that isn't a PGN: %T", s)
	}
}
