// Code generated by "cmd/pgngen"; DO NOT EDIT.
package pgn
type SimnetKeyValueConst uint16
var SimnetKeyValueConstMap = map[int]FieldSpec{0: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	41: {
		BitLength: 0,
		Resolution: 60,
		},
	260: {
		BitLength: 0,
		Resolution: 0.01,
		},
	264: {
		BitLength: 0,
		Resolution: 0.01,
		},
	516: {
		BitLength: 0,
		Resolution: 0.01,
		},
	517: {
		BitLength: 0,
		Resolution: 0.01,
		},
	520: {
		BitLength: 0,
		Resolution: 0.01,
		},
	768: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	1024: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	1800: {
		BitLength: 0,
		Resolution: 0.01,
		},
	4863: {
		BitLength: 0,
		Resolution: 0,
		},
	5160: {
		BitLength: 0,
		Resolution: 0,
		},
	5161: {
		BitLength: 0,
		Resolution: 0,
		},
	9983: {
		BitLength: 0,
		Resolution: 0,
		},
	11524: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	22296: {
		BitLength: 0,
		Resolution: 0.01,
		},
	32789: {
		BitLength: 0,
		Resolution: 0,
		},
	44079: {
		BitLength: 0,
		Resolution: 0,
		},
	55087: {
		BitLength: 0,
		Resolution: 0,
		},
	 
}

type BandgKeyValueConst uint16
var BandgKeyValueConstMap = map[int]FieldSpec{0: {
		BitLength: 0,
		Resolution: 0,
		},
	11: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	16: {
		BitLength: 0,
		Resolution: 0.01,
		},
	17: {
		BitLength: 0,
		Resolution: 0.01,
		},
	18: {
		BitLength: 0,
		Resolution: 0.01,
		},
	19: {
		BitLength: 0,
		Resolution: 0.01,
		},
	20: {
		BitLength: 0,
		Resolution: 0.01,
		},
	21: {
		BitLength: 0,
		Resolution: 0.01,
		},
	22: {
		BitLength: 0,
		Resolution: 0.01,
		},
	23: {
		BitLength: 0,
		Resolution: 0.01,
		},
	24: {
		BitLength: 0,
		Resolution: 0.01,
		},
	25: {
		BitLength: 0,
		Resolution: 0.01,
		},
	26: {
		BitLength: 0,
		Resolution: 0.01,
		},
	27: {
		BitLength: 0,
		Resolution: 0.01,
		},
	28: {
		BitLength: 0,
		Resolution: 0.01,
		},
	29: {
		BitLength: 0,
		Resolution: 0.01,
		},
	30: {
		BitLength: 0,
		Resolution: 0.01,
		},
	31: {
		BitLength: 0,
		Resolution: 0.01,
		},
	50: {
		BitLength: 0,
		Resolution: 0.1,
		},
	52: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	53: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	56: {
		BitLength: 0,
		Resolution: 0.01,
		},
	57: {
		BitLength: 0,
		Resolution: 0.01,
		},
	58: {
		BitLength: 0,
		Resolution: 0.01,
		},
	59: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	64: {
		BitLength: 0,
		Resolution: 0.001,
		},
	65: {
		BitLength: 0,
		Resolution: 0.01,
		},
	73: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	77: {
		BitLength: 0,
		Resolution: 0.01,
		},
	79: {
		BitLength: 0,
		Resolution: 0.01,
		},
	80: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	81: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	83: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	85: {
		BitLength: 0,
		Resolution: 0.01,
		},
	86: {
		BitLength: 0,
		Resolution: 0.01,
		},
	89: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	100: {
		BitLength: 0,
		Resolution: 0,
		},
	102: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	103: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	104: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	105: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	109: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	111: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	113: {
		BitLength: 0,
		Resolution: 0.01,
		},
	117: {
		BitLength: 0,
		Resolution: 0.001,
		},
	124: {
		BitLength: 0,
		Resolution: 0.1,
		},
	125: {
		BitLength: 0,
		Resolution: 0.01,
		},
	126: {
		BitLength: 0,
		Resolution: 0.01,
		},
	127: {
		BitLength: 0,
		Resolution: 0.01,
		},
	129: {
		BitLength: 0,
		Resolution: 0.01,
		},
	130: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	131: {
		BitLength: 0,
		Resolution: 0.01,
		},
	132: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	135: {
		BitLength: 0,
		Resolution: 100,
		},
	152: {
		BitLength: 0,
		Resolution: 0.01,
		},
	154: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	155: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	156: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	157: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	158: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	163: {
		BitLength: 0,
		Resolution: 0,
		},
	164: {
		BitLength: 0,
		Resolution: 0,
		},
	185: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	186: {
		BitLength: 0,
		Resolution: 0.01,
		},
	194: {
		BitLength: 0,
		Resolution: 0.01,
		},
	195: {
		BitLength: 0,
		Resolution: 0.01,
		},
	199: {
		BitLength: 0,
		Resolution: 0.01,
		},
	205: {
		BitLength: 0,
		Resolution: 0.01,
		},
	207: {
		BitLength: 0,
		Resolution: 0.01,
		},
	211: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	233: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	235: {
		BitLength: 0,
		Resolution: 0.01,
		},
	239: {
		BitLength: 0,
		Resolution: 0.001,
		},
	240: {
		BitLength: 0,
		Resolution: 0.001,
		},
	241: {
		BitLength: 0,
		Resolution: 0.001,
		},
	242: {
		BitLength: 0,
		Resolution: 0.001,
		},
	243: {
		BitLength: 0,
		Resolution: 0.001,
		},
	244: {
		BitLength: 0,
		Resolution: 0.001,
		},
	245: {
		BitLength: 0,
		Resolution: 0.001,
		},
	246: {
		BitLength: 0,
		Resolution: 0.001,
		},
	247: {
		BitLength: 0,
		Resolution: 0.001,
		},
	248: {
		BitLength: 0,
		Resolution: 0.001,
		},
	256: {
		BitLength: 0,
		Resolution: 0.001,
		},
	258: {
		BitLength: 0,
		Resolution: 0.01,
		},
	259: {
		BitLength: 0,
		Resolution: 0.01,
		},
	260: {
		BitLength: 0,
		Resolution: 0.001,
		},
	261: {
		BitLength: 0,
		Resolution: 0.01,
		},
	262: {
		BitLength: 0,
		Resolution: 0.001,
		},
	265: {
		BitLength: 0,
		Resolution: 0.001,
		},
	270: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	271: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	272: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	273: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	274: {
		BitLength: 0,
		Resolution: 0.01,
		},
	275: {
		BitLength: 0,
		Resolution: 0.01,
		},
	280: {
		BitLength: 0,
		Resolution: 0.1,
		},
	281: {
		BitLength: 0,
		Resolution: 0.1,
		},
	282: {
		BitLength: 0,
		Resolution: 0.001,
		},
	283: {
		BitLength: 0,
		Resolution: 0.001,
		},
	284: {
		BitLength: 0,
		Resolution: 0.01,
		},
	285: {
		BitLength: 0,
		Resolution: 0.1,
		},
	286: {
		BitLength: 0,
		Resolution: 0.001,
		},
	287: {
		BitLength: 0,
		Resolution: 0.001,
		},
	288: {
		BitLength: 0,
		Resolution: 0.01,
		},
	289: {
		BitLength: 0,
		Resolution: 0.001,
		},
	290: {
		BitLength: 0,
		Resolution: 0.001,
		},
	291: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	292: {
		BitLength: 0,
		Resolution: 0.001,
		},
	293: {
		BitLength: 0,
		Resolution: 0.01,
		},
	294: {
		BitLength: 0,
		Resolution: 0.01,
		},
	296: {
		BitLength: 0,
		Resolution: 0.01,
		},
	297: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	298: {
		BitLength: 0,
		Resolution: 0.001,
		},
	301: {
		BitLength: 0,
		Resolution: 0.01,
		},
	302: {
		BitLength: 0,
		Resolution: 0.1,
		},
	305: {
		BitLength: 0,
		Resolution: 0.01,
		},
	306: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	307: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	308: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	309: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	310: {
		BitLength: 0,
		Resolution: 0.01,
		},
	311: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	312: {
		BitLength: 0,
		Resolution: 0.01,
		},
	313: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	314: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	315: {
		BitLength: 0,
		Resolution: 0,
		},
	316: {
		BitLength: 0,
		Resolution: 0,
		},
	317: {
		BitLength: 0,
		Resolution: 0.01,
		},
	318: {
		BitLength: 0,
		Resolution: 0.01,
		},
	319: {
		BitLength: 0,
		Resolution: 0.01,
		},
	320: {
		BitLength: 0,
		Resolution: 0.01,
		},
	321: {
		BitLength: 0,
		Resolution: 0.01,
		},
	322: {
		BitLength: 0,
		Resolution: 0.01,
		},
	323: {
		BitLength: 0,
		Resolution: 0.01,
		},
	324: {
		BitLength: 0,
		Resolution: 0.01,
		},
	325: {
		BitLength: 0,
		Resolution: 0.01,
		},
	326: {
		BitLength: 0,
		Resolution: 0.01,
		},
	327: {
		BitLength: 0,
		Resolution: 0.01,
		},
	328: {
		BitLength: 0,
		Resolution: 0.01,
		},
	329: {
		BitLength: 0,
		Resolution: 0.01,
		},
	330: {
		BitLength: 0,
		Resolution: 0.01,
		},
	331: {
		BitLength: 0,
		Resolution: 0.01,
		},
	332: {
		BitLength: 0,
		Resolution: 0.01,
		},
	336: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	337: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	338: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	380: {
		BitLength: 0,
		Resolution: 0,
		},
	381: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	382: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	383: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	384: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	385: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	386: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	387: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	 
}

