// Code generated by "cmd/pgngen"; DO NOT EDIT.
package pgn
type NavicoDiagnosticConst uint16
var NavicoDiagnosticConstMap = map[int]FieldSpec{4: {
		BitLength: 0,
		Resolution: 0,
		},
	5: {
		BitLength: 0,
		Resolution: 0,
		},
	7: {
		BitLength: 0,
		Resolution: 0,
		},
	 
}

type NavicoSourceSettingIDConst uint16
var NavicoSourceSettingIDConstMap = map[int]FieldSpec{17: {
		BitLength: 0,
		Resolution: 0,
		},
	18: {
		BitLength: 0,
		Resolution: 1,
		},
	19: {
		BitLength: 0,
		Resolution: 1,
		},
	20: {
		BitLength: 0,
		Resolution: 0,
		},
	21: {
		BitLength: 0,
		Resolution: 1,
		},
	22: {
		BitLength: 0,
		Resolution: 1,
		},
	24: {
		BitLength: 0,
		Resolution: 1,
		},
	 
}

type SimnetKeyValueConst uint16
var SimnetKeyValueConstMap = map[int]FieldSpec{0: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	41: {
		BitLength: 0,
		Resolution: 60,
		},
	260: {
		BitLength: 0,
		Resolution: 0.01,
		},
	264: {
		BitLength: 0,
		Resolution: 0.01,
		},
	516: {
		BitLength: 0,
		Resolution: 0.01,
		},
	517: {
		BitLength: 0,
		Resolution: 0.01,
		},
	520: {
		BitLength: 0,
		Resolution: 0.01,
		},
	768: {
		BitLength: 0,
		Resolution: 0.004,
		},
	1024: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	1280: {
		BitLength: 0,
		Resolution: 0.0909091,
		},
	1283: {
		BitLength: 0,
		Resolution: 0.0909091,
		},
	1285: {
		BitLength: 0,
		Resolution: 0.0909091,
		},
	1329: {
		BitLength: 0,
		Resolution: 0.0909091,
		},
	1335: {
		BitLength: 0,
		Resolution: 0.0909091,
		},
	1336: {
		BitLength: 0,
		Resolution: 0.0909091,
		},
	1337: {
		BitLength: 0,
		Resolution: 0.0909091,
		},
	1345: {
		BitLength: 0,
		Resolution: 0.0909091,
		},
	1349: {
		BitLength: 0,
		Resolution: 0.00900901,
		},
	1800: {
		BitLength: 0,
		Resolution: 0.01,
		},
	4863: {
		BitLength: 0,
		Resolution: 0,
		},
	5120: {
		BitLength: 0,
		Resolution: 0,
		},
	5123: {
		BitLength: 0,
		Resolution: 0,
		},
	5125: {
		BitLength: 0,
		Resolution: 0,
		},
	5126: {
		BitLength: 0,
		Resolution: 0,
		},
	5127: {
		BitLength: 0,
		Resolution: 0,
		},
	5128: {
		BitLength: 0,
		Resolution: 0,
		},
	5134: {
		BitLength: 0,
		Resolution: 0,
		},
	5160: {
		BitLength: 0,
		Resolution: 0,
		},
	5161: {
		BitLength: 0,
		Resolution: 0,
		},
	5163: {
		BitLength: 0,
		Resolution: 0,
		},
	5164: {
		BitLength: 0,
		Resolution: 0,
		},
	5174: {
		BitLength: 0,
		Resolution: 0,
		},
	9983: {
		BitLength: 0,
		Resolution: 0,
		},
	11524: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	16903: {
		BitLength: 0,
		Resolution: 60,
		},
	22296: {
		BitLength: 0,
		Resolution: 0.01,
		},
	32789: {
		BitLength: 0,
		Resolution: 0,
		},
	36871: {
		BitLength: 0,
		Resolution: 0,
		},
	40711: {
		BitLength: 0,
		Resolution: 0,
		},
	44079: {
		BitLength: 0,
		Resolution: 0,
		},
	49159: {
		BitLength: 0,
		Resolution: 0,
		},
	53760: {
		BitLength: 0,
		Resolution: 0,
		},
	55087: {
		BitLength: 0,
		Resolution: 0,
		},
	 
}

type BandgKeyValueConst uint16
var BandgKeyValueConstMap = map[int]FieldSpec{0: {
		BitLength: 0,
		Resolution: 0,
		},
	11: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	16: {
		BitLength: 0,
		Resolution: 0.01,
		},
	17: {
		BitLength: 0,
		Resolution: 0.01,
		},
	18: {
		BitLength: 0,
		Resolution: 0.01,
		},
	19: {
		BitLength: 0,
		Resolution: 0.01,
		},
	20: {
		BitLength: 0,
		Resolution: 0.01,
		},
	21: {
		BitLength: 0,
		Resolution: 0.01,
		},
	22: {
		BitLength: 0,
		Resolution: 0.01,
		},
	23: {
		BitLength: 0,
		Resolution: 0.01,
		},
	24: {
		BitLength: 0,
		Resolution: 0.01,
		},
	25: {
		BitLength: 0,
		Resolution: 0.01,
		},
	26: {
		BitLength: 0,
		Resolution: 0.01,
		},
	27: {
		BitLength: 0,
		Resolution: 0.01,
		},
	28: {
		BitLength: 0,
		Resolution: 0.01,
		},
	29: {
		BitLength: 0,
		Resolution: 0.01,
		},
	30: {
		BitLength: 0,
		Resolution: 0.01,
		},
	31: {
		BitLength: 0,
		Resolution: 0.01,
		},
	50: {
		BitLength: 0,
		Resolution: 0.1,
		},
	52: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	53: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	56: {
		BitLength: 0,
		Resolution: 0.01,
		},
	57: {
		BitLength: 0,
		Resolution: 0.01,
		},
	58: {
		BitLength: 0,
		Resolution: 0.01,
		},
	59: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60: {
		BitLength: 0,
		Resolution: 3.125e-08,
		},
	64: {
		BitLength: 0,
		Resolution: 0.001,
		},
	65: {
		BitLength: 0,
		Resolution: 0.01,
		},
	68: {
		BitLength: 0,
		Resolution: 3.125e-08,
		},
	73: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	77: {
		BitLength: 0,
		Resolution: 0.01,
		},
	79: {
		BitLength: 0,
		Resolution: 0.01,
		},
	81: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	83: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	85: {
		BitLength: 0,
		Resolution: 0.01,
		},
	86: {
		BitLength: 0,
		Resolution: 0.01,
		},
	89: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	100: {
		BitLength: 0,
		Resolution: 0.01,
		},
	102: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	103: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	104: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	105: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	109: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	111: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	113: {
		BitLength: 0,
		Resolution: 0.01,
		},
	117: {
		BitLength: 0,
		Resolution: 0.001,
		},
	124: {
		BitLength: 0,
		Resolution: 0.1,
		},
	125: {
		BitLength: 0,
		Resolution: 0.01,
		},
	126: {
		BitLength: 0,
		Resolution: 0.01,
		},
	127: {
		BitLength: 0,
		Resolution: 0.01,
		},
	129: {
		BitLength: 0,
		Resolution: 0.01,
		},
	130: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	131: {
		BitLength: 0,
		Resolution: 0.01,
		},
	132: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	135: {
		BitLength: 0,
		Resolution: 100,
		},
	152: {
		BitLength: 0,
		Resolution: 0.01,
		},
	154: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	155: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	156: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	157: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	158: {
		BitLength: 0,
		Resolution: 3.125e-08,
		},
	163: {
		BitLength: 0,
		Resolution: 0,
		},
	164: {
		BitLength: 0,
		Resolution: 0,
		},
	185: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	186: {
		BitLength: 0,
		Resolution: 0.01,
		},
	194: {
		BitLength: 0,
		Resolution: 0.01,
		},
	195: {
		BitLength: 0,
		Resolution: 0.01,
		},
	199: {
		BitLength: 0,
		Resolution: 0.01,
		},
	205: {
		BitLength: 0,
		Resolution: 0.01,
		},
	207: {
		BitLength: 0,
		Resolution: 0.01,
		},
	208: {
		BitLength: 0,
		Resolution: 0.01,
		},
	211: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	233: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	235: {
		BitLength: 0,
		Resolution: 0.01,
		},
	239: {
		BitLength: 0,
		Resolution: 0.001,
		},
	240: {
		BitLength: 0,
		Resolution: 0.001,
		},
	241: {
		BitLength: 0,
		Resolution: 0.001,
		},
	242: {
		BitLength: 0,
		Resolution: 0.001,
		},
	243: {
		BitLength: 0,
		Resolution: 0.001,
		},
	244: {
		BitLength: 0,
		Resolution: 0.001,
		},
	245: {
		BitLength: 0,
		Resolution: 0.001,
		},
	246: {
		BitLength: 0,
		Resolution: 0.001,
		},
	247: {
		BitLength: 0,
		Resolution: 0.001,
		},
	248: {
		BitLength: 0,
		Resolution: 0.001,
		},
	256: {
		BitLength: 0,
		Resolution: 0.001,
		},
	258: {
		BitLength: 0,
		Resolution: 0.01,
		},
	259: {
		BitLength: 0,
		Resolution: 0.01,
		},
	260: {
		BitLength: 0,
		Resolution: 0.001,
		},
	261: {
		BitLength: 0,
		Resolution: 0.01,
		},
	262: {
		BitLength: 0,
		Resolution: 0.001,
		},
	263: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	264: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	265: {
		BitLength: 0,
		Resolution: 0.001,
		},
	266: {
		BitLength: 0,
		Resolution: 0.01,
		},
	267: {
		BitLength: 0,
		Resolution: 0.001,
		},
	268: {
		BitLength: 0,
		Resolution: 0.01,
		},
	269: {
		BitLength: 0,
		Resolution: 0.01,
		},
	270: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	271: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	272: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	273: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	274: {
		BitLength: 0,
		Resolution: 0.01,
		},
	275: {
		BitLength: 0,
		Resolution: 0.01,
		},
	276: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	277: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	278: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	279: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	280: {
		BitLength: 0,
		Resolution: 0.1,
		},
	281: {
		BitLength: 0,
		Resolution: 0.1,
		},
	282: {
		BitLength: 0,
		Resolution: 0.001,
		},
	283: {
		BitLength: 0,
		Resolution: 0.001,
		},
	284: {
		BitLength: 0,
		Resolution: 0.01,
		},
	285: {
		BitLength: 0,
		Resolution: 0.1,
		},
	286: {
		BitLength: 0,
		Resolution: 0.001,
		},
	287: {
		BitLength: 0,
		Resolution: 0.001,
		},
	288: {
		BitLength: 0,
		Resolution: 0.01,
		},
	289: {
		BitLength: 0,
		Resolution: 0.001,
		},
	290: {
		BitLength: 0,
		Resolution: 0.001,
		},
	291: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	292: {
		BitLength: 0,
		Resolution: 0.001,
		},
	293: {
		BitLength: 0,
		Resolution: 0.01,
		},
	294: {
		BitLength: 0,
		Resolution: 0.01,
		},
	296: {
		BitLength: 0,
		Resolution: 0.01,
		},
	297: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	298: {
		BitLength: 0,
		Resolution: 0.001,
		},
	299: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	300: {
		BitLength: 0,
		Resolution: 1e-07,
		},
	301: {
		BitLength: 0,
		Resolution: 0.01,
		},
	302: {
		BitLength: 0,
		Resolution: 0.1,
		},
	305: {
		BitLength: 0,
		Resolution: 0.01,
		},
	306: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	307: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	308: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	309: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	310: {
		BitLength: 0,
		Resolution: 0.01,
		},
	311: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	312: {
		BitLength: 0,
		Resolution: 0.01,
		},
	313: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	314: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	315: {
		BitLength: 0,
		Resolution: 0,
		},
	316: {
		BitLength: 0,
		Resolution: 0,
		},
	317: {
		BitLength: 0,
		Resolution: 0.01,
		},
	318: {
		BitLength: 0,
		Resolution: 0.01,
		},
	319: {
		BitLength: 0,
		Resolution: 0.01,
		},
	320: {
		BitLength: 0,
		Resolution: 0.01,
		},
	321: {
		BitLength: 0,
		Resolution: 0.01,
		},
	322: {
		BitLength: 0,
		Resolution: 0.01,
		},
	323: {
		BitLength: 0,
		Resolution: 0.01,
		},
	324: {
		BitLength: 0,
		Resolution: 0.01,
		},
	325: {
		BitLength: 0,
		Resolution: 0.01,
		},
	326: {
		BitLength: 0,
		Resolution: 0.01,
		},
	327: {
		BitLength: 0,
		Resolution: 0.01,
		},
	328: {
		BitLength: 0,
		Resolution: 0.01,
		},
	329: {
		BitLength: 0,
		Resolution: 0.01,
		},
	330: {
		BitLength: 0,
		Resolution: 0.01,
		},
	331: {
		BitLength: 0,
		Resolution: 0.01,
		},
	332: {
		BitLength: 0,
		Resolution: 0.01,
		},
	336: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	337: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	338: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	364: {
		BitLength: 0,
		Resolution: 0.1,
		},
	365: {
		BitLength: 0,
		Resolution: 0.1,
		},
	380: {
		BitLength: 0,
		Resolution: 0,
		},
	381: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	382: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	383: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	384: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	385: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	386: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	387: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	409: {
		BitLength: 0,
		Resolution: 0.001,
		},
	410: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	411: {
		BitLength: 0,
		Resolution: 0.001,
		},
	412: {
		BitLength: 0,
		Resolution: 0.001,
		},
	 
}

type VictronVregConst uint16
var VictronVregConstMap = map[int]FieldSpec{260: {
		BitLength: 0,
		Resolution: 0,
		},
	261: {
		BitLength: 0,
		Resolution: 0,
		},
	270: {
		BitLength: 0,
		Resolution: 0,
		},
	288: {
		BitLength: 0,
		Resolution: 1,
		},
	304: {
		BitLength: 0,
		Resolution: 0,
		},
	305: {
		BitLength: 0,
		Resolution: 0,
		},
	306: {
		BitLength: 0,
		Resolution: 0,
		},
	307: {
		BitLength: 0,
		Resolution: 0,
		},
	512: {
		BitLength: 0,
		Resolution: 0,
		},
	513: {
		BitLength: 0,
		Resolution: 0,
		},
	514: {
		BitLength: 0,
		Resolution: 0,
		},
	515: {
		BitLength: 0,
		Resolution: 0.1,
		},
	516: {
		BitLength: 0,
		Resolution: 0,
		},
	528: {
		BitLength: 0,
		Resolution: 0.1,
		},
	529: {
		BitLength: 0,
		Resolution: 0.1,
		},
	530: {
		BitLength: 0,
		Resolution: 0.1,
		},
	531: {
		BitLength: 0,
		Resolution: 0.1,
		},
	532: {
		BitLength: 0,
		Resolution: 0.1,
		},
	544: {
		BitLength: 0,
		Resolution: 0.1,
		},
	545: {
		BitLength: 0,
		Resolution: 0.1,
		},
	546: {
		BitLength: 0,
		Resolution: 0.1,
		},
	547: {
		BitLength: 0,
		Resolution: 0.1,
		},
	548: {
		BitLength: 0,
		Resolution: 0.1,
		},
	768: {
		BitLength: 0,
		Resolution: 0.1,
		},
	769: {
		BitLength: 0,
		Resolution: 0.1,
		},
	770: {
		BitLength: 0,
		Resolution: 0.1,
		},
	771: {
		BitLength: 0,
		Resolution: 0,
		},
	772: {
		BitLength: 0,
		Resolution: 0,
		},
	773: {
		BitLength: 0,
		Resolution: 0.1,
		},
	774: {
		BitLength: 0,
		Resolution: 0.01,
		},
	775: {
		BitLength: 0,
		Resolution: 0.01,
		},
	776: {
		BitLength: 0,
		Resolution: 0,
		},
	777: {
		BitLength: 0,
		Resolution: 0,
		},
	778: {
		BitLength: 0,
		Resolution: 0,
		},
	779: {
		BitLength: 0,
		Resolution: 0,
		},
	780: {
		BitLength: 0,
		Resolution: 0,
		},
	781: {
		BitLength: 0,
		Resolution: 0,
		},
	782: {
		BitLength: 0,
		Resolution: 0.01,
		},
	783: {
		BitLength: 0,
		Resolution: 0.01,
		},
	784: {
		BitLength: 0,
		Resolution: 0.01,
		},
	785: {
		BitLength: 0,
		Resolution: 0.01,
		},
	800: {
		BitLength: 0,
		Resolution: 0.01,
		},
	801: {
		BitLength: 0,
		Resolution: 0.01,
		},
	802: {
		BitLength: 0,
		Resolution: 0.01,
		},
	803: {
		BitLength: 0,
		Resolution: 0.01,
		},
	804: {
		BitLength: 0,
		Resolution: 0.01,
		},
	805: {
		BitLength: 0,
		Resolution: 0.01,
		},
	806: {
		BitLength: 0,
		Resolution: 0.01,
		},
	807: {
		BitLength: 0,
		Resolution: 0.01,
		},
	808: {
		BitLength: 0,
		Resolution: 0.1,
		},
	809: {
		BitLength: 0,
		Resolution: 0.1,
		},
	810: {
		BitLength: 0,
		Resolution: 0.01,
		},
	811: {
		BitLength: 0,
		Resolution: 0.01,
		},
	812: {
		BitLength: 0,
		Resolution: 0.01,
		},
	813: {
		BitLength: 0,
		Resolution: 0.01,
		},
	814: {
		BitLength: 0,
		Resolution: 0.01,
		},
	815: {
		BitLength: 0,
		Resolution: 0.01,
		},
	816: {
		BitLength: 0,
		Resolution: 0,
		},
	817: {
		BitLength: 0,
		Resolution: 0.1,
		},
	818: {
		BitLength: 0,
		Resolution: 0.1,
		},
	845: {
		BitLength: 0,
		Resolution: 0,
		},
	846: {
		BitLength: 0,
		Resolution: 0,
		},
	847: {
		BitLength: 0,
		Resolution: 0,
		},
	848: {
		BitLength: 0,
		Resolution: 0.01,
		},
	849: {
		BitLength: 0,
		Resolution: 0.01,
		},
	850: {
		BitLength: 0,
		Resolution: 0.01,
		},
	851: {
		BitLength: 0,
		Resolution: 0.01,
		},
	852: {
		BitLength: 0,
		Resolution: 0.01,
		},
	853: {
		BitLength: 0,
		Resolution: 0.01,
		},
	854: {
		BitLength: 0,
		Resolution: 0.01,
		},
	855: {
		BitLength: 0,
		Resolution: 0.01,
		},
	856: {
		BitLength: 0,
		Resolution: 0.1,
		},
	857: {
		BitLength: 0,
		Resolution: 0.1,
		},
	858: {
		BitLength: 0,
		Resolution: 0.01,
		},
	859: {
		BitLength: 0,
		Resolution: 0.01,
		},
	860: {
		BitLength: 0,
		Resolution: 0.01,
		},
	861: {
		BitLength: 0,
		Resolution: 0.01,
		},
	862: {
		BitLength: 0,
		Resolution: 0.01,
		},
	863: {
		BitLength: 0,
		Resolution: 0.01,
		},
	864: {
		BitLength: 0,
		Resolution: 0,
		},
	865: {
		BitLength: 0,
		Resolution: 0.1,
		},
	866: {
		BitLength: 0,
		Resolution: 0.1,
		},
	880: {
		BitLength: 0,
		Resolution: 0,
		},
	881: {
		BitLength: 0,
		Resolution: 0,
		},
	882: {
		BitLength: 0,
		Resolution: 0,
		},
	898: {
		BitLength: 0,
		Resolution: 0.01,
		},
	899: {
		BitLength: 0,
		Resolution: 0.1,
		},
	4094: {
		BitLength: 0,
		Resolution: 60,
		},
	4095: {
		BitLength: 0,
		Resolution: 0.01,
		},
	4096: {
		BitLength: 0,
		Resolution: 1,
		},
	4097: {
		BitLength: 0,
		Resolution: 0.1,
		},
	4098: {
		BitLength: 0,
		Resolution: 0.1,
		},
	4099: {
		BitLength: 0,
		Resolution: 60,
		},
	4100: {
		BitLength: 0,
		Resolution: 0,
		},
	4101: {
		BitLength: 0,
		Resolution: 0,
		},
	4102: {
		BitLength: 0,
		Resolution: 0.01,
		},
	4103: {
		BitLength: 0,
		Resolution: 60,
		},
	4104: {
		BitLength: 0,
		Resolution: 0.1,
		},
	4105: {
		BitLength: 0,
		Resolution: 0.1,
		},
	4106: {
		BitLength: 0,
		Resolution: 60,
		},
	4107: {
		BitLength: 0,
		Resolution: 60,
		},
	4148: {
		BitLength: 0,
		Resolution: 0,
		},
	8194: {
		BitLength: 0,
		Resolution: 0.01,
		},
	8220: {
		BitLength: 0,
		Resolution: 0.001,
		},
	60781: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60782: {
		BitLength: 0,
		Resolution: 1,
		},
	60783: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60797: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60798: {
		BitLength: 0,
		Resolution: 1,
		},
	60799: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60813: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60814: {
		BitLength: 0,
		Resolution: 1,
		},
	60815: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60831: {
		BitLength: 0,
		Resolution: 0,
		},
	60840: {
		BitLength: 0,
		Resolution: 0,
		},
	60841: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60842: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60843: {
		BitLength: 0,
		Resolution: 0,
		},
	60844: {
		BitLength: 0,
		Resolution: 0,
		},
	60845: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60846: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60847: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60857: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60858: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60859: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60860: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60861: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60863: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60880: {
		BitLength: 0,
		Resolution: 1,
		},
	60881: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60882: {
		BitLength: 0,
		Resolution: 1,
		},
	60883: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60884: {
		BitLength: 0,
		Resolution: 0,
		},
	60885: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60886: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60887: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60888: {
		BitLength: 0,
		Resolution: 0,
		},
	60889: {
		BitLength: 0,
		Resolution: 0,
		},
	60890: {
		BitLength: 0,
		Resolution: 0,
		},
	60891: {
		BitLength: 0,
		Resolution: 0,
		},
	60892: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60893: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60894: {
		BitLength: 0,
		Resolution: 0,
		},
	60895: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60904: {
		BitLength: 0,
		Resolution: 0,
		},
	60905: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60906: {
		BitLength: 0,
		Resolution: 0,
		},
	60907: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60908: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60909: {
		BitLength: 0,
		Resolution: 0,
		},
	60910: {
		BitLength: 0,
		Resolution: 0,
		},
	60911: {
		BitLength: 0,
		Resolution: 0,
		},
	60912: {
		BitLength: 0,
		Resolution: 0.1,
		},
	60913: {
		BitLength: 0,
		Resolution: 0,
		},
	60914: {
		BitLength: 0,
		Resolution: 0,
		},
	60915: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60916: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60917: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60918: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60919: {
		BitLength: 0,
		Resolution: 0.01,
		},
	60920: {
		BitLength: 0,
		Resolution: 864,
		},
	60921: {
		BitLength: 0,
		Resolution: 36,
		},
	60922: {
		BitLength: 0,
		Resolution: 36,
		},
	60923: {
		BitLength: 0,
		Resolution: 36,
		},
	60924: {
		BitLength: 0,
		Resolution: 36,
		},
	60925: {
		BitLength: 0,
		Resolution: 0,
		},
	60926: {
		BitLength: 0,
		Resolution: 0,
		},
	60927: {
		BitLength: 0,
		Resolution: 0,
		},
	 
}

type MercuryKeyValueConst uint16
var MercuryKeyValueConstMap = map[int]FieldSpec{5: {
		BitLength: 0,
		Resolution: 0,
		},
	8: {
		BitLength: 0,
		Resolution: 1,
		},
	9: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	10: {
		BitLength: 0,
		Resolution: 1,
		},
	11: {
		BitLength: 0,
		Resolution: 1e-06,
		},
	12: {
		BitLength: 0,
		Resolution: 1e-06,
		},
	13: {
		BitLength: 0,
		Resolution: 1,
		},
	14: {
		BitLength: 0,
		Resolution: 0,
		},
	17: {
		BitLength: 0,
		Resolution: 0,
		},
	256: {
		BitLength: 0,
		Resolution: 0.01,
		},
	257: {
		BitLength: 0,
		Resolution: 0.01,
		},
	272: {
		BitLength: 0,
		Resolution: 0.01,
		},
	273: {
		BitLength: 0,
		Resolution: 0.01,
		},
	288: {
		BitLength: 0,
		Resolution: 0.1,
		},
	289: {
		BitLength: 0,
		Resolution: 0.1,
		},
	336: {
		BitLength: 0,
		Resolution: 0,
		},
	337: {
		BitLength: 0,
		Resolution: 0,
		},
	352: {
		BitLength: 0,
		Resolution: 0,
		},
	368: {
		BitLength: 0,
		Resolution: 0,
		},
	369: {
		BitLength: 0,
		Resolution: 0,
		},
	384: {
		BitLength: 0,
		Resolution: 0,
		},
	385: {
		BitLength: 0,
		Resolution: 0,
		},
	400: {
		BitLength: 0,
		Resolution: 0,
		},
	401: {
		BitLength: 0,
		Resolution: 0,
		},
	416: {
		BitLength: 0,
		Resolution: 0,
		},
	417: {
		BitLength: 0,
		Resolution: 0,
		},
	432: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	433: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	448: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	449: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	464: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	465: {
		BitLength: 0,
		Resolution: 0.0001,
		},
	480: {
		BitLength: 0,
		Resolution: 0,
		},
	481: {
		BitLength: 0,
		Resolution: 0,
		},
	496: {
		BitLength: 0,
		Resolution: 0,
		},
	497: {
		BitLength: 0,
		Resolution: 0,
		},
	512: {
		BitLength: 0,
		Resolution: 0.01,
		},
	513: {
		BitLength: 0,
		Resolution: 0.01,
		},
	528: {
		BitLength: 0,
		Resolution: 0,
		},
	529: {
		BitLength: 0,
		Resolution: 0,
		},
	 
}

