// Package pgn uses data from canboat.json to convert NMEA 2000 messages to strongly-typed golang data.
package pgn

// PgnInfo instances (generated by the pgngen command)s describe known NMEA 2000 messages.
type PgnInfo struct {
	// PGN (Parameter Group Number) identifies the Message
	PGN uint32
	// Description of the message.
	Description string
	// Fast if not single.
	Fast bool
	// ManId identifies the Manufacturer for Proprietary PGNs
	ManId ManufacturerCodeConst
	// Decoder is a function that generates golang data from the messsage data.
	Decoder func(MessageInfo, *PGNDataStream) (interface{}, error)
	// FieldInfo is a map a field descriptions
	FieldInfo map[int]FieldDescriptor
}

// FieldDescriptor instances describe a PGN field.
type FieldDescriptor struct {
	BitLength         uint16
	BitLengthVariable bool
	FieldType         string
	Resolution        float32
	Signed            bool
}

// PgnInfoLookup is a map of PGNs to PgnInfo pointers.
var PgnInfoLookup map[uint32][]*PgnInfo

// init initializes PgnInfoLookup from pgnList (defined in pgninfo_generated.go)
func init() {
	PgnInfoLookup = make(map[uint32][]*PgnInfo)

	for i := range pgnList {
		pi := &pgnList[i]
		val := PgnInfoLookup[pi.PGN]
		if val == nil {
			val = make([]*PgnInfo, 1)
			val[0] = pi
		} else {
			val = append(val, pi)
		}
		PgnInfoLookup[pi.PGN] = val
	}
}

// IsProprietaryPGN returns true if its argument is in one of the proprietary ranges.
func IsProprietaryPGN(pgn uint32) bool {
	if pgn >= 0x0EF00 && pgn <= 0x0EFFF {
		// proprietary PDU1 (addressed) single-frame range 0EF00 to 0xEFFF (61184 - 61439) messages.
		// Addressed means that you send it to specific node on the bus. This you can easily use for responding,
		// since you know the sender. For sender it is bit more complicate since your device address may change
		// due to address claiming. There is N2kDeviceList module for handling devices on bus and find them by
		// "NAME" (= 64 bit value set by SetDeviceInformation ).
		return true
	} else if pgn >= 0x0FF00 && pgn <= 0x0FFFF {
		// proprietary PDU2 (non addressed) single-frame range 0xFF00 to 0xFFFF (65280 - 65535).
		// Non addressed means that destination wil be 255 (=broadcast) so any cabable device can handle it.
		return true
	} else if pgn >= 0x1EF00 && pgn <= 0x1EFFF {
		// proprietary PDU1 (addressed) fast-packet PGN range 0x1EF00 to 0x1EFFF (126720 - 126975)
		return true
	} else if pgn >= 0x1FF00 && pgn <= 0x1FFFF {
		// proprietary PDU2 (non addressed) fast packet range 0x1FF00 to 0x1FFFF (130816 - 131071)
		return true
	}

	return false
}

// GetProprietaryInfo returns Manufacturer and Industry constants.
// Invalid data returned if called on non-proprietary PGNs.
func GetProprietaryInfo(data []uint8) (ManufacturerCodeConst, IndustryCodeConst, error) {
	stream := NewPgnDataStream(data)
	var man ManufacturerCodeConst
	var ind IndustryCodeConst
	var err error
	if v, err := stream.readLookupField(11); err == nil {
		man = ManufacturerCodeConst(v)
	}
	_ = stream.skipBits(2)
	if v, err := stream.readLookupField(3); err == nil {
		ind = IndustryCodeConst(v)
	}
	return man, ind, err
}
