// Code generated by "cmd/pgngen"; DO NOT EDIT.
package pgn

import (
	"time"
	"github.com/boatkit-io/tugboat/pkg/units"
)

// MessageInfo contains metadata about a decoded NMEA 2000 message
type MessageInfo struct {
	// when did we get the message
	Timestamp time.Time

	// 3-bit
	Priority uint8

	// 19-bit number
	PGN uint32

	// actually 8-bit
	SourceId uint8

	// target address, when relevant (PGNs with PF < 240)
	TargetId uint8
}


// PGN struct definitions
type ISOAcknowledgement struct {
	Info MessageInfo
	Control IsoControlConst
	GroupFunction *uint8
	PGN *uint32
}
type ISORequest struct {
	Info MessageInfo
	PGN *uint32
}
type ISOTransportProtocolDataTransfer struct {
	Info MessageInfo
	SID *uint8
	Data []uint8
}
type ISOTransportProtocolConnectionManagementRequestToSend struct {
	Info MessageInfo
	GroupFunctionCode IsoCommandConst
	MessageSize *uint16
	Packets *uint8
	PacketsReply *uint8
	PGN *uint32
}
type ISOTransportProtocolConnectionManagementClearToSend struct {
	Info MessageInfo
	GroupFunctionCode IsoCommandConst
	MaxPackets *uint8
	NextSID *uint8
	PGN *uint32
}
type ISOTransportProtocolConnectionManagementEndOfMessage struct {
	Info MessageInfo
	GroupFunctionCode IsoCommandConst
	TotalMessageSize *uint16
	TotalNumberOfFramesReceived *uint8
	PGN *uint32
}
type ISOTransportProtocolConnectionManagementBroadcastAnnounce struct {
	Info MessageInfo
	GroupFunctionCode IsoCommandConst
	MessageSize *uint16
	Packets *uint8
	PGN *uint32
}
type ISOTransportProtocolConnectionManagementAbort struct {
	Info MessageInfo
	GroupFunctionCode IsoCommandConst
	Reason []uint8
	PGN *uint32
}
type ISOAddressClaim struct {
	Info MessageInfo
	UniqueNumber *uint32
	ManufacturerCode ManufacturerCodeConst
	DeviceInstanceLower *uint8
	DeviceInstanceUpper *uint8
	DeviceFunction DeviceFunctionConst
	DeviceClass DeviceClassConst
	SystemInstance *uint8
	IndustryGroup IndustryCodeConst
	ArbitraryAddressCapable YesNoConst
}
type CarlingBreakerCommand struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageType *uint8
	BreakerMapping1 *uint8
	BreakerMapping2 *uint8
	BreakerMapping3 *uint8
	BreakerCommand *uint8
	DimValue *uint8
}
type Bus1PhaseCBasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
}
type Bus1PhaseBBasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
}
type Bus1PhaseABasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
}
type UtilityPhaseCACReactivePower struct {
	Info MessageInfo
	ReactivePower *uint16
	PowerFactor *float32
	PowerFactorLagging PowerFactorConst
}
type UtilityPhaseCACPower struct {
	Info MessageInfo
	RealPower *int32
	ApparentPower *int32
}
type UtilityPhaseCBasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
	ACRMSCurrent *uint16
}
type UtilityPhaseBACReactivePower struct {
	Info MessageInfo
	ReactivePower *uint16
	PowerFactor *float32
	PowerFactorLagging PowerFactorConst
}
type UtilityPhaseBACPower struct {
	Info MessageInfo
	RealPower *int32
	ApparentPower *int32
}
type UtilityPhaseBBasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
	ACRMSCurrent *uint16
}
type UtilityPhaseAACReactivePower struct {
	Info MessageInfo
	ReactivePower *int32
	PowerFactor *float32
	PowerFactorLagging PowerFactorConst
}
type UtilityPhaseAACPower struct {
	Info MessageInfo
	RealPower *int32
	ApparentPower *int32
}
type UtilityPhaseABasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
	ACRMSCurrent *uint16
}
type UtilityTotalACReactivePower struct {
	Info MessageInfo
	ReactivePower *int32
	PowerFactor *float32
	PowerFactorLagging PowerFactorConst
}
type UtilityTotalACPower struct {
	Info MessageInfo
	RealPower *int32
	ApparentPower *int32
}
type UtilityAverageBasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
	ACRMSCurrent *uint16
}
type GeneratorPhaseCACReactivePower struct {
	Info MessageInfo
	ReactivePower *int32
	PowerFactor *float32
	PowerFactorLagging PowerFactorConst
}
type GeneratorPhaseCACPower struct {
	Info MessageInfo
	RealPower *int32
	ApparentPower *int32
}
type GeneratorPhaseCBasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
	ACRMSCurrent *uint16
}
type GeneratorPhaseBACReactivePower struct {
	Info MessageInfo
	ReactivePower *int32
	PowerFactor *float32
	PowerFactorLagging PowerFactorConst
}
type GeneratorPhaseBACPower struct {
	Info MessageInfo
	RealPower *int32
	ApparentPower *int32
}
type GeneratorPhaseBBasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
	ACRMSCurrent *uint16
}
type GeneratorPhaseAACReactivePower struct {
	Info MessageInfo
	ReactivePower *int32
	PowerFactor *float32
	PowerFactorLagging PowerFactorConst
}
type GeneratorPhaseAACPower struct {
	Info MessageInfo
	RealPower *int32
	ApparentPower *int32
}
type GeneratorPhaseABasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
	ACRMSCurrent *uint16
}
type GeneratorTotalACReactivePower struct {
	Info MessageInfo
	ReactivePower *int32
	PowerFactor *float32
	PowerFactorLagging PowerFactorConst
}
type GeneratorTotalACPower struct {
	Info MessageInfo
	RealPower *int32
	ApparentPower *int32
}
type GeneratorAverageBasicACQuantities struct {
	Info MessageInfo
	LineLineACRMSVoltage *uint16
	LineNeutralACRMSVoltage *uint16
	ACFrequency *float32
	ACRMSCurrent *uint16
}
type ISOCommandedAddress struct {
	Info MessageInfo
	UniqueNumber []uint8
	ManufacturerCode ManufacturerCodeConst
	DeviceInstanceLower *uint8
	DeviceInstanceUpper *uint8
	DeviceFunction DeviceFunctionConst
	DeviceClass DeviceClassConst
	SystemInstance *uint8
	IndustryCode IndustryCodeConst
	NewSourceAddress *uint8
}
type MaretronNumberOfChannels struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	PGN *uint32
	NumberOfChannels *uint8
}
type MaretronProprietaryDCBreakerCurrent struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	BankInstance *uint8
	IndicatorNumber *uint8
	BreakerCurrent *float32
}
type AirmarBootStateAcknowledgment struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	BootState BootStateConst
}
type LowranceTemperature struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	TemperatureSource TemperatureSourceConst
	ActualTemperature *units.Temperature
}
type AirmarBootStateRequest struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
}
type AirmarAccessLevel struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	FormatCode *uint8
	AccessLevel AccessLevelConst
	AccessSeedKey *uint32
}
type LowranceVesselSetupEngineAndTankConfiguration struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	NumberOfEngines *uint8
	NumberOfFuelTanks *uint8
	TotalFuelCapacity *units.Volume
}
type LowranceVesselSetupEngineAndTankConfigurationBroadcast struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	NumberOfEngines *uint8
	NumberOfFuelTanks *uint8
	TotalFuelCapacity *units.Volume
}
type SimnetDeviceStatus struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	Model SimnetDeviceModelConst
	Report SimnetDeviceReportConst
	Status SimnetApStatusConst
}
type SimnetDeviceStatusRequest struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	Model SimnetDeviceModelConst
	Report SimnetDeviceReportConst
}
type SimnetPilotMode struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	Model SimnetDeviceModelConst
	Report SimnetDeviceReportConst
	Mode SimnetApModeBitfieldConst
}
type SimnetDeviceModeRequest struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	Model SimnetDeviceModelConst
	Report SimnetDeviceReportConst
}
type NavicoDepthQuality struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	Instance *uint8
	DepthQuality *float32
}
type SeatalkPilotLockedHeading struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	SID *uint8
	TargetHeadingTrue *float32
	TargetHeadingMagnetic *float32
}
type SeatalkSilenceAlarm struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	AlarmID SeatalkAlarmIdConst
	AlarmGroup SeatalkAlarmGroupConst
}
type AirmarSpeedPulseCount struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	SID *uint8
	DurationOfInterval *float32
	NumberOfPulsesReceived *uint16
}
type NMEARequestGroupFunction struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	TransmissionInterval *float32
	TransmissionIntervalOffset *float32
	NumberOfParameters *uint8
	Repeating1 []NMEARequestGroupFunctionRepeating1
}
type NMEARequestGroupFunctionRepeating1 struct {
	Parameter *uint8
	Value []uint8
}
type NMEACommandGroupFunction struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	Priority PriorityConst
	NumberOfParameters *uint8
	Repeating1 []NMEACommandGroupFunctionRepeating1
}
type NMEACommandGroupFunctionRepeating1 struct {
	Parameter *uint8
	Value []uint8
}
type NMEAAcknowledgeGroupFunction struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	PGNErrorCode PgnErrorCodeConst
	TransmissionIntervalPriorityErrorCode TransmissionIntervalConst
	NumberOfParameters *uint8
	Repeating1 []NMEAAcknowledgeGroupFunctionRepeating1
}
type NMEAAcknowledgeGroupFunctionRepeating1 struct {
	Parameter ParameterFieldConst
}
type NMEAReadFieldsReplyGroupFunction struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	UniqueID *uint8
	NumberOfSelectionPairs *uint8
	NumberOfParameters *uint8
	Repeating1 []NMEAReadFieldsReplyGroupFunctionRepeating1
	Repeating2 []NMEAReadFieldsReplyGroupFunctionRepeating2
}
type NMEAReadFieldsReplyGroupFunctionRepeating1 struct {
	SelectionParameter *uint8
	SelectionValue []uint8
}
type NMEAReadFieldsReplyGroupFunctionRepeating2 struct {
	Parameter *uint8
	Value []uint8
}
type NMEAWriteFieldsGroupFunction struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	UniqueID *uint8
	NumberOfSelectionPairs *uint8
	NumberOfParameters *uint8
	Repeating1 []NMEAWriteFieldsGroupFunctionRepeating1
	Repeating2 []NMEAWriteFieldsGroupFunctionRepeating2
}
type NMEAWriteFieldsGroupFunctionRepeating1 struct {
	SelectionParameter *uint8
	SelectionValue []uint8
}
type NMEAWriteFieldsGroupFunctionRepeating2 struct {
	Parameter *uint8
	Value []uint8
}
type NMEAWriteFieldsReplyGroupFunction struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	UniqueID *uint8
	NumberOfSelectionPairs *uint8
	NumberOfParameters *uint8
	Repeating1 []NMEAWriteFieldsReplyGroupFunctionRepeating1
	Repeating2 []NMEAWriteFieldsReplyGroupFunctionRepeating2
}
type NMEAWriteFieldsReplyGroupFunctionRepeating1 struct {
	SelectionParameter *uint8
	SelectionValue []uint8
}
type NMEAWriteFieldsReplyGroupFunctionRepeating2 struct {
	Parameter *uint8
	Value []uint8
}
type PGNListTransmitAndReceive struct {
	Info MessageInfo
	FunctionCode PgnListFunctionConst
	Repeating1 []PGNListTransmitAndReceiveRepeating1
}
type PGNListTransmitAndReceiveRepeating1 struct {
	PGN *uint32
}
type FusionMediaControl struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID FusionMessageIdConst
	SourceID *uint8
	Command FusionCommandConst
}
type FusionSiriusControl struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID FusionMessageIdConst
	SourceID *uint8
	Command FusionSiriusCommandConst
	Data *uint16
}
type FusionRequestStatus struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID FusionMessageIdConst
}
type FusionSetSource struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID FusionMessageIdConst
	SourceID *uint8
}
type FusionSetMute struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID FusionMessageIdConst
	Command FusionMuteCommandConst
}
type FusionSetZoneVolume struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID FusionMessageIdConst
	Zone *uint8
	Volume *uint8
}
type FusionSetAllVolumes struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID FusionMessageIdConst
	Zone1 *uint8
	Zone2 *uint8
	Zone3 *uint8
	Zone4 *uint8
}
type AirmarAttitudeOffset struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID AirmarCommandConst
	AzimuthOffset *float32
	PitchOffset *float32
	RollOffset *float32
}
type AirmarSimulateMode struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID AirmarCommandConst
	SimulateMode OffOnConst
}
type AirmarCalibrateDepth struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID AirmarCommandConst
	SpeedOfSoundMode *units.Velocity
}
type AirmarCalibrateSpeed struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID AirmarCommandConst
	NumberOfPairsOfDataPoints *uint8
	Repeating1 []AirmarCalibrateSpeedRepeating1
}
type AirmarCalibrateSpeedRepeating1 struct {
	InputFrequency *float32
	OutputSpeed *units.Velocity
}
type AirmarCalibrateTemperature struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID AirmarCommandConst
	TemperatureInstance AirmarTemperatureInstanceConst
	TemperatureOffset *units.Temperature
}
type AirmarSpeedFilterNone struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID AirmarCommandConst
	FilterType *uint8
	SampleInterval *float32
}
type AirmarSpeedFilterIIR struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID AirmarCommandConst
	FilterType *uint8
	SampleInterval *float32
	FilterDuration *float32
}
type AirmarTemperatureFilterNone struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID AirmarCommandConst
	FilterType *uint8
	SampleInterval *float32
}
type AirmarTemperatureFilterIIR struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID AirmarCommandConst
	FilterType *uint8
	SampleInterval *float32
	FilterDuration *float32
}
type AirmarNMEA2000Options struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID AirmarCommandConst
	TransmissionInterval AirmarTransmissionIntervalConst
}
type MaretronDeviationCalibrationResponse struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProductCode MaretronProductCodeConst
	SoftwareCode MaretronSoftwareCodeConst
	Command MaretronCommandConst
	Status MaretronStatusDeviationConst
}
type MaretronSlaveResponse struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProductCode *uint16
	SoftwareCode *uint16
	Command *uint8
	Status *uint8
}
type Alert struct {
	Info MessageInfo
	AlertType AlertTypeConst
	AlertCategory AlertCategoryConst
	AlertSystem *uint8
	AlertSubSystem *uint8
	AlertID *uint16
	DataSourceNetworkIDNAME *uint64
	DataSourceInstance *uint8
	DataSourceIndexSource *uint8
	AlertOccurrenceNumber *uint8
	TemporarySilenceStatus YesNoConst
	AcknowledgeStatus YesNoConst
	EscalationStatus YesNoConst
	TemporarySilenceSupport YesNoConst
	AcknowledgeSupport YesNoConst
	EscalationSupport YesNoConst
	AcknowledgeSourceNetworkIDNAME *uint64
	TriggerCondition AlertTriggerConditionConst
	ThresholdStatus AlertThresholdStatusConst
	AlertPriority *uint8
	AlertState AlertStateConst
}
type AlertResponse struct {
	Info MessageInfo
	AlertType AlertTypeConst
	AlertCategory AlertCategoryConst
	AlertSystem *uint8
	AlertSubSystem *uint8
	AlertID *uint16
	DataSourceNetworkIDNAME *uint64
	DataSourceInstance *uint8
	DataSourceIndexSource *uint8
	AlertOccurrenceNumber *uint8
	AcknowledgeSourceNetworkIDNAME *uint64
	ResponseCommand AlertResponseCommandConst
}
type AlertText struct {
	Info MessageInfo
	AlertType AlertTypeConst
	AlertCategory AlertCategoryConst
	AlertSystem *uint8
	AlertSubSystem *uint8
	AlertID *uint16
	DataSourceNetworkIDNAME *uint64
	DataSourceInstance *uint8
	DataSourceIndexSource *uint8
	AlertOccurrenceNumber *uint8
	LanguageID AlertLanguageIdConst
	AlertTextDescription string
	AlertLocationTextDescription string
}
type SystemTime struct {
	Info MessageInfo
	SID *uint8
	Source SystemTimeConst
	Date *uint16
	Time *float32
}
type Heartbeat struct {
	Info MessageInfo
	DataTransmitOffset *float32
	SequenceCounter *uint8
	Controller1State ControllerStateConst
	Controller2State ControllerStateConst
	EquipmentStatus EquipmentStatusConst
}
type ProductInformation struct {
	Info MessageInfo
	NMEA2000Version *float32
	ProductCode *uint16
	ModelID string
	SoftwareVersionCode string
	ModelVersion string
	ModelSerialCode string
	CertificationLevel CertificationLevelConst
	LoadEquivalency *uint8
}
type ConfigurationInformation struct {
	Info MessageInfo
	InstallationDescription1 string
	InstallationDescription2 string
	ManufacturerInformation string
}
type ManOverboardNotification struct {
	Info MessageInfo
	SID *uint8
	MOBEmitterID *uint32
	ManOverboardStatus MobStatusConst
	ActivationTime *float32
	PositionSource MobPositionSourceConst
	PositionDate *uint16
	PositionTime *float32
	Latitude *float64
	Longitude *float64
	COGReference DirectionReferenceConst
	COG *float32
	SOG *units.Velocity
	MMSIOfVesselOfOrigin *uint32
	MOBEmitterBatteryLowStatus LowBatteryConst
}
type HeadingTrackControl struct {
	Info MessageInfo
	RudderLimitExceeded YesNoConst
	OffHeadingLimitExceeded YesNoConst
	OffTrackLimitExceeded YesNoConst
	Override YesNoConst
	SteeringMode SteeringModeConst
	TurnMode TurnModeConst
	HeadingReference DirectionReferenceConst
	CommandedRudderDirection DirectionRudderConst
	CommandedRudderAngle *float32
	HeadingToSteerCourse *float32
	Track *float32
	RudderLimit *float32
	OffHeadingLimit *float32
	RadiusOfTurnOrder *units.Distance
	RateOfTurnOrder *float32
	OffTrackLimit *units.Distance
	VesselHeading *float32
}
type Rudder struct {
	Info MessageInfo
	Instance *uint8
	DirectionOrder DirectionRudderConst
	AngleOrder *float32
	Position *float32
}
type VesselHeading struct {
	Info MessageInfo
	SID *uint8
	Heading *float32
	Deviation *float32
	Variation *float32
	Reference DirectionReferenceConst
}
type RateOfTurn struct {
	Info MessageInfo
	SID *uint8
	Rate *float64
}
type Attitude struct {
	Info MessageInfo
	SID *uint8
	Yaw *float32
	Pitch *float32
	Roll *float32
}
type MagneticVariation struct {
	Info MessageInfo
	SID *uint8
	Source MagneticVariationConst
	AgeOfService *uint16
	Variation *float32
}
type EngineParametersRapidUpdate struct {
	Info MessageInfo
	Instance EngineInstanceConst
	Speed *float32
	BoostPressure *units.Pressure
	TiltTrim *int8
}
type EngineParametersDynamic struct {
	Info MessageInfo
	Instance EngineInstanceConst
	OilPressure *units.Pressure
	OilTemperature *units.Temperature
	Temperature *units.Temperature
	AlternatorPotential *float32
	FuelRate *units.Flow
	TotalEngineHours *uint32
	CoolantPressure *units.Pressure
	FuelPressure *units.Pressure
	DiscreteStatus1 EngineStatus1Const
	DiscreteStatus2 EngineStatus2Const
	EngineLoad *int8
	EngineTorque *int8
}
type TransmissionParametersDynamic struct {
	Info MessageInfo
	Instance EngineInstanceConst
	TransmissionGear GearStatusConst
	OilPressure *units.Pressure
	OilTemperature *units.Temperature
	DiscreteStatus1 TransmissionStatus1Const
}
type TripParametersVessel struct {
	Info MessageInfo
	TimeToEmpty *float32
	DistanceToEmpty *units.Distance
	EstimatedFuelRemaining *units.Volume
	TripRunTime *float32
}
type TripParametersEngine struct {
	Info MessageInfo
	Instance EngineInstanceConst
	TripFuelUsed *units.Volume
	FuelRateAverage *units.Flow
	FuelRateEconomy *units.Flow
	InstantaneousFuelEconomy *units.Flow
}
type EngineParametersStatic struct {
	Info MessageInfo
	Instance EngineInstanceConst
	RatedEngineSpeed *float32
	VIN string
	SoftwareID string
}
type LoadControllerConnectionStateControl struct {
	Info MessageInfo
	SequenceID *uint8
	ConnectionID *uint8
	State *uint8
	Status *uint8
	OperationalStatusControl *uint8
	PWMDutyCycle *uint8
	Timeon *uint8
	Timeoff *uint8
}
type BinarySwitchBankStatus struct {
	Info MessageInfo
	Instance *uint8
	Indicator1 OffOnConst
	Indicator2 OffOnConst
	Indicator3 OffOnConst
	Indicator4 OffOnConst
	Indicator5 OffOnConst
	Indicator6 OffOnConst
	Indicator7 OffOnConst
	Indicator8 OffOnConst
	Indicator9 OffOnConst
	Indicator10 OffOnConst
	Indicator11 OffOnConst
	Indicator12 OffOnConst
	Indicator13 OffOnConst
	Indicator14 OffOnConst
	Indicator15 OffOnConst
	Indicator16 OffOnConst
	Indicator17 OffOnConst
	Indicator18 OffOnConst
	Indicator19 OffOnConst
	Indicator20 OffOnConst
	Indicator21 OffOnConst
	Indicator22 OffOnConst
	Indicator23 OffOnConst
	Indicator24 OffOnConst
	Indicator25 OffOnConst
	Indicator26 OffOnConst
	Indicator27 OffOnConst
	Indicator28 OffOnConst
}
type SwitchBankControl struct {
	Info MessageInfo
	Instance *uint8
	Switch1 OffOnControlConst
	Switch2 OffOnControlConst
	Switch3 OffOnControlConst
	Switch4 OffOnControlConst
	Switch5 OffOnControlConst
	Switch6 OffOnControlConst
	Switch7 OffOnControlConst
	Switch8 OffOnControlConst
	Switch9 OffOnControlConst
	Switch10 OffOnControlConst
	Switch11 OffOnControlConst
	Switch12 OffOnControlConst
	Switch13 OffOnControlConst
	Switch14 OffOnControlConst
	Switch15 OffOnControlConst
	Switch16 OffOnControlConst
	Switch17 OffOnControlConst
	Switch18 OffOnControlConst
	Switch19 OffOnControlConst
	Switch20 OffOnControlConst
	Switch21 OffOnControlConst
	Switch22 OffOnControlConst
	Switch23 OffOnControlConst
	Switch24 OffOnControlConst
	Switch25 OffOnControlConst
	Switch26 OffOnControlConst
	Switch27 OffOnControlConst
	Switch28 OffOnControlConst
}
type ACInputStatus struct {
	Info MessageInfo
	Instance *uint8
	NumberOfLines *uint8
	Repeating1 []ACInputStatusRepeating1
}
type ACInputStatusRepeating1 struct {
	Line AcLineConst
	Acceptability AcceptabilityConst
	Voltage *float32
	Current *float32
	Frequency *float32
	BreakerSize *float32
	RealPower *uint32
	ReactivePower *uint32
	PowerFactor *float32
}
type ACOutputStatus struct {
	Info MessageInfo
	Instance *uint8
	NumberOfLines *uint8
	Repeating1 []ACOutputStatusRepeating1
}
type ACOutputStatusRepeating1 struct {
	Line LineConst
	Waveform WaveformConst
	Voltage *float32
	Current *float32
	Frequency *float32
	BreakerSize *float32
	RealPower *uint32
	ReactivePower *uint32
	PowerFactor *float32
}
type FluidLevel struct {
	Info MessageInfo
	Instance *uint8
	Type TankTypeConst
	Level *float32
	Capacity *units.Volume
}
type DCDetailedStatus struct {
	Info MessageInfo
	SID *uint8
	Instance *uint8
	DCType DcSourceConst
	StateOfCharge *uint8
	StateOfHealth *uint8
	TimeRemaining *float32
	RippleVoltage *float32
	RemainingCapacity *uint16
}
type ChargerStatus struct {
	Info MessageInfo
	Instance *uint8
	BatteryInstance *uint8
	OperatingState ChargerStateConst
	ChargeMode ChargerModeConst
	Enabled OffOnConst
	EqualizationPending OffOnConst
	EqualizationTimeRemaining *float32
}
type BatteryStatus struct {
	Info MessageInfo
	Instance *uint8
	Voltage *float32
	Current *float32
	Temperature *units.Temperature
	SID *uint8
}
type InverterStatus struct {
	Info MessageInfo
	Instance *uint8
	ACInstance *uint8
	DCInstance *uint8
	OperatingState InverterStateConst
	InverterEnable OffOnConst
}
type ChargerConfigurationStatus struct {
	Info MessageInfo
	Instance *uint8
	BatteryInstance *uint8
	ChargerEnableDisable OffOnConst
	ChargeCurrentLimit *uint8
	ChargingAlgorithm ChargingAlgorithmConst
	ChargerMode ChargerModeConst
	EstimatedTemperature DeviceTempStateConst
	EqualizeOneTimeEnableDisable OffOnConst
	OverChargeEnableDisable OffOnConst
	EqualizeTime *float32
}
type InverterConfigurationStatus struct {
	Info MessageInfo
	Instance *uint8
	ACInstance *uint8
	DCInstance *uint8
	InverterEnableDisable OffOnConst
	InverterMode InverterModeConst
	LoadSenseEnableDisable OffOnConst
	LoadSensePowerThreshold *uint16
	LoadSenseInterval *float32
}
type BatteryConfigurationStatus struct {
	Info MessageInfo
	Instance *uint8
	BatteryType BatteryTypeConst
	SupportsEqualization YesNoConst
	NominalVoltage BatteryVoltageConst
	Chemistry BatteryChemistryConst
	Capacity *uint16
	TemperatureCoefficient *int8
	PeukertExponent *float32
	ChargeEfficiencyFactor *int8
}
type ACPowerCurrentPhaseA struct {
	Info MessageInfo
	SID *uint8
	ConnectionNumber *uint8
	ACRMSCurrent *float32
	Power *int32
}
type ACPowerCurrentPhaseB struct {
	Info MessageInfo
	SID *uint8
	ConnectionNumber *uint8
	ACRMSCurrent *float32
	Power *int32
}
type ACPowerCurrentPhaseC struct {
	Info MessageInfo
	SID *uint8
	ConnectionNumber *uint8
	ACRMSCurrent *float32
	Power *int32
}
type ACVoltageFrequencyPhaseA struct {
	Info MessageInfo
	SID *uint8
	ConnectionNumber *uint8
	ACVoltageLineToNeutral *float32
	ACVoltageLineToLine *float32
	Frequency *float32
}
type ACVoltageFrequencyPhaseB struct {
	Info MessageInfo
	SID *uint8
	ConnectionNumber *uint8
	ACVoltageLineToNeutral *float32
	ACVoltageLineToLine *float32
	Frequency *float32
}
type ACVoltageFrequencyPhaseC struct {
	Info MessageInfo
	SID *uint8
	ConnectionNumber *uint8
	ACVoltageLineToNeutral *float32
	ACVoltageLineToLine *float32
	Frequency *float32
}
type ConverterStatus struct {
	Info MessageInfo
	SID *uint8
	ConnectionNumber *uint8
	OperatingState ConverterStateConst
	TemperatureState GoodWarningErrorConst
	OverloadState GoodWarningErrorConst
	LowDCVoltageState GoodWarningErrorConst
	RippleState GoodWarningErrorConst
}
type LeewayAngle struct {
	Info MessageInfo
	SID *uint8
	LeewayAngle *float32
}
type ThrusterControlStatus struct {
	Info MessageInfo
	SID *uint8
	Identifier *uint8
	DirectionControl ThrusterDirectionControlConst
	PowerEnabled OffOnConst
	RetractControl ThrusterRetractControlConst
	SpeedControl *uint8
	ControlEvents ThrusterControlEventsConst
	CommandTimeout *float32
	AzimuthControl *float32
}
type ThrusterInformation struct {
	Info MessageInfo
	Identifier *uint8
	MotorType ThrusterMotorTypeConst
	PowerRating *uint16
	MaximumTemperatureRating *units.Temperature
	MaximumRotationalSpeed *float32
}
type ThrusterMotorStatus struct {
	Info MessageInfo
	SID *uint8
	Identifier *uint8
	MotorEvents ThrusterMotorEventsConst
	Current *uint8
	Temperature *units.Temperature
	OperatingTime *float32
}
type Speed struct {
	Info MessageInfo
	SID *uint8
	SpeedWaterReferenced *units.Velocity
	SpeedGroundReferenced *units.Velocity
	SpeedWaterReferencedType WaterReferenceConst
	SpeedDirection *uint8
}
type WaterDepth struct {
	Info MessageInfo
	SID *uint8
	Depth *units.Distance
	Offset *units.Distance
	Range *units.Distance
}
type DistanceLog struct {
	Info MessageInfo
	Date *uint16
	Time *float32
	Log *units.Distance
	TripLog *units.Distance
}
type WindlassControlStatus struct {
	Info MessageInfo
	SID *uint8
	WindlassID *uint8
	WindlassDirectionControl WindlassDirectionConst
	AnchorDockingControl OffOnConst
	SpeedControlType SpeedTypeConst
	SpeedControl []uint8
	PowerEnable OffOnConst
	MechanicalLock OffOnConst
	DeckAndAnchorWash OffOnConst
	AnchorLight OffOnConst
	CommandTimeout *float32
	WindlassControlEvents WindlassControlConst
}
type AnchorWindlassOperatingStatus struct {
	Info MessageInfo
	SID *uint8
	WindlassID *uint8
	WindlassDirectionControl WindlassDirectionConst
	WindlassMotionStatus WindlassMotionConst
	RodeTypeStatus RodeTypeConst
	RodeCounterValue *units.Distance
	WindlassLineSpeed *units.Velocity
	AnchorDockingStatus DockingStatusConst
	WindlassOperatingEvents WindlassOperationConst
}
type AnchorWindlassMonitoringStatus struct {
	Info MessageInfo
	SID *uint8
	WindlassID *uint8
	WindlassMonitoringEvents WindlassMonitoringConst
	ControllerVoltage *float32
	MotorCurrent *uint8
	TotalMotorTime *float32
}
type PositionRapidUpdate struct {
	Info MessageInfo
	Latitude *float64
	Longitude *float64
}
type COGSOGRapidUpdate struct {
	Info MessageInfo
	SID *uint8
	COGReference DirectionReferenceConst
	COG *float32
	SOG *units.Velocity
}
type GNSSPositionData struct {
	Info MessageInfo
	SID *uint8
	Date *uint16
	Time *float32
	Latitude *float64
	Longitude *float64
	Altitude *units.Distance
	GNSSType GnsConst
	Method GnsMethodConst
	Integrity GnsIntegrityConst
	NumberOfSVs *uint8
	HDOP *float32
	PDOP *float32
	GeoidalSeparation *units.Distance
	ReferenceStations *uint8
	Repeating1 []GNSSPositionDataRepeating1
}
type GNSSPositionDataRepeating1 struct {
	ReferenceStationType GnsConst
	ReferenceStationID *uint16
	AgeOfDGNSSCorrections *float32
}
type TimeDate struct {
	Info MessageInfo
	Date *uint16
	Time *float32
	LocalOffset *float32
}
type AISClassAPositionReport struct {
	Info MessageInfo
	MessageID AisMessageIdConst
	RepeatIndicator RepeatIndicatorConst
	UserID *uint32
	Longitude *float64
	Latitude *float64
	PositionAccuracy PositionAccuracyConst
	RAIM RaimFlagConst
	TimeStamp TimeStampConst
	COG *float32
	SOG *units.Velocity
	CommunicationState []uint8
	AISTransceiverInformation AisTransceiverConst
	Heading *float32
	RateOfTurn *float32
	NavStatus NavStatusConst
	SpecialManeuverIndicator AisSpecialManeuverConst
	SequenceID *uint8
}
type AISClassBPositionReport struct {
	Info MessageInfo
	MessageID AisMessageIdConst
	RepeatIndicator RepeatIndicatorConst
	UserID *uint32
	Longitude *float64
	Latitude *float64
	PositionAccuracy PositionAccuracyConst
	RAIM RaimFlagConst
	TimeStamp TimeStampConst
	COG *float32
	SOG *units.Velocity
	CommunicationState []uint8
	AISTransceiverInformation AisTransceiverConst
	Heading *float32
	UnitType AisTypeConst
	IntegratedDisplay YesNoConst
	DSC YesNoConst
	Band AisBandConst
	CanHandleMsg22 YesNoConst
	AISMode AisModeConst
	AISCommunicationState AisCommunicationStateConst
}
type AISAidsToNavigationAtonReport struct {
	Info MessageInfo
	MessageID AisMessageIdConst
	RepeatIndicator RepeatIndicatorConst
	UserID *uint32
	Longitude *float64
	Latitude *float64
	PositionAccuracy PositionAccuracyConst
	RAIM RaimFlagConst
	TimeStamp TimeStampConst
	LengthDiameter *units.Distance
	BeamDiameter *units.Distance
	PositionReferenceFromStarboardEdge *units.Distance
	PositionReferenceFromTrueNorthFacingEdge *units.Distance
	AtonType AtonTypeConst
	OffPositionIndicator YesNoConst
	VirtualAtonFlag YesNoConst
	AssignedModeFlag AisAssignedModeConst
	PositionFixingDeviceType PositionFixDeviceConst
	AtonStatus []uint8
	AISTransceiverInformation AisTransceiverConst
	AtonName string
}
type Datum struct {
	Info MessageInfo
	LocalDatum string
	DeltaLatitude *float64
	DeltaLongitude *float64
	DeltaAltitude *units.Distance
	ReferenceDatum string
}
type UserDatum struct {
	Info MessageInfo
	DeltaX *units.Distance
	DeltaY *units.Distance
	DeltaZ *units.Distance
	RotationInX *float32
	RotationInY *float32
	RotationInZ *float32
	Scale *float32
	EllipsoidSemiMajorAxis *units.Distance
	EllipsoidFlatteningInverse *float32
	DatumName string
}
type CrossTrackError struct {
	Info MessageInfo
	SID *uint8
	XTEMode ResidualModeConst
	NavigationTerminated YesNoConst
	XTE *units.Distance
}
type NavigationData struct {
	Info MessageInfo
	SID *uint8
	DistanceToWaypoint *units.Distance
	CourseBearingReference DirectionReferenceConst
	PerpendicularCrossed YesNoConst
	ArrivalCircleEntered YesNoConst
	CalculationType BearingModeConst
	ETATime *float32
	ETADate *uint16
	BearingOriginToDestinationWaypoint *float32
	BearingPositionToDestinationWaypoint *float32
	OriginWaypointNumber *uint32
	DestinationWaypointNumber *uint32
	DestinationLatitude *float64
	DestinationLongitude *float64
	WaypointClosingVelocity *units.Velocity
}
type NavigationRouteWPInformation struct {
	Info MessageInfo
	StartRPS *uint16
	Nitems *uint16
	DatabaseID *uint16
	RouteID *uint16
	NavigationDirectionInRoute DirectionConst
	SupplementaryRouteWPDataAvailable OffOnConst
	RouteName string
	Repeating1 []NavigationRouteWPInformationRepeating1
}
type NavigationRouteWPInformationRepeating1 struct {
	WPID *uint16
	WPName string
	WPLatitude *float64
	WPLongitude *float64
}
type SetDriftRapidUpdate struct {
	Info MessageInfo
	SID *uint8
	SetReference DirectionReferenceConst
	Set *float32
	Drift *units.Velocity
}
type NavigationRouteTimeToFromMark struct {
	Info MessageInfo
	SID *uint8
	TimeToMark *float32
	MarkType MarkTypeConst
	MarkID *uint32
}
type GNSSControlStatus struct {
	Info MessageInfo
	SVElevationMask *float32
	PDOPMask *float32
	PDOPSwitch *float32
	SNRMask *float32
	GNSSModeDesired GnssModeConst
	DGNSSModeDesired DgnssModeConst
	PositionVelocityFilter YesNoConst
	MaxCorrectionAge *float32
	AntennaAltitudeFor2DMode *units.Distance
	UseAntennaAltitudeFor2DMode YesNoConst
}
type GNSSDOPs struct {
	Info MessageInfo
	SID *uint8
	DesiredMode GnssModeConst
	ActualMode GnssModeConst
	HDOP *float32
	VDOP *float32
	TDOP *float32
}
type GNSSSatsInView struct {
	Info MessageInfo
	SID *uint8
	RangeResidualMode RangeResidualModeConst
	SatsInView *uint8
	Repeating1 []GNSSSatsInViewRepeating1
}
type GNSSSatsInViewRepeating1 struct {
	PRN *uint8
	Elevation *float32
	Azimuth *float32
	SNR *float32
	RangeResiduals *units.Distance
	Status SatelliteStatusConst
}
type GNSSRAIMSettings struct {
	Info MessageInfo
	RadialPositionErrorMaximumThreshold *units.Distance
	ProbabilityOfFalseAlarm *int8
	ProbabilityOfMissedDetection *int8
	PseudorangeResidualFilteringTimeConstant *uint16
}
type GNSSPseudorangeErrorStatistics struct {
	Info MessageInfo
	SID *uint8
	RMSStdDevOfRangeInputs *units.Distance
	StdDevOfMajorErrorEllipse *units.Distance
	StdDevOfMinorErrorEllipse *units.Distance
	OrientationOfErrorEllipse *float32
	StdDevLatError *units.Distance
	StdDevLonError *units.Distance
	StdDevAltError *units.Distance
}
type DGNSSCorrections struct {
	Info MessageInfo
	SID *uint8
	ReferenceStationID *uint16
	ReferenceStationType GnsConst
	TimeOfCorrections *float32
	StationHealth StationHealthConst
	SatelliteID *uint8
	PRC *units.Distance
	RRC *units.Velocity
	UDRE *units.Distance
	IOD *uint8
}
type GNSSDifferentialCorrectionReceiverInterface struct {
	Info MessageInfo
	Channel *uint8
	Frequency *float32
	SerialInterfaceBitRate SerialBitRateConst
	SerialInterfaceDetectionMode SerialDetectionModeConst
	DifferentialSource DifferentialSourceConst
	DifferentialOperationMode DifferentialModeConst
}
type GNSSDifferentialCorrectionReceiverSignal struct {
	Info MessageInfo
	SID *uint8
	Channel *uint8
	SignalStrength *float32
	SignalSNR *float32
	Frequency *float32
	StationType GnsConst
	ReferenceStationID *uint16
	DifferentialSignalBitRate SerialBitRateConst
	DifferentialSignalDetectionMode SerialDetectionModeConst
	UsedAsCorrectionSource YesNoConst
	DifferentialSource DifferentialSourceConst
	TimeSinceLastSatDifferentialSync *float32
	SatelliteServiceIDNo *uint16
}
type GLONASSAlmanacData struct {
	Info MessageInfo
	PRN *uint8
	NA *uint16
	Cna *uint8
	Hna *uint8
	EpsilonNa *uint16
	DeltatnaDot *uint8
	OmegaNa *uint16
	DeltaTna *uint32
	Tna *uint32
	LambdaNa *uint32
	DeltaIna *uint32
	TauCa *uint32
	TauNa *uint16
}
type AISUTCAndDateReport struct {
	Info MessageInfo
	MessageID AisMessageIdConst
	RepeatIndicator RepeatIndicatorConst
	UserID *uint32
	Longitude *float64
	Latitude *float64
	PositionAccuracy PositionAccuracyConst
	RAIM RaimFlagConst
	PositionTime *float32
	CommunicationState []uint8
	AISTransceiverInformation AisTransceiverConst
	PositionDate *uint16
	GNSSType PositionFixDeviceConst
}
type AISClassAStaticAndVoyageRelatedData struct {
	Info MessageInfo
	MessageID AisMessageIdConst
	RepeatIndicator RepeatIndicatorConst
	UserID *uint32
	IMONumber *uint32
	Callsign string
	Name string
	TypeOfShip ShipTypeConst
	Length *units.Distance
	Beam *units.Distance
	PositionReferenceFromStarboard *units.Distance
	PositionReferenceFromBow *units.Distance
	ETADate *uint16
	ETATime *float32
	Draft *units.Distance
	Destination string
	AISVersionIndicator AisVersionConst
	GNSSType PositionFixDeviceConst
	DTE AvailableConst
	AISTransceiverInformation AisTransceiverConst
}
type AISAddressedBinaryMessage struct {
	Info MessageInfo
	MessageID AisMessageIdConst
	RepeatIndicator RepeatIndicatorConst
	SourceID *uint32
	AISTransceiverInformation AisTransceiverConst
	SequenceNumber *uint8
	DestinationID *uint32
	RetransmitFlag YesNoConst
	NumberOfBitsInBinaryDataField *uint16
	BinaryData []uint8
}
type AISAcknowledge struct {
	Info MessageInfo
	MessageID AisMessageIdConst
	RepeatIndicator RepeatIndicatorConst
	SourceID *uint32
	AISTransceiverInformation AisTransceiverConst
	Repeating1 []AISAcknowledgeRepeating1
}
type AISAcknowledgeRepeating1 struct {
	DestinationID *uint32
	SequenceNumber *uint8
}
type AISBinaryBroadcastMessage struct {
	Info MessageInfo
	MessageID AisMessageIdConst
	RepeatIndicator RepeatIndicatorConst
	SourceID *uint32
	AISTransceiverInformation AisTransceiverConst
	NumberOfBitsInBinaryDataField *uint16
	BinaryData []uint8
}
type RadioFrequencyModePower struct {
	Info MessageInfo
	RxFrequency *float32
	TxFrequency *float32
	RadioChannel string
	TxPower *uint16
	Mode TelephoneModeConst
	ChannelBandwidth *uint16
}
type AISClassBStaticDataMsg24PartA struct {
	Info MessageInfo
	MessageID AisMessageIdConst
	RepeatIndicator RepeatIndicatorConst
	UserID *uint32
	Name string
	AISTransceiverInformation AisTransceiverConst
	SequenceID *uint8
}
type AISClassBStaticDataMsg24PartB struct {
	Info MessageInfo
	MessageID AisMessageIdConst
	RepeatIndicator RepeatIndicatorConst
	UserID *uint32
	TypeOfShip ShipTypeConst
	VendorID string
	Callsign string
	Length *units.Distance
	Beam *units.Distance
	PositionReferenceFromStarboard *units.Distance
	PositionReferenceFromBow *units.Distance
	MothershipUserID *uint32
	GNSSType PositionFixDeviceConst
	AISTransceiverInformation AisTransceiverConst
	SequenceID *uint8
}
type RouteAndWPServiceDatabaseList struct {
	Info MessageInfo
	StartDatabaseID *uint16
	Nitems *uint16
	NumberOfDatabasesAvailable *uint16
	Repeating1 []RouteAndWPServiceDatabaseListRepeating1
}
type RouteAndWPServiceDatabaseListRepeating1 struct {
	DatabaseID *uint16
	DatabaseName string
	DatabaseTimestamp *float32
	DatabaseDatestamp *uint16
	WPPositionResolution WpPositionResolutionConst
	NumberOfRoutesInDatabase *uint16
	NumberOfWPsInDatabase *uint32
	NumberOfBytesInDatabase *uint32
}
type RouteAndWPServiceRouteList struct {
	Info MessageInfo
	StartRouteID *uint16
	Nitems *uint16
	NumberOfRoutesInDatabase *uint16
	DatabaseID *uint16
	Repeating1 []RouteAndWPServiceRouteListRepeating1
}
type RouteAndWPServiceRouteListRepeating1 struct {
	RouteID *uint16
	RouteName string
	WPIdentificationMethod WpIdentificationMethodConst
	RouteStatus WpRouteStatusConst
}
type RouteAndWPServiceRouteWPListAttributes struct {
	Info MessageInfo
	DatabaseID *uint16
	RouteID *uint16
	RouteWPListName string
	RouteWPListTimestamp *float32
	RouteWPListDatestamp *uint16
	ChangeAtLastTimestamp WpChangeConst
	NumberOfWPsInTheRouteWPList *uint16
	CriticalSupplementaryParameters WpCriticalParametersConst
	NavigationMethod WpNavigationMethodConst
	WPIdentificationMethod WpIdentificationMethodConst
	RouteStatus WpRouteStatusConst
	XTELimitForTheRoute *units.Distance
}
type RouteAndWPServiceRouteWPNamePosition struct {
	Info MessageInfo
	StartRPS *uint16
	Nitems *uint16
	NumberOfWPsInTheRouteWPList *uint16
	DatabaseID *uint16
	RouteID *uint16
	Repeating1 []RouteAndWPServiceRouteWPNamePositionRepeating1
}
type RouteAndWPServiceRouteWPNamePositionRepeating1 struct {
	WPID *uint16
	WPName string
	WPLatitude *float64
	WPLongitude *float64
}
type RouteAndWPServiceRouteWPName struct {
	Info MessageInfo
	StartRPS *uint16
	Nitems *uint16
	NumberOfWPsInTheRouteWPList *uint16
	DatabaseID *uint16
	RouteID *uint16
	Repeating1 []RouteAndWPServiceRouteWPNameRepeating1
}
type RouteAndWPServiceRouteWPNameRepeating1 struct {
	WPID *uint16
	WPName string
}
type RouteAndWPServiceXTELimitNavigationMethod struct {
	Info MessageInfo
	StartRPS *uint16
	Nitems *uint16
	NumberOfWPsWithASpecificXTELimitOrNavMethod *uint16
	Repeating1 []RouteAndWPServiceXTELimitNavigationMethodRepeating1
}
type RouteAndWPServiceXTELimitNavigationMethodRepeating1 struct {
	DatabaseID *uint16
	RouteID *uint16
	RPS *uint16
	XTELimitInTheLegAfterWP *units.Distance
	NavMethodInTheLegAfterWP WpNavigationMethodConst
}
type RouteAndWPServiceWPComment struct {
	Info MessageInfo
	StartID *uint16
	Nitems *uint16
	NumberOfWPsWithComments *uint16
	DatabaseID *uint16
	RouteID *uint16
	Repeating1 []RouteAndWPServiceWPCommentRepeating1
}
type RouteAndWPServiceWPCommentRepeating1 struct {
	WPIDRPS *uint16
	Comment string
}
type RouteAndWPServiceRouteComment struct {
	Info MessageInfo
	StartRouteID *uint16
	Nitems *uint16
	NumberOfRoutesWithComments *uint16
	DatabaseID *uint16
	Repeating1 []RouteAndWPServiceRouteCommentRepeating1
}
type RouteAndWPServiceRouteCommentRepeating1 struct {
	RouteID *uint16
	Comment string
}
type RouteAndWPServiceDatabaseComment struct {
	Info MessageInfo
	StartDatabaseID *uint16
	Nitems *uint16
	NumberOfDatabasesWithComments *uint16
	Repeating1 []RouteAndWPServiceDatabaseCommentRepeating1
}
type RouteAndWPServiceDatabaseCommentRepeating1 struct {
	DatabaseID *uint16
	Comment string
}
type RouteAndWPServiceRadiusOfTurn struct {
	Info MessageInfo
	StartRPS *uint16
	Nitems *uint16
	NumberOfWPsWithASpecificRadiusOfTurn *uint16
	DatabaseID *uint16
	RouteID *uint16
	Repeating1 []RouteAndWPServiceRadiusOfTurnRepeating1
}
type RouteAndWPServiceRadiusOfTurnRepeating1 struct {
	RPS *uint16
	RadiusOfTurn *units.Distance
}
type RouteAndWPServiceWPListWPNamePosition struct {
	Info MessageInfo
	StartWPID *uint16
	Nitems *uint16
	NumberOfValidWPsInTheWPList *uint16
	DatabaseID *uint16
	Repeating1 []RouteAndWPServiceWPListWPNamePositionRepeating1
}
type RouteAndWPServiceWPListWPNamePositionRepeating1 struct {
	WPID *uint16
	WPName string
	WPLatitude *float64
	WPLongitude *float64
}
type WindData struct {
	Info MessageInfo
	SID *uint8
	WindSpeed *units.Velocity
	WindAngle *float32
	Reference WindReferenceConst
}
type EnvironmentalParametersObsolete struct {
	Info MessageInfo
	SID *uint8
	WaterTemperature *units.Temperature
	OutsideAmbientAirTemperature *units.Temperature
	AtmosphericPressure *units.Pressure
}
type EnvironmentalParameters struct {
	Info MessageInfo
	SID *uint8
	TemperatureSource TemperatureSourceConst
	HumiditySource HumiditySourceConst
	Temperature *units.Temperature
	Humidity *float32
	AtmosphericPressure *units.Pressure
}
type Temperature struct {
	Info MessageInfo
	SID *uint8
	Instance *uint8
	Source TemperatureSourceConst
	ActualTemperature *units.Temperature
	SetTemperature *units.Temperature
}
type Humidity struct {
	Info MessageInfo
	SID *uint8
	Instance *uint8
	Source HumiditySourceConst
	ActualHumidity *float32
	SetHumidity *float32
}
type ActualPressure struct {
	Info MessageInfo
	SID *uint8
	Instance *uint8
	Source PressureSourceConst
	Pressure *units.Pressure
}
type SetPressure struct {
	Info MessageInfo
	SID *uint8
	Instance *uint8
	Source PressureSourceConst
	Pressure *units.Pressure
}
type TemperatureExtendedRange struct {
	Info MessageInfo
	SID *uint8
	Instance *uint8
	Source TemperatureSourceConst
	Temperature *units.Temperature
	SetTemperature *units.Temperature
}
type TideStationData struct {
	Info MessageInfo
	Mode ResidualModeConst
	TideTendency TideConst
	MeasurementDate *uint16
	MeasurementTime *float32
	StationLatitude *float64
	StationLongitude *float64
	TideLevel *units.Distance
	TideLevelStandardDeviation *units.Distance
	StationID string
	StationName string
}
type WatermakerInputSettingAndStatus struct {
	Info MessageInfo
	WatermakerOperatingState WatermakerStateConst
	ProductionStartStop YesNoConst
	RinseStartStop YesNoConst
	LowPressurePumpStatus YesNoConst
	HighPressurePumpStatus YesNoConst
	EmergencyStop YesNoConst
	ProductSolenoidValveStatus OkWarningConst
	FlushModeStatus YesNoConst
	SalinityStatus OkWarningConst
	SensorStatus OkWarningConst
	OilChangeIndicatorStatus OkWarningConst
	FilterStatus OkWarningConst
	SystemStatus OkWarningConst
	Salinity *uint16
	ProductWaterTemperature *units.Temperature
	PreFilterPressure *units.Pressure
	PostFilterPressure *units.Pressure
	FeedPressure *units.Pressure
	SystemHighPressure *units.Pressure
	ProductWaterFlow *units.Flow
	BrineWaterFlow *units.Flow
	RunTime *uint32
}
type SmallCraftStatus struct {
	Info MessageInfo
	PortTrimTab *int8
	StarboardTrimTab *int8
}
type DirectionData struct {
	Info MessageInfo
	DataMode ResidualModeConst
	COGReference DirectionReferenceConst
	SID *uint8
	COG *float32
	SOG *units.Velocity
	Heading *float32
	SpeedThroughWater *units.Velocity
	Set *float32
	Drift *units.Velocity
}
type VesselSpeedComponents struct {
	Info MessageInfo
	LongitudinalSpeedWaterReferenced *units.Velocity
	TransverseSpeedWaterReferenced *units.Velocity
	LongitudinalSpeedGroundReferenced *units.Velocity
	TransverseSpeedGroundReferenced *units.Velocity
	SternSpeedWaterReferenced *units.Velocity
	SternSpeedGroundReferenced *units.Velocity
}
type SonichubVolume struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ProprietaryID SonichubCommandConst
	Control SonichubControlConst
	Zone *uint8
	Level *uint8
}
type BEPMarineCzoneZcfBusDistribution struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ChunkIndex *uint16
	Flag *uint8
	Data []uint8
}
type MaretronLabel struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	Instance *uint8
	DataSource *uint8
	DataIndicator *uint8
	Label string
	HardwareChannel *uint8
}
type FusionVersions struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	HWVersionMajor *uint16
	HWVersionMinor *uint16
	SWVersionMajor *uint8
	SWVersionMinor *uint8
	BuildNumber *uint8
}
type FusionSource struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	CurrentSourceID *uint8
	SourceType FusionSourceTypeConst
	Flags *uint8
	Source string
}
type FusionSourceCount struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceCount *uint8
}
type FusionMedia struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Flags FusionPlayStatusConst
	Track *uint32
	TrackCount *uint32
	Length *float32
	PositionInTrack *float32
}
type FusionTrackName struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Index *uint32
	Track string
}
type FusionArtistName struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Index *uint32
	Artist string
}
type FusionAlbumName struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Index *uint32
	Album string
}
type FusionDeviceName struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Name string
}
type FusionZoneName struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Number *uint8
	Name string
}
type FusionSpeedVolumeCurrentSpeed struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Speed *uint16
	Enabled *uint8
}
type FusionIgnitionSwitchState struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	State *uint8
}
type FusionMenuLockId struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	LockId *uint32
	Flags *uint8
}
type FusionRDSData struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	RDSType *uint8
	ProgrammeType *uint8
	RDS string
}
type FusionMultiroom struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Enabled YesNoConst
	IPAddress1 *uint8
	IPAddress2 *uint8
	IPAddress3 *uint8
	IPAddress4 *uint8
}
type FusionMultiroomStatus struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Available YesNoConst
}
type FusionProcessingBypass struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Bypass YesNoConst
}
type FusionMono struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Zone *uint8
	Enabled YesNoConst
}
type FusionTrackPosition struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Progress *float32
}
type FusionTuner struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID FusionRadioSourceConst
	Scanning *uint8
	Frequency *uint32
	SignalStrength *uint8
	Track string
}
type FusionMARINETUNER struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Channel *uint8
	SignalStrength *uint8
	Name string
}
type FusionMarineSquelch struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Squelch *uint8
}
type FusionMarineScanMode struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Scan YesNoConst
}
type FusionMenuItem struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	ItemIndex *uint32
	Flags *uint8
	LockID *uint8
	Text string
}
type FusionAuxGain struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Gain *uint8
}
type FusionUSBRepeatStatus struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	ID FusionSettingConst
	Status FusionRepeatStatusConst
}
type FusionSetting struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	ID FusionSettingConst
	Value *uint32
}
type FusionSettings struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Count *uint32
	Repeating1 []FusionSettingsRepeating1
}
type FusionSettingsRepeating1 struct {
	ID FusionSettingConst
	Value *uint32
}
type FusionMute struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Mute FusionMuteCommandConst
}
type FusionBalance struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Zone *uint8
	VALUE *uint8
}
type FusionLowPassFilter struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Zone *uint8
	Filter *uint8
}
type FusionSublevels struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Zone1 *uint8
	Zone2 *uint8
	Zone3 *uint8
	Zone4 *uint8
}
type FusionEQ struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Zone *uint8
	Bass *int8
	Mid *int8
	Treble *int8
}
type FusionVolumeLimits struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Zone1VolumeLimit *uint8
	Zone2VolumeLimit *uint8
	Zone3VolumeLimit *uint8
	Zone4VolumeLimit *uint8
}
type FusionVolumes struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Zone1 *uint8
	Zone2 *uint8
	Zone3 *uint8
	Zone4 *uint8
}
type FusionCapabilities struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Zone1 *uint16
	Zone2 *uint16
	Zone3 *uint16
	Zone4 *uint16
	Global *uint16
}
type FusionLineLevelControl struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	Zone *uint8
	Control *uint8
}
type FusionPowerState struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	State FusionPowerStateConst
}
type FusionSiriusxm struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	ComState FusionSiriusComStateConst
	Alert FusionSiriusComStateConst
	AdvisoryChannel *uint16
	TuningMode FusionSiriusTuningModeConst
}
type FusionSiriusxmChannel struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	ChannelNumber *uint16
	Channel string
}
type FusionSiriusxmTitle struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Channel *uint16
	Title string
}
type FusionSiriusxmArtist struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Channel *uint16
	Artist string
}
type FusionSiriusxmContentInfo struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Channel *uint16
	Genre string
}
type FusionSiriusxmCategory struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Channel *uint16
	Name string
}
type FusionSiriusxmSignal struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Signal *uint8
}
type FusionSiriusxmPresets struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	MessageID FusionStatusMessageIdConst
	SourceID *uint8
	Count *uint8
	Values []uint8
}
type MaretronProprietaryTemperatureHighRange struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	SID *uint8
	Instance *uint8
	Source TemperatureSourceConst
	ActualTemperature *units.Temperature
	SetTemperature *units.Temperature
}
type BGKeyValueData struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	Repeating1 []BGKeyValueDataRepeating1
}
type BGKeyValueDataRepeating1 struct {
	Key *uint16
	Length *uint8
	Value []uint8
}
type MercuryEngineKeyValueData struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	Repeating1 []MercuryEngineKeyValueDataRepeating1
}
type MercuryEngineKeyValueDataRepeating1 struct {
	Key *uint16
	Length *uint8
	Value []uint8
}
type MaretronDataInstanceChannelCorrelation struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	PGN *uint32
	HardwareChannel *uint8
	Instance *uint8
	DataSource *uint8
	DataIndicator *uint8
}
type MaretronSwitchIndicatorStatus struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	IndicatorBankInstance *uint8
	NumberOfStatusFields *uint8
	Repeating1 []MaretronSwitchIndicatorStatusRepeating1
}
type MaretronSwitchIndicatorStatusRepeating1 struct {
	IndicatorStatus *uint8
}
type MaretronSwitchStatusCounter struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	Instance *uint8
	IndicatorNumber *uint8
	StartDate *uint16
	StartTime *float32
	OFFCounter *uint32
	ONCounter *uint32
	ERRORCounter *uint32
	SwitchStatus OffOnConst
}
type MaretronSwitchStatusTimer struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	Instance *uint8
	IndicatorNumber *uint8
	StartDate *uint16
	StartTime *float32
	AccumulatedOFFPeriod *uint32
	AccumulatedONPeriod *uint32
	AccumulatedERRORPeriod *uint32
	SwitchStatus OffOnConst
}
type FurunoMultiSatsInViewExtended struct {
	Info MessageInfo
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	ReportType *uint8
	Antenna *uint8
	PageType *uint8
	Page *uint8
	SatsInUse *uint8
	SatsInView *uint8
	Repeating1 []FurunoMultiSatsInViewExtendedRepeating1
}
type FurunoMultiSatsInViewExtendedRepeating1 struct {
	PRN *uint8
	Elevation *float32
	Azimuth *float32
	SNR *float32
	RangeResidual *units.Distance
	BaselineStatus FurunoBaselineStatusConst
}
// Partial type for NMEARequestGroupFunction when PGN is proprietary or unknown
type NMEARequestGroupFunctionPartial struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	TransmissionInterval *float32
	TransmissionIntervalOffset *float32
	NumberOfParameters *uint8
	RawData []byte
}
// Partial type for NMEACommandGroupFunction when PGN is proprietary or unknown
type NMEACommandGroupFunctionPartial struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	Priority PriorityConst
	NumberOfParameters *uint8
	RawData []byte
}
// Partial type for NMEAAcknowledgeGroupFunction when PGN is proprietary or unknown
type NMEAAcknowledgeGroupFunctionPartial struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	PGNErrorCode PgnErrorCodeConst
	TransmissionIntervalPriorityErrorCode TransmissionIntervalConst
	NumberOfParameters *uint8
	RawData []byte
}
// Partial type for NMEAReadFieldsReplyGroupFunction when PGN is proprietary or unknown
type NMEAReadFieldsReplyGroupFunctionPartial struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	UniqueID *uint8
	NumberOfSelectionPairs *uint8
	NumberOfParameters *uint8
	RawData []byte
}
// Partial type for NMEAWriteFieldsGroupFunction when PGN is proprietary or unknown
type NMEAWriteFieldsGroupFunctionPartial struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	UniqueID *uint8
	NumberOfSelectionPairs *uint8
	NumberOfParameters *uint8
	RawData []byte
}
// Partial type for NMEAWriteFieldsReplyGroupFunction when PGN is proprietary or unknown
type NMEAWriteFieldsReplyGroupFunctionPartial struct {
	Info MessageInfo
	FunctionCode GroupFunctionConst
	PGN *uint32
	ManufacturerCode ManufacturerCodeConst
	IndustryCode IndustryCodeConst
	UniqueID *uint8
	NumberOfSelectionPairs *uint8
	NumberOfParameters *uint8
	RawData []byte
}
