// Code generated by "cmd/pgngen"; DO NOT EDIT.
package client

import (
	"context"
)

// SubscriptionHandler defines the interface for handling PGN subscriptions
type SubscriptionHandler interface {
	HandlePGN(ctx context.Context, pgn uint32, data interface{}) error
}

// PGNSubscription represents a subscription to a specific PGN
type PGNSubscription struct {
	PGN      uint32
	Handler  SubscriptionHandler
	Priority int
}

// SubscriptionManager manages PGN subscriptions
type SubscriptionManager struct {
	subscriptions map[uint32][]SubscriptionHandler
}

// NewSubscriptionManager creates a new subscription manager
func NewSubscriptionManager() *SubscriptionManager {
	return &SubscriptionManager{
		subscriptions: make(map[uint32][]SubscriptionHandler),
	}
}

// Subscribe adds a subscription for a specific PGN
func (sm *SubscriptionManager) Subscribe(pgn uint32, handler SubscriptionHandler) {
	sm.subscriptions[pgn] = append(sm.subscriptions[pgn], handler)
}

// Unsubscribe removes a subscription for a specific PGN
func (sm *SubscriptionManager) Unsubscribe(pgn uint32, handler SubscriptionHandler) {
	handlers := sm.subscriptions[pgn]
	for i, h := range handlers {
		if h == handler {
			sm.subscriptions[pgn] = append(handlers[:i], handlers[i+1:]...)
			break
		}
	}
}

// NotifySubscribers notifies all subscribers of a PGN
func (sm *SubscriptionManager) NotifySubscribers(ctx context.Context, pgn uint32, data interface{}) error {
	handlers := sm.subscriptions[pgn]
	for _, handler := range handlers {
		if err := handler.HandlePGN(ctx, pgn, data); err != nil {
			return err
		}
	}
	return nil
}
