// Code generated by "cmd/pgngen"; DO NOT EDIT.
package client

// WriteInterface defines the interface for writing PGN data
type WriteInterface interface {
	Encode() ([]byte, error)
	GetMessageInfo() *MessageInfo
	SetMessageInfo(*MessageInfo)
}

// MessageWriter provides utilities for writing PGN messages
type MessageWriter struct {
	// Implementation details will be added as needed
}

// NewMessageWriter creates a new message writer
func NewMessageWriter() *MessageWriter {
	return &MessageWriter{}
}
