// Code generated by "cmd/pgngen"; DO NOT EDIT.
package runtime

import (
	"fmt"
)

// PgnDiscriminator contains the information needed to discriminate between PGN variants
type PgnDiscriminator struct {
	PgnInfo    *PgnInfo
	MatchSpecs []MatchFieldSpec
}

// MatchFieldSpec contains a FieldSpec and the expected match value for discrimination
type MatchFieldSpec struct {
	FieldSpec  *FieldSpec
	MatchValue int
}

// matchesVariant checks if the data stream matches the specified variant's match fields
func matchesVariant(stream *DataStream, matchSpecs []MatchFieldSpec) bool {
	// Reset stream position for each variant check
	stream.resetToStart()
	
	for _, matchSpec := range matchSpecs {
		// Use ReadRaw since match values are raw (unscaled)
		if value, err := ReadRaw[uint64](stream, matchSpec.FieldSpec); err != nil {
			return false
		} else if value == nil || *value != uint64(matchSpec.MatchValue) {
			return false
		}
	}
	return true
}
