// Code generated by "cmd/pgngen"; DO NOT EDIT.
package runtime

import (
	"fmt"
)

// EncodeIsoAcknowledgement encodes a IsoAcknowledgement struct to NMEA 2000 wire format
func EncodeIsoAcknowledgement(p *IsoAcknowledgement, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for IsoAcknowledgement")
}

// EncodeIsoRequest encodes a IsoRequest struct to NMEA 2000 wire format
func EncodeIsoRequest(p *IsoRequest, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for IsoRequest")
}

// EncodeIsoTransportProtocolDataTransfer encodes a IsoTransportProtocolDataTransfer struct to NMEA 2000 wire format
func EncodeIsoTransportProtocolDataTransfer(p *IsoTransportProtocolDataTransfer, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for IsoTransportProtocolDataTransfer")
}

// EncodeIsoTransportProtocolConnectionManagementRequestToSend encodes a IsoTransportProtocolConnectionManagementRequestToSend struct to NMEA 2000 wire format
func EncodeIsoTransportProtocolConnectionManagementRequestToSend(p *IsoTransportProtocolConnectionManagementRequestToSend, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for IsoTransportProtocolConnectionManagementRequestToSend")
}

// EncodeIsoTransportProtocolConnectionManagementClearToSend encodes a IsoTransportProtocolConnectionManagementClearToSend struct to NMEA 2000 wire format
func EncodeIsoTransportProtocolConnectionManagementClearToSend(p *IsoTransportProtocolConnectionManagementClearToSend, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for IsoTransportProtocolConnectionManagementClearToSend")
}

// EncodeIsoTransportProtocolConnectionManagementEndOfMessage encodes a IsoTransportProtocolConnectionManagementEndOfMessage struct to NMEA 2000 wire format
func EncodeIsoTransportProtocolConnectionManagementEndOfMessage(p *IsoTransportProtocolConnectionManagementEndOfMessage, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for IsoTransportProtocolConnectionManagementEndOfMessage")
}

// EncodeIsoTransportProtocolConnectionManagementBroadcastAnnounce encodes a IsoTransportProtocolConnectionManagementBroadcastAnnounce struct to NMEA 2000 wire format
func EncodeIsoTransportProtocolConnectionManagementBroadcastAnnounce(p *IsoTransportProtocolConnectionManagementBroadcastAnnounce, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for IsoTransportProtocolConnectionManagementBroadcastAnnounce")
}

// EncodeIsoTransportProtocolConnectionManagementAbort encodes a IsoTransportProtocolConnectionManagementAbort struct to NMEA 2000 wire format
func EncodeIsoTransportProtocolConnectionManagementAbort(p *IsoTransportProtocolConnectionManagementAbort, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for IsoTransportProtocolConnectionManagementAbort")
}

// EncodeIsoAddressClaim encodes a IsoAddressClaim struct to NMEA 2000 wire format
func EncodeIsoAddressClaim(p *IsoAddressClaim, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for IsoAddressClaim")
}

// EncodeBus1PhaseCBasicAcQuantities encodes a Bus1PhaseCBasicAcQuantities struct to NMEA 2000 wire format
func EncodeBus1PhaseCBasicAcQuantities(p *Bus1PhaseCBasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Bus1PhaseCBasicAcQuantities")
}

// EncodeBus1PhaseBBasicAcQuantities encodes a Bus1PhaseBBasicAcQuantities struct to NMEA 2000 wire format
func EncodeBus1PhaseBBasicAcQuantities(p *Bus1PhaseBBasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Bus1PhaseBBasicAcQuantities")
}

// EncodeBus1PhaseABasicAcQuantities encodes a Bus1PhaseABasicAcQuantities struct to NMEA 2000 wire format
func EncodeBus1PhaseABasicAcQuantities(p *Bus1PhaseABasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Bus1PhaseABasicAcQuantities")
}

// EncodeUtilityPhaseCAcReactivePower encodes a UtilityPhaseCAcReactivePower struct to NMEA 2000 wire format
func EncodeUtilityPhaseCAcReactivePower(p *UtilityPhaseCAcReactivePower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityPhaseCAcReactivePower")
}

// EncodeUtilityPhaseCAcPower encodes a UtilityPhaseCAcPower struct to NMEA 2000 wire format
func EncodeUtilityPhaseCAcPower(p *UtilityPhaseCAcPower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityPhaseCAcPower")
}

// EncodeUtilityPhaseCBasicAcQuantities encodes a UtilityPhaseCBasicAcQuantities struct to NMEA 2000 wire format
func EncodeUtilityPhaseCBasicAcQuantities(p *UtilityPhaseCBasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityPhaseCBasicAcQuantities")
}

// EncodeUtilityPhaseBAcReactivePower encodes a UtilityPhaseBAcReactivePower struct to NMEA 2000 wire format
func EncodeUtilityPhaseBAcReactivePower(p *UtilityPhaseBAcReactivePower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityPhaseBAcReactivePower")
}

// EncodeUtilityPhaseBAcPower encodes a UtilityPhaseBAcPower struct to NMEA 2000 wire format
func EncodeUtilityPhaseBAcPower(p *UtilityPhaseBAcPower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityPhaseBAcPower")
}

// EncodeUtilityPhaseBBasicAcQuantities encodes a UtilityPhaseBBasicAcQuantities struct to NMEA 2000 wire format
func EncodeUtilityPhaseBBasicAcQuantities(p *UtilityPhaseBBasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityPhaseBBasicAcQuantities")
}

// EncodeUtilityPhaseAAcReactivePower encodes a UtilityPhaseAAcReactivePower struct to NMEA 2000 wire format
func EncodeUtilityPhaseAAcReactivePower(p *UtilityPhaseAAcReactivePower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityPhaseAAcReactivePower")
}

// EncodeUtilityPhaseAAcPower encodes a UtilityPhaseAAcPower struct to NMEA 2000 wire format
func EncodeUtilityPhaseAAcPower(p *UtilityPhaseAAcPower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityPhaseAAcPower")
}

// EncodeUtilityPhaseABasicAcQuantities encodes a UtilityPhaseABasicAcQuantities struct to NMEA 2000 wire format
func EncodeUtilityPhaseABasicAcQuantities(p *UtilityPhaseABasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityPhaseABasicAcQuantities")
}

// EncodeUtilityTotalAcReactivePower encodes a UtilityTotalAcReactivePower struct to NMEA 2000 wire format
func EncodeUtilityTotalAcReactivePower(p *UtilityTotalAcReactivePower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityTotalAcReactivePower")
}

// EncodeUtilityTotalAcPower encodes a UtilityTotalAcPower struct to NMEA 2000 wire format
func EncodeUtilityTotalAcPower(p *UtilityTotalAcPower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityTotalAcPower")
}

// EncodeUtilityAverageBasicAcQuantities encodes a UtilityAverageBasicAcQuantities struct to NMEA 2000 wire format
func EncodeUtilityAverageBasicAcQuantities(p *UtilityAverageBasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UtilityAverageBasicAcQuantities")
}

// EncodeGeneratorPhaseCAcReactivePower encodes a GeneratorPhaseCAcReactivePower struct to NMEA 2000 wire format
func EncodeGeneratorPhaseCAcReactivePower(p *GeneratorPhaseCAcReactivePower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorPhaseCAcReactivePower")
}

// EncodeGeneratorPhaseCAcPower encodes a GeneratorPhaseCAcPower struct to NMEA 2000 wire format
func EncodeGeneratorPhaseCAcPower(p *GeneratorPhaseCAcPower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorPhaseCAcPower")
}

// EncodeGeneratorPhaseCBasicAcQuantities encodes a GeneratorPhaseCBasicAcQuantities struct to NMEA 2000 wire format
func EncodeGeneratorPhaseCBasicAcQuantities(p *GeneratorPhaseCBasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorPhaseCBasicAcQuantities")
}

// EncodeGeneratorPhaseBAcReactivePower encodes a GeneratorPhaseBAcReactivePower struct to NMEA 2000 wire format
func EncodeGeneratorPhaseBAcReactivePower(p *GeneratorPhaseBAcReactivePower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorPhaseBAcReactivePower")
}

// EncodeGeneratorPhaseBAcPower encodes a GeneratorPhaseBAcPower struct to NMEA 2000 wire format
func EncodeGeneratorPhaseBAcPower(p *GeneratorPhaseBAcPower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorPhaseBAcPower")
}

// EncodeGeneratorPhaseBBasicAcQuantities encodes a GeneratorPhaseBBasicAcQuantities struct to NMEA 2000 wire format
func EncodeGeneratorPhaseBBasicAcQuantities(p *GeneratorPhaseBBasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorPhaseBBasicAcQuantities")
}

// EncodeGeneratorPhaseAAcReactivePower encodes a GeneratorPhaseAAcReactivePower struct to NMEA 2000 wire format
func EncodeGeneratorPhaseAAcReactivePower(p *GeneratorPhaseAAcReactivePower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorPhaseAAcReactivePower")
}

// EncodeGeneratorPhaseAAcPower encodes a GeneratorPhaseAAcPower struct to NMEA 2000 wire format
func EncodeGeneratorPhaseAAcPower(p *GeneratorPhaseAAcPower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorPhaseAAcPower")
}

// EncodeGeneratorPhaseABasicAcQuantities encodes a GeneratorPhaseABasicAcQuantities struct to NMEA 2000 wire format
func EncodeGeneratorPhaseABasicAcQuantities(p *GeneratorPhaseABasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorPhaseABasicAcQuantities")
}

// EncodeGeneratorTotalAcReactivePower encodes a GeneratorTotalAcReactivePower struct to NMEA 2000 wire format
func EncodeGeneratorTotalAcReactivePower(p *GeneratorTotalAcReactivePower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorTotalAcReactivePower")
}

// EncodeGeneratorTotalAcPower encodes a GeneratorTotalAcPower struct to NMEA 2000 wire format
func EncodeGeneratorTotalAcPower(p *GeneratorTotalAcPower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorTotalAcPower")
}

// EncodeGeneratorAverageBasicAcQuantities encodes a GeneratorAverageBasicAcQuantities struct to NMEA 2000 wire format
func EncodeGeneratorAverageBasicAcQuantities(p *GeneratorAverageBasicAcQuantities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GeneratorAverageBasicAcQuantities")
}

// EncodeIsoCommandedAddress encodes a IsoCommandedAddress struct to NMEA 2000 wire format
func EncodeIsoCommandedAddress(p *IsoCommandedAddress, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for IsoCommandedAddress")
}

// EncodeMaretronProprietaryDcBreakerCurrent encodes a MaretronProprietaryDcBreakerCurrent struct to NMEA 2000 wire format
func EncodeMaretronProprietaryDcBreakerCurrent(p *MaretronProprietaryDcBreakerCurrent, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for MaretronProprietaryDcBreakerCurrent")
}

// EncodeAirmarBootStateAcknowledgment encodes a AirmarBootStateAcknowledgment struct to NMEA 2000 wire format
func EncodeAirmarBootStateAcknowledgment(p *AirmarBootStateAcknowledgment, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarBootStateAcknowledgment")
}

// EncodeLowranceTemperature encodes a LowranceTemperature struct to NMEA 2000 wire format
func EncodeLowranceTemperature(p *LowranceTemperature, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for LowranceTemperature")
}

// EncodeAirmarBootStateRequest encodes a AirmarBootStateRequest struct to NMEA 2000 wire format
func EncodeAirmarBootStateRequest(p *AirmarBootStateRequest, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarBootStateRequest")
}

// EncodeAirmarAccessLevel encodes a AirmarAccessLevel struct to NMEA 2000 wire format
func EncodeAirmarAccessLevel(p *AirmarAccessLevel, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarAccessLevel")
}

// EncodeSimnetDeviceStatus encodes a SimnetDeviceStatus struct to NMEA 2000 wire format
func EncodeSimnetDeviceStatus(p *SimnetDeviceStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for SimnetDeviceStatus")
}

// EncodeSimnetDeviceStatusRequest encodes a SimnetDeviceStatusRequest struct to NMEA 2000 wire format
func EncodeSimnetDeviceStatusRequest(p *SimnetDeviceStatusRequest, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for SimnetDeviceStatusRequest")
}

// EncodeSimnetPilotMode encodes a SimnetPilotMode struct to NMEA 2000 wire format
func EncodeSimnetPilotMode(p *SimnetPilotMode, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for SimnetPilotMode")
}

// EncodeSimnetDeviceModeRequest encodes a SimnetDeviceModeRequest struct to NMEA 2000 wire format
func EncodeSimnetDeviceModeRequest(p *SimnetDeviceModeRequest, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for SimnetDeviceModeRequest")
}

// EncodeSeatalkPilotLockedHeading encodes a SeatalkPilotLockedHeading struct to NMEA 2000 wire format
func EncodeSeatalkPilotLockedHeading(p *SeatalkPilotLockedHeading, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for SeatalkPilotLockedHeading")
}

// EncodeSeatalkSilenceAlarm encodes a SeatalkSilenceAlarm struct to NMEA 2000 wire format
func EncodeSeatalkSilenceAlarm(p *SeatalkSilenceAlarm, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for SeatalkSilenceAlarm")
}

// EncodeAirmarSpeedPulseCount encodes a AirmarSpeedPulseCount struct to NMEA 2000 wire format
func EncodeAirmarSpeedPulseCount(p *AirmarSpeedPulseCount, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarSpeedPulseCount")
}

// EncodeNmeaRequestGroupFunction encodes a NmeaRequestGroupFunction struct to NMEA 2000 wire format
func EncodeNmeaRequestGroupFunction(p *NmeaRequestGroupFunction, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for NmeaRequestGroupFunction")
}
// EncodeNmeaRequestGroupFunctionPartial returns an error for partial variants
func EncodeNmeaRequestGroupFunctionPartial(p *NmeaRequestGroupFunctionPartial, stream *DataStream) (*MessageInfo, error) {
	return nil, fmt.Errorf("cannot encode partial variant of NmeaRequestGroupFunction - use NmeaRequestGroupFunction for encoding")
}

// EncodeNmeaCommandGroupFunction encodes a NmeaCommandGroupFunction struct to NMEA 2000 wire format
func EncodeNmeaCommandGroupFunction(p *NmeaCommandGroupFunction, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for NmeaCommandGroupFunction")
}
// EncodeNmeaCommandGroupFunctionPartial returns an error for partial variants
func EncodeNmeaCommandGroupFunctionPartial(p *NmeaCommandGroupFunctionPartial, stream *DataStream) (*MessageInfo, error) {
	return nil, fmt.Errorf("cannot encode partial variant of NmeaCommandGroupFunction - use NmeaCommandGroupFunction for encoding")
}

// EncodeNmeaAcknowledgeGroupFunction encodes a NmeaAcknowledgeGroupFunction struct to NMEA 2000 wire format
func EncodeNmeaAcknowledgeGroupFunction(p *NmeaAcknowledgeGroupFunction, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for NmeaAcknowledgeGroupFunction")
}
// EncodeNmeaAcknowledgeGroupFunctionPartial returns an error for partial variants
func EncodeNmeaAcknowledgeGroupFunctionPartial(p *NmeaAcknowledgeGroupFunctionPartial, stream *DataStream) (*MessageInfo, error) {
	return nil, fmt.Errorf("cannot encode partial variant of NmeaAcknowledgeGroupFunction - use NmeaAcknowledgeGroupFunction for encoding")
}

// EncodeNmeaReadFieldsReplyGroupFunction encodes a NmeaReadFieldsReplyGroupFunction struct to NMEA 2000 wire format
func EncodeNmeaReadFieldsReplyGroupFunction(p *NmeaReadFieldsReplyGroupFunction, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for NmeaReadFieldsReplyGroupFunction")
}
// EncodeNmeaReadFieldsReplyGroupFunctionPartial returns an error for partial variants
func EncodeNmeaReadFieldsReplyGroupFunctionPartial(p *NmeaReadFieldsReplyGroupFunctionPartial, stream *DataStream) (*MessageInfo, error) {
	return nil, fmt.Errorf("cannot encode partial variant of NmeaReadFieldsReplyGroupFunction - use NmeaReadFieldsReplyGroupFunction for encoding")
}

// EncodeNmeaWriteFieldsGroupFunction encodes a NmeaWriteFieldsGroupFunction struct to NMEA 2000 wire format
func EncodeNmeaWriteFieldsGroupFunction(p *NmeaWriteFieldsGroupFunction, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for NmeaWriteFieldsGroupFunction")
}
// EncodeNmeaWriteFieldsGroupFunctionPartial returns an error for partial variants
func EncodeNmeaWriteFieldsGroupFunctionPartial(p *NmeaWriteFieldsGroupFunctionPartial, stream *DataStream) (*MessageInfo, error) {
	return nil, fmt.Errorf("cannot encode partial variant of NmeaWriteFieldsGroupFunction - use NmeaWriteFieldsGroupFunction for encoding")
}

// EncodeNmeaWriteFieldsReplyGroupFunction encodes a NmeaWriteFieldsReplyGroupFunction struct to NMEA 2000 wire format
func EncodeNmeaWriteFieldsReplyGroupFunction(p *NmeaWriteFieldsReplyGroupFunction, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for NmeaWriteFieldsReplyGroupFunction")
}
// EncodeNmeaWriteFieldsReplyGroupFunctionPartial returns an error for partial variants
func EncodeNmeaWriteFieldsReplyGroupFunctionPartial(p *NmeaWriteFieldsReplyGroupFunctionPartial, stream *DataStream) (*MessageInfo, error) {
	return nil, fmt.Errorf("cannot encode partial variant of NmeaWriteFieldsReplyGroupFunction - use NmeaWriteFieldsReplyGroupFunction for encoding")
}

// EncodePgnListTransmitAndReceive encodes a PgnListTransmitAndReceive struct to NMEA 2000 wire format
func EncodePgnListTransmitAndReceive(p *PgnListTransmitAndReceive, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for PgnListTransmitAndReceive")
}

// EncodeFusionMediaControl encodes a FusionMediaControl struct to NMEA 2000 wire format
func EncodeFusionMediaControl(p *FusionMediaControl, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionMediaControl")
}

// EncodeFusionSiriusControl encodes a FusionSiriusControl struct to NMEA 2000 wire format
func EncodeFusionSiriusControl(p *FusionSiriusControl, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSiriusControl")
}

// EncodeFusionRequestStatus encodes a FusionRequestStatus struct to NMEA 2000 wire format
func EncodeFusionRequestStatus(p *FusionRequestStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionRequestStatus")
}

// EncodeFusionSetSource encodes a FusionSetSource struct to NMEA 2000 wire format
func EncodeFusionSetSource(p *FusionSetSource, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSetSource")
}

// EncodeFusionSetMute encodes a FusionSetMute struct to NMEA 2000 wire format
func EncodeFusionSetMute(p *FusionSetMute, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSetMute")
}

// EncodeFusionSetZoneVolume encodes a FusionSetZoneVolume struct to NMEA 2000 wire format
func EncodeFusionSetZoneVolume(p *FusionSetZoneVolume, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSetZoneVolume")
}

// EncodeFusionSetAllVolumes encodes a FusionSetAllVolumes struct to NMEA 2000 wire format
func EncodeFusionSetAllVolumes(p *FusionSetAllVolumes, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSetAllVolumes")
}

// EncodeAirmarAttitudeOffset encodes a AirmarAttitudeOffset struct to NMEA 2000 wire format
func EncodeAirmarAttitudeOffset(p *AirmarAttitudeOffset, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarAttitudeOffset")
}

// EncodeAirmarSimulateMode encodes a AirmarSimulateMode struct to NMEA 2000 wire format
func EncodeAirmarSimulateMode(p *AirmarSimulateMode, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarSimulateMode")
}

// EncodeAirmarCalibrateDepth encodes a AirmarCalibrateDepth struct to NMEA 2000 wire format
func EncodeAirmarCalibrateDepth(p *AirmarCalibrateDepth, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarCalibrateDepth")
}

// EncodeAirmarCalibrateSpeed encodes a AirmarCalibrateSpeed struct to NMEA 2000 wire format
func EncodeAirmarCalibrateSpeed(p *AirmarCalibrateSpeed, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarCalibrateSpeed")
}

// EncodeAirmarCalibrateTemperature encodes a AirmarCalibrateTemperature struct to NMEA 2000 wire format
func EncodeAirmarCalibrateTemperature(p *AirmarCalibrateTemperature, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarCalibrateTemperature")
}

// EncodeAirmarSpeedFilterNone encodes a AirmarSpeedFilterNone struct to NMEA 2000 wire format
func EncodeAirmarSpeedFilterNone(p *AirmarSpeedFilterNone, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarSpeedFilterNone")
}

// EncodeAirmarSpeedFilterIir encodes a AirmarSpeedFilterIir struct to NMEA 2000 wire format
func EncodeAirmarSpeedFilterIir(p *AirmarSpeedFilterIir, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarSpeedFilterIir")
}

// EncodeAirmarTemperatureFilterNone encodes a AirmarTemperatureFilterNone struct to NMEA 2000 wire format
func EncodeAirmarTemperatureFilterNone(p *AirmarTemperatureFilterNone, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarTemperatureFilterNone")
}

// EncodeAirmarTemperatureFilterIir encodes a AirmarTemperatureFilterIir struct to NMEA 2000 wire format
func EncodeAirmarTemperatureFilterIir(p *AirmarTemperatureFilterIir, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarTemperatureFilterIir")
}

// EncodeAirmarNmea2000Options encodes a AirmarNmea2000Options struct to NMEA 2000 wire format
func EncodeAirmarNmea2000Options(p *AirmarNmea2000Options, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AirmarNmea2000Options")
}

// EncodeMaretronDeviationCalibrationResponse encodes a MaretronDeviationCalibrationResponse struct to NMEA 2000 wire format
func EncodeMaretronDeviationCalibrationResponse(p *MaretronDeviationCalibrationResponse, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for MaretronDeviationCalibrationResponse")
}

// EncodeMaretronSlaveResponse encodes a MaretronSlaveResponse struct to NMEA 2000 wire format
func EncodeMaretronSlaveResponse(p *MaretronSlaveResponse, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for MaretronSlaveResponse")
}

// EncodeAlert encodes a Alert struct to NMEA 2000 wire format
func EncodeAlert(p *Alert, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Alert")
}

// EncodeAlertResponse encodes a AlertResponse struct to NMEA 2000 wire format
func EncodeAlertResponse(p *AlertResponse, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AlertResponse")
}

// EncodeAlertText encodes a AlertText struct to NMEA 2000 wire format
func EncodeAlertText(p *AlertText, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AlertText")
}

// EncodeSystemTime encodes a SystemTime struct to NMEA 2000 wire format
func EncodeSystemTime(p *SystemTime, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for SystemTime")
}

// EncodeHeartbeat encodes a Heartbeat struct to NMEA 2000 wire format
func EncodeHeartbeat(p *Heartbeat, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Heartbeat")
}

// EncodeProductInformation encodes a ProductInformation struct to NMEA 2000 wire format
func EncodeProductInformation(p *ProductInformation, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for ProductInformation")
}

// EncodeConfigurationInformation encodes a ConfigurationInformation struct to NMEA 2000 wire format
func EncodeConfigurationInformation(p *ConfigurationInformation, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for ConfigurationInformation")
}

// EncodeManOverboardNotification encodes a ManOverboardNotification struct to NMEA 2000 wire format
func EncodeManOverboardNotification(p *ManOverboardNotification, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for ManOverboardNotification")
}

// EncodeHeadingTrackControl encodes a HeadingTrackControl struct to NMEA 2000 wire format
func EncodeHeadingTrackControl(p *HeadingTrackControl, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for HeadingTrackControl")
}

// EncodeRudder encodes a Rudder struct to NMEA 2000 wire format
func EncodeRudder(p *Rudder, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Rudder")
}

// EncodeVesselHeading encodes a VesselHeading struct to NMEA 2000 wire format
func EncodeVesselHeading(p *VesselHeading, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for VesselHeading")
}

// EncodeRateOfTurn encodes a RateOfTurn struct to NMEA 2000 wire format
func EncodeRateOfTurn(p *RateOfTurn, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RateOfTurn")
}

// EncodeAttitude encodes a Attitude struct to NMEA 2000 wire format
func EncodeAttitude(p *Attitude, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Attitude")
}

// EncodeMagneticVariation encodes a MagneticVariation struct to NMEA 2000 wire format
func EncodeMagneticVariation(p *MagneticVariation, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for MagneticVariation")
}

// EncodeEngineParametersRapidUpdate encodes a EngineParametersRapidUpdate struct to NMEA 2000 wire format
func EncodeEngineParametersRapidUpdate(p *EngineParametersRapidUpdate, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for EngineParametersRapidUpdate")
}

// EncodeEngineParametersDynamic encodes a EngineParametersDynamic struct to NMEA 2000 wire format
func EncodeEngineParametersDynamic(p *EngineParametersDynamic, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for EngineParametersDynamic")
}

// EncodeTransmissionParametersDynamic encodes a TransmissionParametersDynamic struct to NMEA 2000 wire format
func EncodeTransmissionParametersDynamic(p *TransmissionParametersDynamic, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for TransmissionParametersDynamic")
}

// EncodeTripParametersVessel encodes a TripParametersVessel struct to NMEA 2000 wire format
func EncodeTripParametersVessel(p *TripParametersVessel, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for TripParametersVessel")
}

// EncodeTripParametersEngine encodes a TripParametersEngine struct to NMEA 2000 wire format
func EncodeTripParametersEngine(p *TripParametersEngine, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for TripParametersEngine")
}

// EncodeEngineParametersStatic encodes a EngineParametersStatic struct to NMEA 2000 wire format
func EncodeEngineParametersStatic(p *EngineParametersStatic, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for EngineParametersStatic")
}

// EncodeLoadControllerConnectionStateControl encodes a LoadControllerConnectionStateControl struct to NMEA 2000 wire format
func EncodeLoadControllerConnectionStateControl(p *LoadControllerConnectionStateControl, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for LoadControllerConnectionStateControl")
}

// EncodeBinarySwitchBankStatus encodes a BinarySwitchBankStatus struct to NMEA 2000 wire format
func EncodeBinarySwitchBankStatus(p *BinarySwitchBankStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for BinarySwitchBankStatus")
}

// EncodeSwitchBankControl encodes a SwitchBankControl struct to NMEA 2000 wire format
func EncodeSwitchBankControl(p *SwitchBankControl, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for SwitchBankControl")
}

// EncodeAcInputStatus encodes a AcInputStatus struct to NMEA 2000 wire format
func EncodeAcInputStatus(p *AcInputStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AcInputStatus")
}

// EncodeAcOutputStatus encodes a AcOutputStatus struct to NMEA 2000 wire format
func EncodeAcOutputStatus(p *AcOutputStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AcOutputStatus")
}

// EncodeFluidLevel encodes a FluidLevel struct to NMEA 2000 wire format
func EncodeFluidLevel(p *FluidLevel, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FluidLevel")
}

// EncodeDcDetailedStatus encodes a DcDetailedStatus struct to NMEA 2000 wire format
func EncodeDcDetailedStatus(p *DcDetailedStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for DcDetailedStatus")
}

// EncodeChargerStatus encodes a ChargerStatus struct to NMEA 2000 wire format
func EncodeChargerStatus(p *ChargerStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for ChargerStatus")
}

// EncodeBatteryStatus encodes a BatteryStatus struct to NMEA 2000 wire format
func EncodeBatteryStatus(p *BatteryStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for BatteryStatus")
}

// EncodeInverterStatus encodes a InverterStatus struct to NMEA 2000 wire format
func EncodeInverterStatus(p *InverterStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for InverterStatus")
}

// EncodeAcPowerCurrentPhaseA encodes a AcPowerCurrentPhaseA struct to NMEA 2000 wire format
func EncodeAcPowerCurrentPhaseA(p *AcPowerCurrentPhaseA, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AcPowerCurrentPhaseA")
}

// EncodeAcPowerCurrentPhaseB encodes a AcPowerCurrentPhaseB struct to NMEA 2000 wire format
func EncodeAcPowerCurrentPhaseB(p *AcPowerCurrentPhaseB, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AcPowerCurrentPhaseB")
}

// EncodeAcPowerCurrentPhaseC encodes a AcPowerCurrentPhaseC struct to NMEA 2000 wire format
func EncodeAcPowerCurrentPhaseC(p *AcPowerCurrentPhaseC, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AcPowerCurrentPhaseC")
}

// EncodeAcVoltageFrequencyPhaseA encodes a AcVoltageFrequencyPhaseA struct to NMEA 2000 wire format
func EncodeAcVoltageFrequencyPhaseA(p *AcVoltageFrequencyPhaseA, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AcVoltageFrequencyPhaseA")
}

// EncodeAcVoltageFrequencyPhaseB encodes a AcVoltageFrequencyPhaseB struct to NMEA 2000 wire format
func EncodeAcVoltageFrequencyPhaseB(p *AcVoltageFrequencyPhaseB, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AcVoltageFrequencyPhaseB")
}

// EncodeAcVoltageFrequencyPhaseC encodes a AcVoltageFrequencyPhaseC struct to NMEA 2000 wire format
func EncodeAcVoltageFrequencyPhaseC(p *AcVoltageFrequencyPhaseC, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AcVoltageFrequencyPhaseC")
}

// EncodeConverterStatus encodes a ConverterStatus struct to NMEA 2000 wire format
func EncodeConverterStatus(p *ConverterStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for ConverterStatus")
}

// EncodeDcVoltageCurrent encodes a DcVoltageCurrent struct to NMEA 2000 wire format
func EncodeDcVoltageCurrent(p *DcVoltageCurrent, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for DcVoltageCurrent")
}

// EncodeLeewayAngle encodes a LeewayAngle struct to NMEA 2000 wire format
func EncodeLeewayAngle(p *LeewayAngle, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for LeewayAngle")
}

// EncodeThrusterControlStatus encodes a ThrusterControlStatus struct to NMEA 2000 wire format
func EncodeThrusterControlStatus(p *ThrusterControlStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for ThrusterControlStatus")
}

// EncodeThrusterInformation encodes a ThrusterInformation struct to NMEA 2000 wire format
func EncodeThrusterInformation(p *ThrusterInformation, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for ThrusterInformation")
}

// EncodeThrusterMotorStatus encodes a ThrusterMotorStatus struct to NMEA 2000 wire format
func EncodeThrusterMotorStatus(p *ThrusterMotorStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for ThrusterMotorStatus")
}

// EncodeSpeed encodes a Speed struct to NMEA 2000 wire format
func EncodeSpeed(p *Speed, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Speed")
}

// EncodeWaterDepth encodes a WaterDepth struct to NMEA 2000 wire format
func EncodeWaterDepth(p *WaterDepth, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for WaterDepth")
}

// EncodeDistanceLog encodes a DistanceLog struct to NMEA 2000 wire format
func EncodeDistanceLog(p *DistanceLog, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for DistanceLog")
}

// EncodeWindlassControlStatus encodes a WindlassControlStatus struct to NMEA 2000 wire format
func EncodeWindlassControlStatus(p *WindlassControlStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for WindlassControlStatus")
}

// EncodeAnchorWindlassOperatingStatus encodes a AnchorWindlassOperatingStatus struct to NMEA 2000 wire format
func EncodeAnchorWindlassOperatingStatus(p *AnchorWindlassOperatingStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AnchorWindlassOperatingStatus")
}

// EncodeAnchorWindlassMonitoringStatus encodes a AnchorWindlassMonitoringStatus struct to NMEA 2000 wire format
func EncodeAnchorWindlassMonitoringStatus(p *AnchorWindlassMonitoringStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AnchorWindlassMonitoringStatus")
}

// EncodePositionRapidUpdate encodes a PositionRapidUpdate struct to NMEA 2000 wire format
func EncodePositionRapidUpdate(p *PositionRapidUpdate, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for PositionRapidUpdate")
}

// EncodeCogSogRapidUpdate encodes a CogSogRapidUpdate struct to NMEA 2000 wire format
func EncodeCogSogRapidUpdate(p *CogSogRapidUpdate, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for CogSogRapidUpdate")
}

// EncodeGnssPositionData encodes a GnssPositionData struct to NMEA 2000 wire format
func EncodeGnssPositionData(p *GnssPositionData, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GnssPositionData")
}

// EncodeTimeDate encodes a TimeDate struct to NMEA 2000 wire format
func EncodeTimeDate(p *TimeDate, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for TimeDate")
}

// EncodeAisClassAPositionReport encodes a AisClassAPositionReport struct to NMEA 2000 wire format
func EncodeAisClassAPositionReport(p *AisClassAPositionReport, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AisClassAPositionReport")
}

// EncodeAisClassBPositionReport encodes a AisClassBPositionReport struct to NMEA 2000 wire format
func EncodeAisClassBPositionReport(p *AisClassBPositionReport, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AisClassBPositionReport")
}

// EncodeAisAidsToNavigationAtonReport encodes a AisAidsToNavigationAtonReport struct to NMEA 2000 wire format
func EncodeAisAidsToNavigationAtonReport(p *AisAidsToNavigationAtonReport, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AisAidsToNavigationAtonReport")
}

// EncodeDatum encodes a Datum struct to NMEA 2000 wire format
func EncodeDatum(p *Datum, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Datum")
}

// EncodeUserDatum encodes a UserDatum struct to NMEA 2000 wire format
func EncodeUserDatum(p *UserDatum, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for UserDatum")
}

// EncodeCrossTrackError encodes a CrossTrackError struct to NMEA 2000 wire format
func EncodeCrossTrackError(p *CrossTrackError, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for CrossTrackError")
}

// EncodeNavigationData encodes a NavigationData struct to NMEA 2000 wire format
func EncodeNavigationData(p *NavigationData, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for NavigationData")
}

// EncodeNavigationRouteWpInformation encodes a NavigationRouteWpInformation struct to NMEA 2000 wire format
func EncodeNavigationRouteWpInformation(p *NavigationRouteWpInformation, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for NavigationRouteWpInformation")
}

// EncodeGnssDops encodes a GnssDops struct to NMEA 2000 wire format
func EncodeGnssDops(p *GnssDops, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GnssDops")
}

// EncodeGnssSatsInView encodes a GnssSatsInView struct to NMEA 2000 wire format
func EncodeGnssSatsInView(p *GnssSatsInView, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GnssSatsInView")
}

// EncodeGnssRaimSettings encodes a GnssRaimSettings struct to NMEA 2000 wire format
func EncodeGnssRaimSettings(p *GnssRaimSettings, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GnssRaimSettings")
}

// EncodeGnssPseudorangeErrorStatistics encodes a GnssPseudorangeErrorStatistics struct to NMEA 2000 wire format
func EncodeGnssPseudorangeErrorStatistics(p *GnssPseudorangeErrorStatistics, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GnssPseudorangeErrorStatistics")
}

// EncodeDgnssCorrections encodes a DgnssCorrections struct to NMEA 2000 wire format
func EncodeDgnssCorrections(p *DgnssCorrections, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for DgnssCorrections")
}

// EncodeGnssDifferentialCorrectionReceiverInterface encodes a GnssDifferentialCorrectionReceiverInterface struct to NMEA 2000 wire format
func EncodeGnssDifferentialCorrectionReceiverInterface(p *GnssDifferentialCorrectionReceiverInterface, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GnssDifferentialCorrectionReceiverInterface")
}

// EncodeGnssDifferentialCorrectionReceiverSignal encodes a GnssDifferentialCorrectionReceiverSignal struct to NMEA 2000 wire format
func EncodeGnssDifferentialCorrectionReceiverSignal(p *GnssDifferentialCorrectionReceiverSignal, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GnssDifferentialCorrectionReceiverSignal")
}

// EncodeGlonassAlmanacData encodes a GlonassAlmanacData struct to NMEA 2000 wire format
func EncodeGlonassAlmanacData(p *GlonassAlmanacData, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for GlonassAlmanacData")
}

// EncodeAisClassAStaticAndVoyageRelatedData encodes a AisClassAStaticAndVoyageRelatedData struct to NMEA 2000 wire format
func EncodeAisClassAStaticAndVoyageRelatedData(p *AisClassAStaticAndVoyageRelatedData, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AisClassAStaticAndVoyageRelatedData")
}

// EncodeAisAddressedBinaryMessage encodes a AisAddressedBinaryMessage struct to NMEA 2000 wire format
func EncodeAisAddressedBinaryMessage(p *AisAddressedBinaryMessage, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AisAddressedBinaryMessage")
}

// EncodeAisAcknowledge encodes a AisAcknowledge struct to NMEA 2000 wire format
func EncodeAisAcknowledge(p *AisAcknowledge, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AisAcknowledge")
}

// EncodeAisBinaryBroadcastMessage encodes a AisBinaryBroadcastMessage struct to NMEA 2000 wire format
func EncodeAisBinaryBroadcastMessage(p *AisBinaryBroadcastMessage, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AisBinaryBroadcastMessage")
}

// EncodeRadioFrequencyModePower encodes a RadioFrequencyModePower struct to NMEA 2000 wire format
func EncodeRadioFrequencyModePower(p *RadioFrequencyModePower, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RadioFrequencyModePower")
}

// EncodeAisClassBStaticDataMsg24PartA encodes a AisClassBStaticDataMsg24PartA struct to NMEA 2000 wire format
func EncodeAisClassBStaticDataMsg24PartA(p *AisClassBStaticDataMsg24PartA, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AisClassBStaticDataMsg24PartA")
}

// EncodeAisClassBStaticDataMsg24PartB encodes a AisClassBStaticDataMsg24PartB struct to NMEA 2000 wire format
func EncodeAisClassBStaticDataMsg24PartB(p *AisClassBStaticDataMsg24PartB, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for AisClassBStaticDataMsg24PartB")
}

// EncodeRouteAndWpServiceDatabaseList encodes a RouteAndWpServiceDatabaseList struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceDatabaseList(p *RouteAndWpServiceDatabaseList, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceDatabaseList")
}

// EncodeRouteAndWpServiceRouteList encodes a RouteAndWpServiceRouteList struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceRouteList(p *RouteAndWpServiceRouteList, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceRouteList")
}

// EncodeRouteAndWpServiceRouteWpListAttributes encodes a RouteAndWpServiceRouteWpListAttributes struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceRouteWpListAttributes(p *RouteAndWpServiceRouteWpListAttributes, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceRouteWpListAttributes")
}

// EncodeRouteAndWpServiceRouteWpNamePosition encodes a RouteAndWpServiceRouteWpNamePosition struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceRouteWpNamePosition(p *RouteAndWpServiceRouteWpNamePosition, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceRouteWpNamePosition")
}

// EncodeRouteAndWpServiceRouteWpName encodes a RouteAndWpServiceRouteWpName struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceRouteWpName(p *RouteAndWpServiceRouteWpName, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceRouteWpName")
}

// EncodeRouteAndWpServiceXteLimitNavigationMethod encodes a RouteAndWpServiceXteLimitNavigationMethod struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceXteLimitNavigationMethod(p *RouteAndWpServiceXteLimitNavigationMethod, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceXteLimitNavigationMethod")
}

// EncodeRouteAndWpServiceWpComment encodes a RouteAndWpServiceWpComment struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceWpComment(p *RouteAndWpServiceWpComment, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceWpComment")
}

// EncodeRouteAndWpServiceRouteComment encodes a RouteAndWpServiceRouteComment struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceRouteComment(p *RouteAndWpServiceRouteComment, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceRouteComment")
}

// EncodeRouteAndWpServiceDatabaseComment encodes a RouteAndWpServiceDatabaseComment struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceDatabaseComment(p *RouteAndWpServiceDatabaseComment, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceDatabaseComment")
}

// EncodeRouteAndWpServiceRadiusOfTurn encodes a RouteAndWpServiceRadiusOfTurn struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceRadiusOfTurn(p *RouteAndWpServiceRadiusOfTurn, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceRadiusOfTurn")
}

// EncodeRouteAndWpServiceWpListWpNamePosition encodes a RouteAndWpServiceWpListWpNamePosition struct to NMEA 2000 wire format
func EncodeRouteAndWpServiceWpListWpNamePosition(p *RouteAndWpServiceWpListWpNamePosition, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for RouteAndWpServiceWpListWpNamePosition")
}

// EncodeWindData encodes a WindData struct to NMEA 2000 wire format
func EncodeWindData(p *WindData, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for WindData")
}

// EncodeEnvironmentalParametersObsolete encodes a EnvironmentalParametersObsolete struct to NMEA 2000 wire format
func EncodeEnvironmentalParametersObsolete(p *EnvironmentalParametersObsolete, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for EnvironmentalParametersObsolete")
}

// EncodeEnvironmentalParameters encodes a EnvironmentalParameters struct to NMEA 2000 wire format
func EncodeEnvironmentalParameters(p *EnvironmentalParameters, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for EnvironmentalParameters")
}

// EncodeTemperature encodes a Temperature struct to NMEA 2000 wire format
func EncodeTemperature(p *Temperature, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Temperature")
}

// EncodeHumidity encodes a Humidity struct to NMEA 2000 wire format
func EncodeHumidity(p *Humidity, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for Humidity")
}

// EncodeActualPressure encodes a ActualPressure struct to NMEA 2000 wire format
func EncodeActualPressure(p *ActualPressure, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for ActualPressure")
}

// EncodeSetPressure encodes a SetPressure struct to NMEA 2000 wire format
func EncodeSetPressure(p *SetPressure, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for SetPressure")
}

// EncodeTemperatureExtendedRange encodes a TemperatureExtendedRange struct to NMEA 2000 wire format
func EncodeTemperatureExtendedRange(p *TemperatureExtendedRange, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for TemperatureExtendedRange")
}

// EncodeTideStationData encodes a TideStationData struct to NMEA 2000 wire format
func EncodeTideStationData(p *TideStationData, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for TideStationData")
}

// EncodeWatermakerInputSettingAndStatus encodes a WatermakerInputSettingAndStatus struct to NMEA 2000 wire format
func EncodeWatermakerInputSettingAndStatus(p *WatermakerInputSettingAndStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for WatermakerInputSettingAndStatus")
}

// EncodeVesselSpeedComponents encodes a VesselSpeedComponents struct to NMEA 2000 wire format
func EncodeVesselSpeedComponents(p *VesselSpeedComponents, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for VesselSpeedComponents")
}

// EncodeSonichubVolume encodes a SonichubVolume struct to NMEA 2000 wire format
func EncodeSonichubVolume(p *SonichubVolume, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for SonichubVolume")
}

// EncodeFusionVersions encodes a FusionVersions struct to NMEA 2000 wire format
func EncodeFusionVersions(p *FusionVersions, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionVersions")
}

// EncodeFusionSource encodes a FusionSource struct to NMEA 2000 wire format
func EncodeFusionSource(p *FusionSource, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSource")
}

// EncodeFusionSourceCount encodes a FusionSourceCount struct to NMEA 2000 wire format
func EncodeFusionSourceCount(p *FusionSourceCount, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSourceCount")
}

// EncodeFusionMedia encodes a FusionMedia struct to NMEA 2000 wire format
func EncodeFusionMedia(p *FusionMedia, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionMedia")
}

// EncodeFusionTrackName encodes a FusionTrackName struct to NMEA 2000 wire format
func EncodeFusionTrackName(p *FusionTrackName, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionTrackName")
}

// EncodeFusionArtistName encodes a FusionArtistName struct to NMEA 2000 wire format
func EncodeFusionArtistName(p *FusionArtistName, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionArtistName")
}

// EncodeFusionAlbumName encodes a FusionAlbumName struct to NMEA 2000 wire format
func EncodeFusionAlbumName(p *FusionAlbumName, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionAlbumName")
}

// EncodeFusionDeviceName encodes a FusionDeviceName struct to NMEA 2000 wire format
func EncodeFusionDeviceName(p *FusionDeviceName, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionDeviceName")
}

// EncodeFusionZoneName encodes a FusionZoneName struct to NMEA 2000 wire format
func EncodeFusionZoneName(p *FusionZoneName, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionZoneName")
}

// EncodeFusionTrackPosition encodes a FusionTrackPosition struct to NMEA 2000 wire format
func EncodeFusionTrackPosition(p *FusionTrackPosition, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionTrackPosition")
}

// EncodeFusionTuner encodes a FusionTuner struct to NMEA 2000 wire format
func EncodeFusionTuner(p *FusionTuner, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionTuner")
}

// EncodeFusionMarineTuner encodes a FusionMarineTuner struct to NMEA 2000 wire format
func EncodeFusionMarineTuner(p *FusionMarineTuner, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionMarineTuner")
}

// EncodeFusionMarineSquelch encodes a FusionMarineSquelch struct to NMEA 2000 wire format
func EncodeFusionMarineSquelch(p *FusionMarineSquelch, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionMarineSquelch")
}

// EncodeFusionMarineScanMode encodes a FusionMarineScanMode struct to NMEA 2000 wire format
func EncodeFusionMarineScanMode(p *FusionMarineScanMode, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionMarineScanMode")
}

// EncodeFusionMenuItem encodes a FusionMenuItem struct to NMEA 2000 wire format
func EncodeFusionMenuItem(p *FusionMenuItem, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionMenuItem")
}

// EncodeFusionAuxGain encodes a FusionAuxGain struct to NMEA 2000 wire format
func EncodeFusionAuxGain(p *FusionAuxGain, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionAuxGain")
}

// EncodeFusionUsbRepeatStatus encodes a FusionUsbRepeatStatus struct to NMEA 2000 wire format
func EncodeFusionUsbRepeatStatus(p *FusionUsbRepeatStatus, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionUsbRepeatStatus")
}

// EncodeFusionSetting encodes a FusionSetting struct to NMEA 2000 wire format
func EncodeFusionSetting(p *FusionSetting, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSetting")
}

// EncodeFusionSettings encodes a FusionSettings struct to NMEA 2000 wire format
func EncodeFusionSettings(p *FusionSettings, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSettings")
}

// EncodeFusionMute encodes a FusionMute struct to NMEA 2000 wire format
func EncodeFusionMute(p *FusionMute, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionMute")
}

// EncodeFusionBalance encodes a FusionBalance struct to NMEA 2000 wire format
func EncodeFusionBalance(p *FusionBalance, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionBalance")
}

// EncodeFusionLowPassFilter encodes a FusionLowPassFilter struct to NMEA 2000 wire format
func EncodeFusionLowPassFilter(p *FusionLowPassFilter, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionLowPassFilter")
}

// EncodeFusionSublevels encodes a FusionSublevels struct to NMEA 2000 wire format
func EncodeFusionSublevels(p *FusionSublevels, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSublevels")
}

// EncodeFusionEq encodes a FusionEq struct to NMEA 2000 wire format
func EncodeFusionEq(p *FusionEq, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionEq")
}

// EncodeFusionVolumeLimits encodes a FusionVolumeLimits struct to NMEA 2000 wire format
func EncodeFusionVolumeLimits(p *FusionVolumeLimits, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionVolumeLimits")
}

// EncodeFusionVolumes encodes a FusionVolumes struct to NMEA 2000 wire format
func EncodeFusionVolumes(p *FusionVolumes, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionVolumes")
}

// EncodeFusionCapabilities encodes a FusionCapabilities struct to NMEA 2000 wire format
func EncodeFusionCapabilities(p *FusionCapabilities, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionCapabilities")
}

// EncodeFusionLineLevelControl encodes a FusionLineLevelControl struct to NMEA 2000 wire format
func EncodeFusionLineLevelControl(p *FusionLineLevelControl, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionLineLevelControl")
}

// EncodeFusionPowerState encodes a FusionPowerState struct to NMEA 2000 wire format
func EncodeFusionPowerState(p *FusionPowerState, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionPowerState")
}

// EncodeFusionSiriusxm encodes a FusionSiriusxm struct to NMEA 2000 wire format
func EncodeFusionSiriusxm(p *FusionSiriusxm, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSiriusxm")
}

// EncodeFusionSiriusxmChannel encodes a FusionSiriusxmChannel struct to NMEA 2000 wire format
func EncodeFusionSiriusxmChannel(p *FusionSiriusxmChannel, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSiriusxmChannel")
}

// EncodeFusionSiriusxmTitle encodes a FusionSiriusxmTitle struct to NMEA 2000 wire format
func EncodeFusionSiriusxmTitle(p *FusionSiriusxmTitle, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSiriusxmTitle")
}

// EncodeFusionSiriusxmArtist encodes a FusionSiriusxmArtist struct to NMEA 2000 wire format
func EncodeFusionSiriusxmArtist(p *FusionSiriusxmArtist, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSiriusxmArtist")
}

// EncodeFusionSiriusxmContentInfo encodes a FusionSiriusxmContentInfo struct to NMEA 2000 wire format
func EncodeFusionSiriusxmContentInfo(p *FusionSiriusxmContentInfo, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSiriusxmContentInfo")
}

// EncodeFusionSiriusxmCategory encodes a FusionSiriusxmCategory struct to NMEA 2000 wire format
func EncodeFusionSiriusxmCategory(p *FusionSiriusxmCategory, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSiriusxmCategory")
}

// EncodeFusionSiriusxmSignal encodes a FusionSiriusxmSignal struct to NMEA 2000 wire format
func EncodeFusionSiriusxmSignal(p *FusionSiriusxmSignal, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSiriusxmSignal")
}

// EncodeFusionSiriusxmPresets encodes a FusionSiriusxmPresets struct to NMEA 2000 wire format
func EncodeFusionSiriusxmPresets(p *FusionSiriusxmPresets, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for FusionSiriusxmPresets")
}

// EncodeMaretronProprietaryTemperatureHighRange encodes a MaretronProprietaryTemperatureHighRange struct to NMEA 2000 wire format
func EncodeMaretronProprietaryTemperatureHighRange(p *MaretronProprietaryTemperatureHighRange, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for MaretronProprietaryTemperatureHighRange")
}

// EncodeBGKeyValueData encodes a BGKeyValueData struct to NMEA 2000 wire format
func EncodeBGKeyValueData(p *BGKeyValueData, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for BGKeyValueData")
}

// EncodeMaretronSwitchStatusCounter encodes a MaretronSwitchStatusCounter struct to NMEA 2000 wire format
func EncodeMaretronSwitchStatusCounter(p *MaretronSwitchStatusCounter, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for MaretronSwitchStatusCounter")
}

// EncodeMaretronSwitchStatusTimer encodes a MaretronSwitchStatusTimer struct to NMEA 2000 wire format
func EncodeMaretronSwitchStatusTimer(p *MaretronSwitchStatusTimer, stream *DataStream) (*MessageInfo, error) {
	// Implementation will be added when we implement encoding
	return nil, fmt.Errorf("encoding not yet implemented for MaretronSwitchStatusTimer")
}
